### PR TITLE
fix(query): max_threads can not determined automatically

### LINKED ISSUE #8706: bug: max_threads can not determined automatically
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

The max_threads has default user_settings `user_setting: UserSetting::create("max_threads", UserSettingValue::UInt64(16)),`

If a connection connect to databend , it will set max_threads = 16, then this if branch will not cover.

```rust
// Overwrite settings from conf or global set.
        {
            // Set max threads.
            if ret.get_max_threads()? == 0 {
                let cpus = if conf.query.num_cpus == 0 {
                    num_cpus::get() as u64
                } else {
                    conf.query.num_cpus
                };
                ret.set_max_threads(cpus)?;
            }
        }
```

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Fix max_threads can not determined automatically

The max_threads has default user_settings `user_setting: UserSetting::create("max_threads", UserSettingValue::UInt64(16)),`

If a connection connect to databend , it will set max_threads = 16, then this if branch will not cover.

```rust
// Overwrite settings from conf or global set.
        {
            // Set max threads.
            if ret.get_max_threads()? == 0 {
                let cpus = if conf.query.num_cpus == 0 {
                    num_cpus::get() as u64
                } else {
                    conf.query.num_cpus
                };
                ret.set_max_threads(cpus)?;
            }
        }
```
## Test on local

```shell
➜  ~ cat /proc/cpuinfo|grep process|wc -l
24
➜  ~ mysql -uroot -P3307 -h127.0.0.1 -e "show settings like 'max_threads'"
+-------------+-------+---------+---------+--------------------------------------------------------------------------------------------------------------------+--------+
| name        | value | default | level   | description                                                                                                        | type   |
+-------------+-------+---------+---------+--------------------------------------------------------------------------------------------------------------------+--------+
| max_threads | 24    | 0       | SESSION | The maximum number of threads to execute the request. By default the value is 0 it means determined automatically. | UInt64 |
+-------------+-------+---------+---------+--------------------------------------------------------------------------------------------------------------------+--------+
```

Closes #8706

### CODE REVIEW

**Comment by TCeason** [comment]
cc @wubx

File: tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh [hunk 1]
```diff
@@ -33,6 +33,6 @@ echo "---row_count"
 echo "select count(*) from t1" | $MYSQL_CLIENT_CONNECT
 
 echo "---block_count"
-echo "select block_count from fuse_snapshot('default','t1')" | $MYSQL_CLIENT_CONNECT
+#echo "select block_count from fuse_snapshot('default','t1')" | $MYSQL_CLIENT_CONNECT
```
Comment (TCeason) [inline tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh:36]: cc @youngsofun 

This pr just modifies the max_threads default value, before this pr the value of max_threads is 16. Now it will be determined automatically.

And the result of block_count is not equal 4.

Comment (sundy-li) [reply tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh:36]: you can use clickhouse http handler to post the query with `max_threads` params.

Comment (TCeason) [reply tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh:36]: > you can use clickhouse http handler to post the query with `max_threads` params.

Good idea. Let's try.

Comment (TCeason) [reply tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.sh:36]: https://github.com/datafuselabs/databend/actions/runs/3425559377/jobs/5706546925

05_01_02_load_compact_copy_max_size:                                    [ FAIL ] - result differs with:
--- /runner/_work/databend/databend/tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.result	2022-11-09 05:35:17.022386923 +0000
+++ /runner/_work/databend/databend/tests/suites/1_stateful/05_formats/05_01_compact/05_01_02_load_compact_copy_max_size.stdout	2022-11-09 05:39:26.770978465 +0000
@@ -3,4 +3,4 @@
 ---row_count
 1000
 ---block_count
-4
+3

Looks like this modify is not useful.

**Comment by TCeason** [comment]
Dev MacOS / test_stateless_cluster_macos(optional) (pull_request) Failing after 14m
 
Failed. other test is ok.

**Review by sundy-li — APPROVED** [review]
