### PR TITLE
fix(query): rewrite desc stage query

### LINKED ISSUE #7200: bug: `DESC STAGE` returns nothing in MySQL console
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

59595a94453d8c7d31e52bc8c3fd84dce8e84a21

### What's Wrong?

`DESC STAGE` returns nothing in the MySQL console. Check [here](https://pastebin.com/tBk2JYji) to see detailed DataBend-Query logs on SQL `DESC STAGE my_local_stage`.
```MySQL
SELECT VERSION();
# +----------------------------------------------------------------------------------------+
# | version()                                                                              |
# +----------------------------------------------------------------------------------------+
# | 8.0.26-v0.6.66-nightly-59595a9-simd(rust-1.64.0-nightly-2022-08-19T09:00:42.32012814Z) |
# +----------------------------------------------------------------------------------------+

CREATE STAGE my_local_stage;

# upload files to my_local_stage through HTTP

SHOW STAGES;

# +----------------+------------+-----------------+--------------------+---------+
# | name           | stage_type | number_of_files | creator            | comment |
# +----------------+------------+-----------------+--------------------+---------+
# | my_local_stage | Internal   |               1 | 'root'@'127.0.0.1' |         |
# +----------------+------------+-----------------+--------------------+---------+
DESC STAGE my_local_stage;

# Query OK, 0 rows affected (0.038 sec)
# Read 1 rows, 381.00 B in 0.021 sec., 48.33 rows/sec., 17.98 KiB/sec.
```

In expectation, `DESC STAGE` should be showing a table like https://databend.rs/doc/load-data/stage#step-1-create-stage-object did.

Only MySQL handler is affected. ClickHouse HTTP and DataBend HTTP all work well.
working on ClickHouse and HTTP

Meanwhile `DESC TABLE` works fine
```MySQL
SHOW TABLES;

# +-------------------+
# | tables_in_default |
# +-------------------+
# | tbl               |
# +-------------------+

DESC tbl;

# +--------+---------+------+---------+-------+
# | Field  | Type    | Null | Default | Extra |
# +--------+---------+------+---------+-------+
# | id     | INT     | NO   | 0       |       |
# | slogan | VARCHAR | NO   |         |       |
# +--------+---------+------+---------+-------+
```

### How to Reproduce?

1. checkout to the main branch, 59595a9 is not really far away
2. run DataBend-Query on the local filesystem
```shell
RUST_LOG=debug STORAGE_TYPE=fs cargo run --bin databend-query
```
3. connect to Query with MySQL client, and run SQL scripts described in `What's Wrong`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #7200

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

**Review by ClSlaid — APPROVED** [review]

File: src/query/service/src/interpreters/access/management_mode_access.rs [hunk 1]
```diff
@@ -62,6 +62,7 @@ impl ManagementModeAccess {
                             | RewriteKind::ShowFunctions
                             | RewriteKind::ShowUsers
                             | RewriteKind::ShowStages
+                            | RewriteKind::DescribeStage
```
Comment (ClSlaid) [inline src/query/service/src/interpreters/access/management_mode_access.rs:65]: https://github.com/datafuselabs/databend/blob/59595a94453d8c7d31e52bc8c3fd84dce8e84a21/src/query/service/src/sql/planner/plans/mod.rs#L211-L227
Does this compile?

Comment (sundy-li) [reply src/query/service/src/interpreters/access/management_mode_access.rs:65]: It's outdated.
