### PR TITLE
fix(copy): fix not return error when copy

### LINKED ISSUE #9900: Bug: 0 rows affected on COPY a 1.7gb parquet file from stage with FORCE = true
**Summary**

version:

```
DatabendQuery v0.9.19-nightly-4c83ef5(rust-1.68.0-nightly-2023-01-30T16:23:53.145240877Z)
```

to reproduce:

1) presign the file:

```
PRESIGN UPLOAD @~/lineitem.parquet;
```

2) upload to aws s3:

```
╰─$ curl -v --upload-file /Users/yazhou/Downloads/lineitem.parquet {presignedURL}
```

after load successfully, try LIST to check its size is correct:

Screen Shot 2023-02-05 at 14 17 29

3) do COPY with FORCE:

```
COPY INTO yazhou.lineitem FROM @~/lineitem.parquet file_format = (type = parquet) FORCE = true;
```

got response:

```
0 rows affected | 1.2s ago
```

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

DO NOT ignore errors on copy

Closes #9900

### CODE REVIEW

File: src/query/pipeline/sources/src/input_formats/input_pipeline.rs [hunk 1]
```diff
@@ -211,11 +211,7 @@ pub trait InputFormatPipe: Sized + Send + 'static {
                     while let Some(row_batch) = futs.next().await {
                         match row_batch {
                             Ok(row_batch) => {
-                                if row_batch.is_ok() {
-                                    if data_tx2.send(row_batch).await.is_err() {
-                                        break;
-                                    }
-                                } else {
+                                if data_tx2.send(row_batch).await.is_err() {
```
Comment (BohuTANG) [inline src/query/pipeline/sources/src/input_formats/input_pipeline.rs:214]: We can improve the variable name `data_tx2` to a meaningful name here.

**Review by BohuTANG — APPROVED** [review]
