### PR TITLE
fix(query): check limit vec length

### LINKED ISSUE #12639: bug: limit parser logic
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main version

### What's Wrong?

Limit only has two way:

```
limit n
limit n,m => limit m offset n
```

Now limit parser is 

```
 LIMIT ~ ^#comma_separated_list1(expr)
```

### How to Reproduce?

So we can run this query successfully in databend:

```sql
select * from numbers(2) limit 0,1,safe;
+--------+
| number |
+--------+
|      0 |
+--------+

```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

- Closes #12639

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12640)

### CODE REVIEW

File: src/query/ast/src/parser/query.rs [hunk 1]
```diff
@@ -144,11 +145,17 @@ pub fn set_operation_element(i: Input) -> IResult<WithSpan<SetOperationElement>>
...
         |(_, _, order_by)| SetOperationElement::OrderBy { order_by },
     );
-    let limit = map(
+    let limit = map_res(
         rule! {
             LIMIT ~ ^#comma_separated_list1(expr)
         },
-        |(_, limit)| SetOperationElement::Limit { limit },
+        |(_, limit)| {
+            if limit.len() > 2 {
```
Comment (b41sh) [inline src/query/ast/src/parser/query.rs:153]: How about checking in the `postfix` function?

File: tests/sqllogictests/suites/query/select.test [hunk 2]
```diff
@@ -96,3 +96,6 @@ values (1, 'one'), (2, 'two'), (3, 'three') order by col0 desc limit 2
 ----
 3 three
 2 two
+
+statement error 1005
+select * from numbers(2) limit 0,1,safe;
```
Comment (andylokandy) [inline tests/sqllogictests/suites/query/select.test:101]:
```suggestion
select * from numbers(2) limit 0,1,dummy;
```

**Review by andylokandy — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]

**Review by b41sh — APPROVED** [review]
