### PR TITLE
fix(query): fix add/subtract datetime with big integer panic

### LINKED ISSUE #12911: bug: `add` and `minus` date with big integer panic
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.118-nightly

### What's Wrong?

`add` and `minus` date with big integer panic
```
panicked at 'called `Option::unwrap()` on a `None` value', src/query/expression/src/utils/date_helper.rs:250:64
```

### How to Reproduce?

```sql
mysql> select minus(to_date(927407), 2453255792146787571);
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 19144 panicked.
```

```sql
mysql> select add(to_date(927407), 2453255792146787571);
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 19229 panicked.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- fix add/subtract datetime with big integer panic
- add `to_quarter` function

Closes #12911

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12940)

### CODE REVIEW

**Review by ariesdevil — APPROVED** [review]
LGTM

File: src/query/functions/src/scalars/datetime.rs [hunk 1]
```diff
@@ -1027,23 +1041,18 @@ fn register_to_number_functions(registry: &mut FunctionRegistry) {
...
-
-                Some(FunctionDomain::Domain(SimpleDomain::<i32> {
-                    min: ln.checked_add(rn)?,
-                    max: lm.checked_add(rm)?,
-                }))
-            })()
-            .unwrap_or(FunctionDomain::Full)
-        },
-        |a, b, _| a + (b as i32),
+        |_, _, _| FunctionDomain::MayThrow,
```
Comment (sundy-li) [inline src/query/functions/src/scalars/datetime.rs:1046]: This will affect constant folder which make example query with filter `timestamp + 3 >  t2` fail to prune partitions.

**Review by sundy-li — APPROVED** [review]
