### PR TITLE
fix: fix count rewrite in agg index

### LINKED ISSUE #14249: aggregating index status issue
**Summary**

# Queries
```
CREATE STAGE IF NOT EXISTS wizardbend
    URL = 's3://wizardbend/'
    CONNECTION = (ALLOW_ANONYMOUS = 'true');

CREATE TABLE onebrc (
    station_name VARCHAR NULL,
    measurement  DOUBLE  NULL
);

create aggregating index agg_onebrc as SELECT station_name,
       MIN(measurement) AS min_measurement,
       AVG(measurement) AS mean_measurement,
       MAX(measurement) AS max_measurement
FROM onebrc
GROUP BY station_name;

COPY INTO onebrc
FROM (
    SELECT *
    FROM @wizardbend/1brc/measurements.parquet
);
```

# Issues

`@wizardbend/1brc/measurements.parquet` has 1B rows.
There are **3** issues:
1. The progress status is very large, hunders of billion rows processed.
2. It seems the aggregating index refresh after *ALL* the copy is done, not during the COPY? **This broken the transaction**:If i cannel the copy(actually it is in refreshing index phase), but we have commit to the meta, it's not tansactional to the user.
3. `EXPLAIN SELECT station_name,
       MIN(measurement) AS min_measurement,
       AVG(measurement) AS mean_measurement,
       MAX(measurement) AS max_measurement
FROM onebrc
GROUP BY station_name;` There is no aggregating index can be used.
```
Exchange
├── output columns: [MIN(measurement) (#5), MAX(measurement) (#8), onebrc.station_name (#0), mean_measurement (#9)]
├── exchange type: Merge
└── EvalScalar
    ├── output columns: [MIN(measurement) (#5), MAX(measurement) (#8), onebrc.station_name (#0), mean_measurement (#9)]
    ├── expressions: [sum(measurement) (#6) / CAST(if(CAST(count(measurement) (#7) = 0 AS Boolean NULL), 1, count(measurement) (#7)) AS UInt64 NULL)]
    ├── estimated rows: 1000000000.00
    └── AggregateFinal
        ├── output columns: [MIN(measurement) (#5), sum(measurement) (#6), count(measurement) (#7), MAX(measurement) (#8), onebrc.station_name (#0)]
        ├── group by: [station_name]
        ├── aggregate functions: [min(measurement), sum(measurement), count(measurement), max(measurement)]
        ├── estimated rows: 1000000000.00
        └── Exchange
            ├── output columns: [MIN(measurement) (#5), sum(measurement) (#6), count(measurement) (#7), MAX(measurement) (#8), #_group_by_key]
            ├── exchange type: Hash(_group_by_key)
            └── AggregatePartial
                ├── output columns: [MIN(measurement) (#5), sum(measurement) (#6), count(measurement) (#7), MAX(measurement) (#8), #_group_by_key]
                ├── group by: [station_name]
                ├── aggregate functions: [min(measurement), sum(measurement), count(measurement), max(measurement)]
                ├── estimated rows: 1000000000.00
                └── TableScan
                    ├── table: default.default.onebrc
                    ├── output columns: [station_name (#0), measurement (#1)]
                    ├── read rows: 1000000000
                    ├── read bytes: 4911961194
                    ├── partitions total: 1200
                    ├── partitions scanned: 1200
                    ├── pruning stats: [segments: <range pruning: 2 to 2>, blocks: <range pruning: 1200 to 1200, bloom pruning: 0 to 0>]
                    ├── push downs: [filters: [], limit: NONE]
                    └── estimated rows: 1000000000.00
```

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

`count(col)` will be rewritten to `count()` if col is NOT nullable, as create agg index will rewrite statement and don't know the col's datatype, we will provide both `count(col)` and `count()` for agg index, make query rewrite with agg index happy.

Fixes #14249 

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14256)

### CODE REVIEW

File: src/query/sql/src/planner/semantic/aggregating_index_visitor.rs [hunk 1]
```diff
@@ -180,11 +180,16 @@ impl AggregatingIndexRewriter {
...
     }
 
+    // If `arg[0]` data type is *NOT* nullable, the optimizer will rewrite `count(arg)` to `count()`,
+    // this happened in `RuleID::NormalizeAggregate`.
+    // But here we cannot get the arg[0] type, so we provide both `count(arg)` and `count()`.
     pub fn extract_avg(&mut self, args: &[Expr]) {
         let sum = format!("SUM({})", args[0]);
-        let count = "COUNT()".to_string();
+        let count = format!("COUNT({})", args[0]);
+        let count_without_column = "COUNT()".to_string();
```
Comment (sundy-li) [inline src/query/sql/src/planner/semantic/aggregating_index_visitor.rs:189]: see: `rewrite_avg`
```
fn rewrite_avg(&self, args: &[Expr]) -> Option<Expr> {
        let text = format!(
            "sum({}) / if(count({}) = 0, 1, count({}))",
            args[0], args[0], args[0]
        );

        if let Ok(tokens) = tokenize_sql(&text) {
            if let Ok(new_expr) = parse_expr(&tokens, self.sql_dialect) {
                return Some(new_expr);
            }
        }

        None
    }
```

**Review by sundy-li — APPROVED** [review]
