### PR TITLE
ISSUE-3698: Support `as` case-insensitive when create udf

### LINKED ISSUE #3698: UDF: CREATE FUNCTION mean2number as (x,y)-> (x+y) / 2; ERROR 1105 (HY000): Code: 5, displayText = sql parser error: Expected AS, found: as.
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

mysql> CREATE FUNCTION mean2number as (x,y)-> (x+y) / 2;
ERROR 1105 (HY000): Code: 5, displayText = sql parser error: Expected AS, found: as.

### What You Expected?

Supports AS  or as 

### How to Reproduce?

mysql> CREATE FUNCTION mean2number as (x,y)-> (x+y) / 2;
ERROR 1105 (HY000): Code: 5, displayText = sql parser error: Expected AS, found: as.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevinw66**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Support `as` case-insensitive when create udf

## Changelog

- Bug Fix

## Related Issues

Fixes #3698

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

File: query/src/sql/sql_parser.rs [hunk 1]
```diff
@@ -948,8 +948,7 @@ impl<'a> DfParser<'a> {
                 .parse_keywords(&[Keyword::IF, Keyword::NOT, Keyword::EXISTS]);
 
         let udf_name = self.parser.parse_literal_string()?;
-        let as_token = Token::make_keyword("AS");
-        self.parser.expect_token(&as_token)?;
+        self.parser.expect_keyword(Keyword::AS)?;
```
Comment (BohuTANG) [inline query/src/sql/sql_parser.rs:951]: It would be better to add a test like:
https://github.com/datafuselabs/databend/blob/bf989b9bae6234518937814e57692ae5a9313205/query/tests/it/sql/sql_parser.rs#L1409-L1418

```
 expect_parse_ok( 
     "CREATE FUNCTION test_udf as (p, d) -> not(isnotnull(p, d)) DESC = 'this is a description'", 
     DfStatement::CreateUDF(DfCreateUDF { 
         if_not_exists: false, 
         udf_name: "test_udf".to_string(), 
         parameters: vec!["p".to_string(), "d".to_string()], 
         definition: "not(isnotnull(p,d))".to_string(), 
         description: "this is a description".to_string(), 
     }), 
 )?; 
```

Comment (kevinw66) [reply query/src/sql/sql_parser.rs:951]: done

**Comment by BohuTANG** [comment]
/lgtm

Thank you @kevinw66 !
