### PR TITLE
fix: try to fix table name case sensibility

### LINKED ISSUE #9049: Bug: table name can't find
**Summary**

`select A.* from (WITH source2 AS (select 1 as e) SELECT * FROM source2) A;`

`A` will transfer to `a`, so the SQL won't find table `A`.

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

`select A.* from (WITH source2 AS (select 1 as e) SELECT * FROM source2) A;`

`A` will transfer to `a` and add to `ColumnBinding`, so the SQL won't find table `A` when `normalize_select_list`.

Introduce `compare_table_name` method to compare table name correctly.

Btw, the ticket also spilt `normalize_select_list` method

Closes #9049

### CODE REVIEW

File: src/query/sql/src/planner/binder/project.rs [hunk 1]
```diff
@@ -307,6 +214,142 @@ impl<'a> Binder {
...
+                        scalar: BoundColumnRef {
+                            column: column_binding.clone(),
+                        }
+                        .into(),
+                        alias: column_binding.column_name.clone(),
+                    });
+                }
+            } else if let Some(name) = &column_binding.table_name {
+                if push_item
+                    && compare_table_name(
```
Comment (xudong963) [inline src/query/sql/src/planner/binder/project.rs:257]: The main changed place

**Review by TCeason — APPROVED** [review]

**Comment by xudong963** [comment]
@mergify update
