### PR TITLE
fix(query): cast with keyword err

### LINKED ISSUE #9548: bug:  cast(position as) return error
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.8.177

### What's Wrong?

Run SQL error:

```
1005:error: 
   --> SQL:46:19
   |
 1 | with __dbt__cte__commit_comments_ab1 as (
   | ---- while parsing `SELECT ...`
   .
30 | 
31 | -- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
32 | -- depends_on: __dbt__cte__commit_comments_ab1
33 | select
   | ------ while parsing `SELECT ...`
   .
43 |     cast(user as json) as user,
44 |     cast(node_id as String) as node_id,
45 |     cast(html_url as String) as html_url,
46 |     cast(position as
   |     ---- -------- ^^ expected `(`
   |     |    |         
   |     |    while parsing `POSITION(... IN ...)`
   |     while parsing `CAST(... AS ...)`
   |     while parsing expression
```

### How to Reproduce?

Run the following SQL:

```
select
    cast(id as
    BIGINT
) as id,
    cast(url as String) as url,
    cast(body as String) as body,
    cast(line as
    BIGINT
) as line,
    cast(path as String) as path,
    cast(user as json) as user,
    cast(node_id as String) as node_id,
    cast(html_url as String) as html_url,
    cast(position as
    BIGINT
) as position,
    cast(commit_id as String) as commit_id,
    cast(nullif(created_at, '') as
    TIMESTAMP
) as created_at,
    cast(repository as String) as repository,
    cast(nullif(updated_at, '') as
    TIMESTAMP
) as updated_at,
    cast(author_association as String) as author_association,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    NOW() as _airbyte_normalized_at
from __dbt__cte__commit_comments_ab1
``` 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

```rust
let position = map(
    rule! {
        POSITION
        ~ ^"("
        ~ ^#subexpr(BETWEEN_PREC)
        ~ ^IN
        ~ ^#subexpr(0)
        ~ ^")"
    },
    |(_, _, substr_expr, _, str_expr, _)| ExprElement::Position {
        substr_expr: Box::new(substr_expr),
        str_expr: Box::new(str_expr),
    },
);
```

will be expand to this:

```rust
let position = map(
    nom::sequence::tuple((
        crate::match_token(POSITION),
        nom::combinator::cut(crate::match_text("(")),
        nom::combinator::cut(subexpr(BETWEEN_PREC)),
        nom::combinator::cut(crate::match_token(IN)),
        nom::combinator::cut(subexpr(0)),
        nom::combinator::cut(crate::match_text(")")),
    )),
    |(_, _, substr_expr, _, str_expr, _)| ExprElement::Position {
        substr_expr: Box::new(substr_expr),
        str_expr: Box::new(str_expr),
    },
);
```

If the cut returns an error, the parse simply breaks and does not attempt another branch.

So sql `select cast(position as string) from t` return parse error.

position is a common field name, so in this pr I modify it.

There are some code like position:

```
substring
extract
trim
trim_from

```

But these not a common schema name, so I think in this pr, we just need to modify position parse.

Closes #9548

### CODE REVIEW

File: src/query/ast/src/parser/expr.rs [hunk 1]
```diff
@@ -658,11 +658,11 @@ pub fn expr_element(i: Input) -> IResult<WithSpan<ExprElement>> {
     let position = map(
         rule! {
             POSITION
-            ~ ^"("
-            ~ ^#subexpr(BETWEEN_PREC)
-            ~ ^IN
-            ~ ^#subexpr(0)
-            ~ ^")"
+            ~ "("
```
Comment (sundy-li) [inline src/query/ast/src/parser/expr.rs:661]: please add some comments to help other people understand the difference.

Comment (TCeason) [reply src/query/ast/src/parser/expr.rs:661]: Ok that's a draft and I think we can modify more in this pr.

**Comment by sundy-li** [comment]
```
substring
extract
trim
trim_from
```

I think we could modify the first `"("` to `"("` for all these function styles AST.

**Comment by TCeason** [comment]
> ```
> substring
> extract
> trim
> trim_from
> ```
> 
> I think we could modify the first `"("` to `"("` for all these function styles AST.

Agree, we must first ensure that no errors are reported, and then ensure the accuracy of error prompts.

**Review by sundy-li — APPROVED** [review]

File: src/query/ast/src/parser/expr.rs [hunk 2]
```diff
@@ -648,17 +648,20 @@ pub fn expr_element(i: Input) -> IResult<WithSpan<ExprElement>> {
...
         rule! {
-            EXTRACT ~ ^"(" ~ ^#interval_kind ~ ^FROM ~ ^#subexpr(0) ~ ^")"
+            EXTRACT ~ "(" ~ ^#interval_kind ~ ^FROM ~ ^#subexpr(0) ~ ^")"
         },
         |(_, _, field, _, expr, _)| ExprElement::Extract {
             field,
             expr: Box::new(expr),
         },
     );
+    // ^"(" can expand to nom::combinator::cut(crate::match_text("(")).
```
Comment (andylokandy) [inline src/query/ast/src/parser/expr.rs:658]: The comment is correct but may become confusing for the people seeing it later.
