### PR TITLE
fix(processor): try fix cannot kill drop table

### LINKED ISSUE #7961: bug: cannot kill drop table xx all
A test:

Case1: if the compact deal with block, we can abort: -- can be aborted
```
mysql> optimize table t7861 compact;
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
ERROR 1152 (08S01): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed.
```

Case2: drop table xx all; -- can not be aborted
It seems we can't deal with block, so this case can not abort.

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/7959#issuecomment-1261944878_

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(processor): try fix cannot kill drop table

Fixes #7961

### CODE REVIEW

File: src/query/storages/fuse/src/operations/gc.rs [hunk 1]
```diff
@@ -228,29 +266,58 @@ impl FuseTable {
...
+                    "Aborted query, because the server is shutting down or the query was killed.",
+                ));
+            }
+
             if let Some(c) = CacheManager::instance().get_table_segment_cache() {
                 let cache = &mut *c.write();
                 cache.pop(x.as_str());
             }
+
+            if aborting.load(Ordering::Relaxed) {
```
Comment (BohuTANG) [inline src/query/storages/fuse/src/operations/gc.rs:291]: No need to check here?

Comment (BohuTANG) [reply src/query/storages/fuse/src/operations/gc.rs:291]: Let's delete the extra block if aborted before.

File: src/query/storages/fuse/src/operations/gc.rs [hunk 2]
```diff
@@ -228,29 +266,58 @@ impl FuseTable {
...
+                ));
+            }
+
             let loc = locs.snapshot_location_from_uuid(id, *ver)?;
             if let Some(c) = CacheManager::instance().get_table_snapshot_cache() {
                 let cache = &mut *c.write();
                 cache.pop(loc.as_str());
             }
+
+            if aborting.load(Ordering::Relaxed) {
```
Comment (BohuTANG) [inline src/query/storages/fuse/src/operations/gc.rs:315]: Same suggestion as above :)

**Review by Xuanwo — APPROVED** [review]
