### PR TITLE
fix(query): fix some tests that block `See you again`

### LINKED ISSUE #6891: New planner doesn't support `show tables in db1`

### LINKED ISSUE #6894: New planner doesn't support create table with select
```rust
static TEST_CREATE_QUERY_SELECT: &str =
         "CREATE TABLE default.test_b(a varchar, x int) select b, a from default.test_a";
```

### LINKED ISSUE #6901: New planner didn't do ManagementModeAccess check

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

1. show tables in db1 support to fix ISSUE-6891
2. create table as select to fix ISSUE-6894
3. fix management check with new planner in ISSUE-6901

Fixes #6891
Fixes #6894 
Fixes #6901

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

File: query/src/sql/planner/plans/mod.rs [hunk 1]
```diff
@@ -178,7 +173,7 @@ pub enum Plan {
     AlterUDF(Box<AlterUserUDFPlan>),
     DropUDF(Box<DropUserUDFPlan>),
 
-    // ShowRoles  -> Rewrite to Query,
+    // Role
```
Comment (TCeason) [inline query/src/sql/planner/plans/mod.rs:176]: // Account 

I think account is better.

**Review by TCeason — APPROVED** [review]
