### PR TITLE
fix(query): fix `database` and `user` related functions in planner v2

### LINKED ISSUE #6457: bug: planner v2 current_database() will lost connection
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main branch newest version

### What's Wrong?

lost mysql connection.

### How to Reproduce?

```sql
'root'@mysqldb 11:32:10 [system]> set enable_planner_v2 = 1;
Query OK, 0 rows affected (0.04 sec)

'root'@mysqldb 11:32:26 [system]> select current_database();
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    30
Current database: system

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    31
Current database: system

ERROR 2013 (HY000): Lost connection to MySQL server during query
'root'@mysqldb 11:32:30 [system]> set enable_planner_v2 = 0;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    32
Current database: system

Query OK, 0 rows affected (0.22 sec)

'root'@mysqldb 11:34:15 [system]> set enable_planner_v2 = 0;
Query OK, 0 rows affected (0.03 sec)

'root'@mysqldb 11:34:16 [system]> select current_database();
+----------------------------+
| current_database('system') |
+----------------------------+
| system                     |
+----------------------------+
1 row in set (0.05 sec)
Read 1 rows, 1.00 B in 0.010 sec., 104.82 rows/sec., 104.82 B/sec.


```

Error LOG

```
2022-07-05T03:32:30.500374Z DEBUG do_query{query="select current_database()"}: sqlparser::parser: next precedence: 0    
2022-07-05T03:32:30.502387Z ERROR do_query{query="select current_database()"}: common_tracing::panic_hook: panicked at 'index out of bounds: the len is 0 but the index is 0', common/functions/src/scalars/contexts/database.rs:59:12 backtrace=Backtrace [{ fn: "common_tracing::panic_hook::log_panic", file: "./common/tracing/src/panic_hook.rs", line: 31 }, { fn: "common_tracing::panic_hook::set_panic_hook::{{closure}}", file: "./common/tracing/src/panic_hook.rs", line: 26 }, { fn: "std::panicking::rust_panic_with_hook", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 702 }, { fn: "std::panicking::begin_panic_handler::{{closure}}", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 588 }, { fn: "std::sys_common::backtrace::__rust_end_short_backtrace", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys_common/backtrace.rs", line: 138 }, { fn: "rust_begin_unwind", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 584 }, { fn: "core::panicking::panic_fmt", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/panicking.rs", line: 142 }, { fn: "core::panicking::panic_bounds_check", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/panicking.rs", line: 84 }, { fn: "<common_functions::scalars::contexts::database::DatabaseFunction as common_functions::scalars::function::Function>::eval", file: "./common/functions/src/scalars/contexts/database.rs", line: 59 }, { fn: "<common_functions::scalars::function_adapter::FunctionAdapter as common_functions::scalars::function::Function>::eval", file: "./common/functions/src/scalars/function_adapter.rs", line: 115 }, { fn: "databend_query::common::evaluator::eval_node::EvalNode<VectorID>::eval", file: "./query/src/common/evaluator/eval_node.rs", line: 71 }, { fn: "databend_query::common::evaluator::eval_node::EvalNode<VectorID>::try_eval_const", file: "./query/src/common/evaluator/eval_node.rs", line: 86 }, { fn: "databend_query::sql::planner::semantic::type_check::TypeChecker::post_resolve::{{closure}}", file: "./query/src/sql/planner/semantic/type_check.rs", line: 114 }, { fn: "core::result::Result<T,E>::and_then", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/result.rs", line: 1352 }, { fn: "databend_query::sql::planner::semantic::type_check::TypeChecker::post_resolve", file: "./query/src/sql/planner/semantic/type_check.rs", line: 112 }, { fn: "databend_query::sql::planner::semantic::type_check::TypeChecker::resolve::{{closure}}", file: "./query/src/sql/planner/semantic/type_check.rs", line: 730 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "<core::pin::Pin<P> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/future.rs", line: 124 }, { fn: "databend_query::sql::planner::binder::scalar::ScalarBinder::bind::{{closure}}", file: "./query/src/sql/planner/binder/scalar.rs", line: 50 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::sql::planner::binder::project::<impl databend_query::sql::planner::binder::Binder>::normalize_select_list::{{closure}}", file: "./query/src/sql/planner/binder/project.rs", line: 172 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::sql::planner::binder::select::<impl databend_query::sql::planner::binder::Binder>::bind_select_stmt::{{closure}}", file: "./query/src/sql/planner/binder/select.rs", line: 90 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::sql::planner::binder::select::<impl databend_query::sql::planner::binder::Binder>::bind_set_expr::{{closure}}", file: "./query/src/sql/planner/binder/select.rs", line: 164 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "<core::pin::Pin<P> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/future.rs", line: 124 }, { fn: "databend_query::sql::planner::binder::select::<impl databend_query::sql::planner::binder::Binder>::bind_query::{{closure}}", file: "./query/src/sql/planner/binder/select.rs", line: 186 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::sql::planner::binder::Binder::bind_statement::{{closure}}", file: "./query/src/sql/planner/binder/mod.rs", line: 100 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "<core::pin::Pin<P> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/future.rs", line: 124 }, { fn: "databend_query::sql::planner::binder::Binder::bind::{{closure}}", file: "./query/src/sql/planner/binder/mod.rs", line: 89 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::sql::planner::Planner::plan_sql::{{closure}}", file: "./query/src/sql/planner/mod.rs", line: 62 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}::{{closure}}", file: "./query/src/servers/mysql/mysql_interactive_worker.rs", line: 308 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "<tracing::instrument::Instrumented<T> as core::future::future::Future>::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs", line: 272 }, { fn: "databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}", file: "./query/src/servers/mysql/mysql_interactive_worker.rs", line: 278 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "<databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorker<W> as opensrv_mysql::AsyncMysqlShim<W>>::on_query::{{closure}}", file: "./query/src/servers/mysql/mysql_interactive_worker.rs", line: 188 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "<core::pin::Pin<P> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/future.rs", line: 124 }, { fn: "opensrv_mysql::AsyncMysqlIntermediary<B,S>::run::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/opensrv-mysql-0.1.0/src/lib.rs", line: 519 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "opensrv_mysql::AsyncMysqlIntermediary<B,S>::run_with_options::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/opensrv-mysql-0.1.0/src/lib.rs", line: 251 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "databend_query::servers::mysql::mysql_session::MySQLConnection::run_on_stream::{{closure}}::{{closure}}", file: "./query/src/servers/mysql/mysql_session.rs", line: 52 }, { fn: "<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/future/mod.rs", line: 91 }, { fn: "tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs", line: 165 }, { fn: "tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs", line: 14 }, { fn: "tokio::runtime::task::core::CoreStage<T>::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs", line: 155 }, { fn: "tokio::runtime::task::harness::poll_future::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 470 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 492 }, { fn: "__rust_try" }, { fn: "std::panicking::try", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 456 }, { fn: "std::panic::catch_unwind", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panic.rs", line: 137 }, { fn: "tokio::runtime::task::harness::poll_future", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 458 }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll_inner", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 104 }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 57 }, { fn: "tokio::runtime::task::raw::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs", line: 144 }, { fn: "tokio::runtime::task::raw::RawTask::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs", line: 84 }, { fn: "tokio::runtime::task::LocalNotified<S>::run", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs", line: 376 }, { fn: "tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs", line: 435 }, { fn: "tokio::coop::with_budget::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs", line: 102 }, { fn: "std::thread::local::LocalKey<T>::try_with", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/thread/local.rs", line: 445 }, { fn: "std::thread::local::LocalKey<T>::with", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/thread/local.rs", line: 421 }, { fn: "tokio::coop::with_budget", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs", line: 95 }, { fn: "tokio::coop::budget", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs", line: 72 }, { fn: "tokio::runtime::thread_pool::worker::Context::run_task", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs", line: 434 }, { fn: "tokio::runtime::thread_pool::worker::Context::run", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs", line: 401 }, { fn: "tokio::runtime::thread_pool::worker::run::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs", line: 386 }, { fn: "tokio::macros::scoped_tls::ScopedKey<T>::set", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs", line: 61 }, { fn: "tokio::runtime::thread_pool::worker::run", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs", line: 383 }, { fn: "tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs", line: 362 }, { fn: "<tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs", line: 42 }, { fn: "tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs", line: 165 }, { fn: "tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs", line: 14 }, { fn: "tokio::runtime::task::core::CoreStage<T>::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs", line: 155 }, { fn: "tokio::runtime::task::harness::poll_future::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 470 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 492 }, { fn: "__rust_try" }, { fn: "std::panicking::try", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 456 }, { fn: "std::panic::catch_unwind", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panic.rs", line: 137 }, { fn: "tokio::runtime::task::harness::poll_future", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 458 }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll_inner", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 104 }, { fn: "tokio::runtime::task::harness::Harness<T,S>::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs", line: 57 }, { fn: "tokio::runtime::task::raw::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs", line: 144 }, { fn: "tokio::runtime::task::raw::RawTask::poll", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs", line: 84 }, { fn: "tokio::runtime::task::UnownedTask<S>::run", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs", line: 413 }, { fn: "tokio::runtime::blocking::pool::Task::run", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs", line: 91 }, { fn: "tokio::runtime::blocking::pool::Inner::run", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs", line: 325 }, { fn: "tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}", file: "/home/taichong/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs", line: 300 }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys_common/backtrace.rs", line: 122 }, { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/thread/mod.rs", line: 501 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 492 }, { fn: "__rust_try" }, { fn: "std::panicking::try", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panicking.rs", line: 456 }, { fn: "std::panic::catch_unwind", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/panic.rs", line: 137 }, { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/thread/mod.rs", line: 500 }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/core/src/ops/function.rs", line: 248 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/boxed.rs", line: 1951 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/alloc/src/boxed.rs", line: 1951 }, { fn: "std::sys::unix::thread::Thread::new::thread_start", file: "/rustc/ddcbba036aee08f0709f98a92a342a278eae5c05/library/std/src/sys/unix/thread.rs", line: 108 }, { fn: "start_thread", file: "/build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c", line: 477 }, { fn: "clone", file: "/build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S", line: 95 }] panic.file="common/functions/src/scalars/contexts/database.rs" panic.line=59 panic.column=12
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Defined2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

support current_database(), currentDatabase(), currentUser() functions in planner v2

Fixes #6457

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @TCeason @xudong963 
PTAL

File: query/src/sql/planner/semantic/type_check.rs [hunk 1]
```diff
@@ -1133,33 +1133,60 @@ impl<'a> TypeChecker<'a> {
...
+                Ok(user) => {
+                    let arg = Expr::Literal {
+                        span: &[],
+                        lit: Literal::String(user.identity().to_string()),
+                    };
+                    Some(self.resolve_function(span, "user", &[&arg], None).await)
+                }
+                Err(e) => Some(Err(e)),
+            },
+            "currentuser" => match self.ctx.get_current_user() {
```
Comment (TCeason) [inline query/src/sql/planner/semantic/type_check.rs:1167]: I think we do not need `currentuser`.

current_user is for clickhouse
user is for mysql

File: tests/suites/0_stateless/02_function/02_0003_function_database.sql [hunk 2]
```diff
@@ -1,2 +1,6 @@
-SELECT database(), currentDatabase();
+SELECT database(), currentDatabase(), current_database();
 
+set enable_planner_v2 = 1;
+SELECT database(), currentDatabase(), current_database();
```
Comment (TCeason) [inline tests/suites/0_stateless/02_function/02_0003_function_database.sql:4]: better to add this file: tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql

**Comment by BohuTANG** [comment]
Conflicting files
tests/suites/0_stateless/20+_others/20_0001_planner_v2.result
tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql

File: query/src/sql/planner/semantic/type_check.rs (hunk 1 above)
Comment (Defined2014) [reply query/src/sql/planner/semantic/type_check.rs:1167]: If not support this, it will panic. Maybe we can delete it in another PR (also delete it when planner = v1)

File: query/src/sql/planner/semantic/type_check.rs [hunk 3]
```diff
@@ -1185,33 +1185,60 @@ impl<'a> TypeChecker<'a> {
...
                 Some(self.resolve_function(span, "database", &[&arg], None).await)
             }
+            "currentdatabase" => {
+                let arg = Expr::Literal {
+                    span: &[],
+                    lit: Literal::String(self.ctx.get_current_database()),
+                };
+                Some(self.resolve_function(span, "currentdatabase", &[&arg], None).await)
+            }
+            "current_database" => {
```
Comment (sundy-li) [inline query/src/sql/planner/semantic/type_check.rs:1195]:
```suggestion
            "currentdatabase" | "current_database"=> {
                let arg = Expr::Literal {
                    span: &[],
                    lit: Literal::String(self.ctx.get_current_database()),
                };
                Some(self.resolve_function(span, func_name.to_lowercase().as_str(), &[&arg], None).await)
            }
```

Comment (Defined2014) [reply query/src/sql/planner/semantic/type_check.rs]: Done

File: query/src/sql/planner/semantic/type_check.rs [hunk 4]
```diff
@@ -1206,39 +1192,13 @@ impl<'a> TypeChecker<'a> {
...
-                    };
-                    Some(
-                        self.resolve_function(span, "currentuser", &[&arg], None)
-                            .await,
-                    )
-                }
-                Err(e) => Some(Err(e)),
-            },
-            "current_user" => match self.ctx.get_current_user() {
+            "user" | "currentuser" | "current_user" => match self.ctx.get_current_user() {
```
Comment (sundy-li) [inline query/src/sql/planner/semantic/type_check.rs:1195]: `name @("user" | "currentuser" | "current_user") => `

may be better, so we have a `name` variable.

**Review by sundy-li — APPROVED** [review]

**Review by TCeason — APPROVED** [review]

**Comment by TCeason** [comment]
@mergify update

**Comment by sundy-li** [comment]
cc @ZeaLoVe  the SQL logic test is failed, need help.

**Comment by ZeaLoVe** [comment]
> cc @ZeaLoVe the SQL logic test is failed, need help.

image

cc @youngsofun  http handler error, please take a look.
