### PR TITLE
fix(parser): fix parse float with E failed

### LINKED ISSUE #7156: bug: float exponent form does not support E
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.7.159-nightly-a7f2c58-simd(rust-1.64.0-nightly-2022-08-10T16:29:03.797735015Z)

### What's Wrong?

My program automatically generates a capital E
```sql
CREATE TABLE t0(c0 FLOAT NULL DEFAULT(true), c1 BOOL NULL DEFAULT(811681875));
INSERT INTO t0(c0, c1) VALUES (8.11681875E8, -568901493);

 Code: 1010, displayText = Expression size not match schema num of cols.
```

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix parse float with `E` failed

Fixes #7156

### CODE REVIEW

File: src/query/ast/src/parser/token.rs [hunk 1]
```diff
@@ -125,8 +125,8 @@ pub enum TokenKind {
     #[regex(r"[0-9]+")]
     LiteralInteger,
 
-    #[regex(r"[0-9]+e[+-]?[0-9]+")]
-    #[regex(r"([0-9]*\.[0-9]+(e[+-]?[0-9]+)?)|([0-9]+\.[0-9]*(e[+-]?[0-9]+)?)")]
+    #[regex(r"[0-9]+[eE][+-]?[0-9]+")]
+    #[regex(r"([0-9]*\.[0-9]+([eE][+-]?[0-9]+)?)|([0-9]+\.[0-9]*([eE][+-]?[0-9]+)?)")]
```
Comment (Xuanwo) [inline src/query/ast/src/parser/token.rs:129]: Is is a good idea to use https://docs.rs/nom/latest/nom/number/complete/fn.float.html directly?

Comment (b41sh) [reply src/query/ast/src/parser/token.rs:129]: use `nom::number::complete::float` to parse `LiteralFloat` token?

Comment (sundy-li) [reply src/query/ast/src/parser/token.rs:129]: How to use it into `derive`?

Comment (b41sh) [reply src/query/ast/src/parser/token.rs:129]: But other Literals are implemented with regular expressions, should they be replaced by `nom`?

Comment (sundy-li) [reply src/query/ast/src/parser/token.rs:129]: cc @andylokandy

Comment (andylokandy) [reply src/query/ast/src/parser/token.rs:129]: tokenizer usually use regular expression instead of parser, because the formaer is faster and must terminate. nom is a parser, so we can't use it here.

**Review by BohuTANG — APPROVED** [review]
