### PR TITLE
Fix group by empty

### LINKED ISSUE #4349: bug: empty blocks group by, range start index 1 out of range for slice of length 0
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

x

### What's Wrong?

```
 2022-03-07T01:10:22.5822126Z [2m2022-03-07T01:10:22.581877Z[0m [31mERROR[0m [2mcommon_tracing::panic_hook[0m[2m:[0m panicked at 'range start index 1 out of range for slice of length 0', /home/runner/work/databend/databend/common/datablocks/src/kernels/data_block_group_by_hash.rs:290:26 [3mbacktrace[0m[2m=[0m   0: common_tracing::panic_hook::set_panic_hook::{{closure}}
2022-03-07T01:10:22.5823061Z              at common/tracing/src/panic_hook.rs:25:25
2022-03-07T01:10:22.5823387Z    1: std::panicking::rust_panic_with_hook
2022-03-07T01:10:22.5823788Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:702:17
2022-03-07T01:10:22.5824206Z    2: std::panicking::begin_panic_handler::{{closure}}
2022-03-07T01:10:22.5824618Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:588:13
2022-03-07T01:10:22.5825018Z    3: std::sys_common::backtrace::__rust_end_short_backtrace
2022-03-07T01:10:22.5825454Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:138:18
2022-03-07T01:10:22.5825813Z    4: rust_begin_unwind
2022-03-07T01:10:22.5826173Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:584:5
2022-03-07T01:10:22.5826523Z    5: core::panicking::panic_fmt
2022-03-07T01:10:22.5826903Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panicking.rs:143:14
2022-03-07T01:10:22.5827297Z    6: core::slice::index::slice_start_index_len_fail
2022-03-07T01:10:22.5827680Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/slice/index.rs:35:5
2022-03-07T01:10:22.5828128Z    7: <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index
2022-03-07T01:10:22.5828572Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/slice/index.rs:329:13
2022-03-07T01:10:22.5829004Z       core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
2022-03-07T01:10:22.5829409Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/slice/index.rs:15:9
2022-03-07T01:10:22.5829899Z       common_datablocks::kernels::data_block_group_by_hash::HashMethodFixedKeys<T>::deserialize_group_columns
2022-03-07T01:10:22.5830380Z              at common/datablocks/src/kernels/data_block_group_by_hash.rs:290:26
2022-03-07T01:10:22.5830983Z    8: <databend_query::pipelines::transforms::transform_group_by_final::GroupByFinalTransform as databend_query::pipelines::processors::processor::Processor>::execute::{{closure}}::{{closure}}
2022-03-07T01:10:22.5831575Z              at query/src/pipelines/transforms/transform_group_by_final.rs:253:9
2022-03-07T01:10:22.5831999Z    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:22.5832449Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:22.5833051Z       <databend_query::pipelines::transforms::transform_group_by_final::GroupByFinalTransform as databend_query::pipelines::processors::processor::Processor>::execute::{{closure}}
2022-03-07T01:10:22.5833629Z              at query/src/pipelines/transforms/transform_group_by_final.rs:86:5
2022-03-07T01:10:22.5834281Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:22.5834729Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:22.5835141Z   10: <core::pin::Pin<P> as core::future::future::Future>::poll
2022-03-07T01:10:22.5835570Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/future.rs:124:9
2022-03-07T01:10:22.5836035Z       databend_query::pipelines::processors::processor_merge::MergeProcessor::merge::{{closure}}
2022-03-07T01:10:22.5836484Z              at query/src/pipelines/processors/processor_merge.rs:60:63
2022-03-07T01:10:22.5837016Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:22.5837462Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:22.5837891Z   11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
2022-03-07T01:10:22.5838578Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.31/src/instrument.rs:272:9
2022-03-07T01:10:22.5839042Z   12: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
2022-03-07T01:10:22.5839663Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
2022-03-07T01:10:22.5840099Z       tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2022-03-07T01:10:22.5840715Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
2022-03-07T01:10:22.5841166Z       tokio::runtime::task::core::CoreStage<T>::poll
2022-03-07T01:10:22.5841770Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
2022-03-07T01:10:22.5842205Z       tokio::runtime::task::harness::poll_future::{{closure}}
2022-03-07T01:10:22.5842829Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
2022-03-07T01:10:22.5843348Z       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-03-07T01:10:22.5843830Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
2022-03-07T01:10:22.5844191Z       std::panicking::try::do_call
2022-03-07T01:10:22.5844562Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
2022-03-07T01:10:22.5844914Z       std::panicking::try
2022-03-07T01:10:22.5845261Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
2022-03-07T01:10:22.5845620Z       std::panic::catch_unwind
2022-03-07T01:10:22.5845980Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
2022-03-07T01:10:22.5846363Z       tokio::runtime::task::harness::poll_future
2022-03-07T01:10:22.5846964Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
2022-03-07T01:10:22.5847422Z   13: tokio::runtime::task::harness::Harness<T,S>::poll_inner
2022-03-07T01:10:22.5848329Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
2022-03-07T01:10:22.5848783Z       tokio::runtime::task::harness::Harness<T,S>::poll
2022-03-07T01:10:22.5849386Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
2022-03-07T01:10:22.5849824Z   14: tokio::runtime::task::raw::RawTask::poll
2022-03-07T01:10:22.5850417Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
2022-03-07T01:10:22.5851272Z       tokio::runtime::task::LocalNotified<S>::run
2022-03-07T01:10:22.5851859Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
2022-03-07T01:10:22.5852434Z       tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
2022-03-07T01:10:22.5853113Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:425:13
2022-03-07T01:10:22.5853550Z       tokio::coop::with_budget::{{closure}}
2022-03-07T01:10:22.5854091Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
2022-03-07T01:10:22.5854507Z       std::thread::local::LocalKey<T>::try_with
2022-03-07T01:10:22.5854905Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/local.rs:413:16
2022-03-07T01:10:22.5855356Z       std::thread::local::LocalKey<T>::with
2022-03-07T01:10:22.5855743Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/local.rs:389:9
2022-03-07T01:10:22.5856100Z       tokio::coop::with_budget
2022-03-07T01:10:22.5856647Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
2022-03-07T01:10:22.5857010Z       tokio::coop::budget
2022-03-07T01:10:22.5857541Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
2022-03-07T01:10:22.5857968Z       tokio::runtime::thread_pool::worker::Context::run_task
2022-03-07T01:10:22.5858602Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
2022-03-07T01:10:22.5859044Z   15: tokio::runtime::thread_pool::worker::Context::run
2022-03-07T01:10:22.5859677Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:398:24
2022-03-07T01:10:22.5860136Z       tokio::runtime::thread_pool::worker::run::{{closure}}
2022-03-07T01:10:22.5860763Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
2022-03-07T01:10:22.5861198Z       tokio::macros::scoped_tls::ScopedKey<T>::set
2022-03-07T01:10:22.5861873Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
2022-03-07T01:10:22.5862305Z       tokio::runtime::thread_pool::worker::run
2022-03-07T01:10:22.5862921Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
2022-03-07T01:10:22.5863382Z   16: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
2022-03-07T01:10:22.5864032Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
2022-03-07T01:10:22.5864549Z       <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
2022-03-07T01:10:22.5865214Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
2022-03-07T01:10:22.5865660Z       tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
2022-03-07T01:10:22.5866270Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
2022-03-07T01:10:22.5866709Z       tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2022-03-07T01:10:22.5867585Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
2022-03-07T01:10:22.5868014Z       tokio::runtime::task::core::CoreStage<T>::poll
2022-03-07T01:10:22.5868619Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
2022-03-07T01:10:22.5869072Z       tokio::runtime::task::harness::poll_future::{{closure}}
2022-03-07T01:10:22.5869690Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
2022-03-07T01:10:22.5870273Z       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-03-07T01:10:22.5870748Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
2022-03-07T01:10:22.5871127Z       std::panicking::try::do_call
2022-03-07T01:10:22.5871505Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
2022-03-07T01:10:22.5871839Z       std::panicking::try
2022-03-07T01:10:22.5872200Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
2022-03-07T01:10:22.5872554Z       std::panic::catch_unwind
2022-03-07T01:10:22.5872967Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
2022-03-07T01:10:22.5873352Z       tokio::runtime::task::harness::poll_future
2022-03-07T01:10:22.5873967Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
2022-03-07T01:10:22.5874428Z       tokio::runtime::task::harness::Harness<T,S>::poll_inner
2022-03-07T01:10:22.5875026Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
2022-03-07T01:10:22.5875471Z       tokio::runtime::task::harness::Harness<T,S>::poll
2022-03-07T01:10:22.5876077Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
2022-03-07T01:10:22.5876487Z       tokio::runtime::task::raw::poll
2022-03-07T01:10:22.5877044Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
2022-03-07T01:10:22.5877467Z   17: tokio::runtime::task::raw::RawTask::poll
2022-03-07T01:10:22.5878053Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
2022-03-07T01:10:22.5878475Z       tokio::runtime::task::UnownedTask<S>::run
2022-03-07T01:10:22.5879048Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
2022-03-07T01:10:22.5879470Z       tokio::runtime::blocking::pool::Task::run
2022-03-07T01:10:22.5880064Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
2022-03-07T01:10:22.5880498Z       tokio::runtime::blocking::pool::Inner::run
2022-03-07T01:10:22.5881084Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
2022-03-07T01:10:22.5881594Z       tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
2022-03-07T01:10:22.5882243Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
2022-03-07T01:10:22.5882697Z       std::sys_common::backtrace::__rust_begin_short_backtrace
2022-03-07T01:10:22.5883111Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:122:18
2022-03-07T01:10:22.5883551Z   18: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
2022-03-07T01:10:22.5883984Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:498:17
2022-03-07T01:10:22.5884435Z       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-03-07T01:10:22.5884911Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
2022-03-07T01:10:22.5885283Z       std::panicking::try::do_call
2022-03-07T01:10:22.5885657Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
2022-03-07T01:10:22.5885995Z       std::panicking::try
2022-03-07T01:10:22.5886359Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
2022-03-07T01:10:22.5886715Z       std::panic::catch_unwind
2022-03-07T01:10:22.5887151Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
2022-03-07T01:10:22.5887531Z       std::thread::Builder::spawn_unchecked_::{{closure}}
2022-03-07T01:10:22.5888155Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:497:30
2022-03-07T01:10:22.5888574Z       core::ops::function::FnOnce::call_once{{vtable.shim}}
2022-03-07T01:10:22.5888990Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/ops/function.rs:227:5
2022-03-07T01:10:22.5889409Z   19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-03-07T01:10:22.5889830Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
2022-03-07T01:10:22.5890336Z       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-03-07T01:10:22.5890757Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
2022-03-07T01:10:22.5891135Z       std::sys::unix::thread::Thread::new::thread_start
2022-03-07T01:10:22.5891541Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys/unix/thread.rs:108:17
2022-03-07T01:10:22.5891882Z   20: start_thread
2022-03-07T01:10:22.5892095Z   21: clone
```

### What You Expected?

x

### How to Reproduce?

_No response_

### Anything Else?

x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

 
- Bug Fix
 
## Related Issues

Fixes #4349

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

File: common/datablocks/src/kernels/data_block_group_by_hash.rs [hunk 1]
```diff
@@ -167,6 +167,7 @@ impl HashMethodSerializer {
         keys: Vec<Vec<u8>>,
         group_fields: &[DataField],
     ) -> Result<Vec<ColumnRef>> {
+        debug_assert!(!keys.is_empty());
```
Comment (BohuTANG) [inline common/datablocks/src/kernels/data_block_group_by_hash.rs:170]: How about the `debug_assert` performance affects?

Comment (sundy-li) [reply common/datablocks/src/kernels/data_block_group_by_hash.rs:170]: it's only enabled in debug mode, which will be useful to detect the bugs in ci.

See: https://doc.rust-lang.org/std/macro.debug_assert.html
