### PR TITLE
compatibility mysql insert and select

### LINKED ISSUE #4861: Compatibility MySQL insert
**Summary**
want databend can support load mydumer | mysqldump MySQL data.

```
CREATE TABLE `sbtest2` (
  `id` int NOT NULL,
  `k` int NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ;

INSERT INTO `sbtest2` VALUES(1,24940,"50739423477-59896895752-91121550334-25071371310-03454727381-25307272676-12883025003-48844794346-97662793974-67443907837","10824941535-62754685647-36430831520-45812593797-70371571680");
```

>ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named "50739423477-59896895752-91121550334-25071371310-03454727381-25307272676-12883025003-48844794346-97662793974-67443907837". Valid fields: ["id", "k", "c", "pad"].
ERROR: No query specified

Expect：
**make that insert work.**

```
2022-04-14T10:50:55.976888Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1006, displayText = Unable to get field named "50739423477-59896895752-91121550334-25071371310-03454727381-25307272676-12883025003-48844794346-97662793974-67443907837". Valid fields: ["id", "k", "c", "pad"].

   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::BadArguments
             at /home/wu/databend/common/exception/src/exception_code.rs:36:66
   1: common_datavalues::data_schema::DataSchema::index_of
             at /home/wu/databend/common/datavalues/src/data_schema.rs:103:13
   2: common_datavalues::data_schema::DataSchema::field_with_name
             at /home/wu/databend/common/datavalues/src/data_schema.rs:86:25
      <common_planners::plan_expression_common::ExpressionDataTypeVisitor as common_planners::plan_expression_visitor::ExpressionVisitor>::post_visit
             at /home/wu/databend/common/planners/src/plan_expression_common.rs:426:29
   3: common_planners::plan_expression_visitor::ExpressionVisitor::visit
             at /home/wu/databend/common/planners/src/plan_expression_visitor.rs:41:28
      common_planners::plan_expression::Expression::to_data_type
             at /home/wu/databend/common/planners/src/plan_expression.rs:293:9
   4: databend_query::sql::statements::value_source::exprs_to_datablock::{{closure}}
             at /home/wu/databend/query/src/sql/statements/value_source.rs:122:24
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      databend_query::sql::statements::value_source::ValueSource::parser_read::{{closure}}
             at /home/wu/databend/query/src/sql/statements/value_source.rs:107:75
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      databend_query::sql::statements::statement_insert::DfInsertStatement::analyze_insert_values::{{closure}}
             at /home/wu/databend/query/src/sql/statements/statement_insert.rs:155:73
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      <databend_query::sql::statements::statement_insert::DfInsertStatement as databend_query::sql::statements::analyzer_statement::AnalyzableStatement>::analyze::{{closure}}::{{closure}}
             at /home/wu/databend/query/src/sql/statements/statement_insert.rs:88:78
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   5: <databend_query::sql::statements::statement_insert::DfInsertStatement as databend_query::sql::statements::analyzer_statement::AnalyzableStatement>::analyze::{{closure}}
             at /home/wu/databend/query/src/sql/statements/statement_insert.rs:76:5
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/future.rs:124:9
      <databend_query::sql::sql_statement::DfStatement as databend_query::sql::statements::analyzer_statement::AnalyzableStatement>::analyze::{{closure}}
             at /home/wu/databend/query/src/sql/statements/analyzer_statement.rs:171:58
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/future.rs:124:9
      databend_query::sql::plan_parser::PlanParser::build_plan::{{closure}}
             at /home/wu/databend/query/src/sql/plan_parser.rs:62:49
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   8: databend_query::sql::plan_parser::PlanParser::parse_with_hint::{{closure}}
             at /home/wu/databend/query/src/sql/plan_parser.rs:48:80
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}::{{closure}}
             at /home/wu/databend/query/src/servers/mysql/mysql_interactive_worker.rs:276:88
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   9: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}
             at /home/wu/databend/query/src/servers/mysql/mysql_interactive_worker.rs:262:5
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  10: <databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorker<W> as opensrv_mysql::AsyncMysqlShim<W>>::on_query::{{closure}}
             at /home/wu/databend/query/src/servers/mysql/mysql_interactive_worker.rs:177:47
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/future.rs:124:9
      opensrv_mysql::AsyncMysqlIntermediary<B,S>::run::{{closure}}
             at /home/wu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:513:30
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      opensrv_mysql::AsyncMysqlIntermediary<B,S>::run_with_options::{{closure}}
             at /home/wu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:250:17
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      opensrv_mysql::AsyncMysqlIntermediary<B,S>::run_on::{{closure}}
             at /home/wu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:230:66
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      databend_query::servers::mysql::mysql_session::MySQLConnection::run_on_stream::{{closure}}::{{closure}}
             at /home/wu/databend/query/src/servers/mysql/mysql_session.rs:44:88
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  13: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/core.rs:161:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/core.rs:151:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:467:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:456:19
  14: std::panic::catch_unwind
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  15: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:103:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  16: tokio::runtime::task::raw::RawTask::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/raw.rs:80:18
      tokio::runtime::task::LocalNotified<S>::run
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/mod.rs:347:9
      tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/thread_pool/worker.rs:448:21
      tokio::coop::with_budget::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/coop.rs:102:9
      std::thread::local::LocalKey<T>::try_with
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/thread/local.rs:442:16
      std::thread::local::LocalKey<T>::with
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/thread/local.rs:418:9
      tokio::coop::with_budget
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/coop.rs:95:5
      tokio::coop::budget
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/coop.rs:72:5
      tokio::runtime::thread_pool::worker::Context::run_task
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
  17: tokio::runtime::thread_pool::worker::Context::run
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/thread_pool/worker.rs:391:24
      tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
      tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
      tokio::runtime::thread_pool::worker::run
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
  18: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
      tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/core.rs:161:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/core.rs:151:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:467:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:455:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:103:27
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/harness.rs:57:15
      tokio::runtime::task::raw::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  19: tokio::runtime::task::raw::RawTask::poll
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/raw.rs:80:18
      tokio::runtime::task::UnownedTask<S>::run
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/task/mod.rs:384:9
      tokio::runtime::blocking::pool::Task::run
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
      tokio::runtime::blocking::pool::Inner::run
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
      tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:122:18
  20: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/thread/mod.rs:498:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/thread/mod.rs:497:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/ops/function.rs:227:5
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys/unix/thread.rs:108:17
  22: start_thread
             at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  23: clone
````

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

compatibility double quoted for MySQL:

```SQL
insert into t values("xxx");
show tables where table_name like "";
show databases where name like "";
select "";
select * from t where name = "";
select * from t2 where id in ("1");
select * from t2 where c between "" and "";
select * from t2 where id like "";
```

## Changelog

- Improvement
- Build/Testing/CI

## Related Issues

Fixes #4861 #1551

### CODE REVIEW

**Comment by BohuTANG** [comment]
The error is:
```
Traceback (most recent call last):
  File "/workspace/tests/suites/0_stateless/10_drivers/10_0000_python_clickhouse_driver.py", line 6, in <module>
    from clickhouse_driver import connect
ModuleNotFoundError: No module named 'clickhouse_driver'
```

For new setup tools, we should first open a new for `clickhouse_driver` first, then merge to this PR, there is a demo(install sqlalchemy module a few days ago) : https://github.com/datafuselabs/databend/pull/4775

**Comment by BohuTANG** [comment]
@mergify update

File: tools/fuzz/fuzz_targets/fuzz_parse_sql.rs [hunk 1]
```diff
@@ -12,13 +12,15 @@
...
+use databend_query::sessions::Session;
+use databend_query::sessions::SessionType;
 use databend_query::sql::DfParser;
 use honggfuzz::fuzz;
 
 fn main() {
     loop {
         fuzz!(|data: String| {
-            let _ = DfParser::parse_sql(&data);
+            let _ = DfParser::parse_sql(&data, SessionType::Fuzz);
```
Comment (BohuTANG) [inline tools/fuzz/fuzz_targets/fuzz_parse_sql.rs:23]: Hmm, how to run fuzz?

Comment (TCeason) [reply tools/fuzz/fuzz_targets/fuzz_parse_sql.rs:23]: Actually, I also have some issues with this file. I'm not sure why we need this file. And can not find where it is used.

To build success, I add a new SessionType Fuzz.

File: query/src/sql/statements/analyzer_value_expr.rs [hunk 2]
```diff
@@ -19,16 +19,29 @@ use common_planners::Expression;
...
-    pub fn analyze(value: &Value) -> Result<Expression> {
+    pub fn analyze(value: &Value, typ: SessionType) -> Result<Expression> {
         match value {
             Value::Null => Self::analyze_null_value(),
             Value::Boolean(value) => Self::analyze_bool_value(value),
             Value::Number(value, _) => Self::analyze_number_value(value, None),
             Value::HexStringLiteral(value) => Self::analyze_number_value(value, Some(16)),
             Value::SingleQuotedString(value) => Self::analyze_string_value(value),
+            Value::DoubleQuotedString(value) => {
+                if let SessionType::MySQL = typ {
```
Comment (BohuTANG) [inline query/src/sql/statements/analyzer_value_expr.rs:35]: Here should add more comments to explain why we need `SessionType::MySQL`

File: query/src/sql/sql_parser.rs [hunk 3]
```diff
@@ -73,12 +75,26 @@ impl<'a> DfParser<'a> {
...
     /// Parse a SQL statement and produce a set of statements with dialect
-    pub fn parse_sql(sql: &'a str) -> Result<(Vec<DfStatement<'a>>, Vec<DfHint>), ErrorCode> {
-        let dialect = &GenericDialect {};
-        let start = Instant::now();
-        let result = DfParser::parse_sql_with_dialect(sql, dialect)?;
-        histogram!(super::metrics::METRIC_PARSER_USEDTIME, start.elapsed());
-        Ok(result)
+    pub fn parse_sql(
+        sql: &'a str,
+        typ: SessionType,
```
Comment (BohuTANG) [inline query/src/sql/sql_parser.rs:80]: If databend default sql dialect is `MySqlDialect`, the problems is?

Comment (BohuTANG) [reply query/src/sql/sql_parser.rs:80]: So we no need a `SessionType` there

File: query/src/sql/sql_parser.rs [hunk 4]
```diff
@@ -73,12 +75,26 @@ impl<'a> DfParser<'a> {
...
+    ) -> Result<(Vec<DfStatement<'a>>, Vec<DfHint>), ErrorCode> {
+        match typ {
+            SessionType::MySQL => {
+                let dialect = &MySqlDialect {};
```
Comment (b41sh) [inline query/src/sql/sql_parser.rs:84]: Looks like there are some duplicate codes.
How about
```rust
let dialect = match ...
```

File: query/src/sql/statements/value_source.rs [hunk 5]
```diff
@@ -150,11 +152,23 @@ async fn exprs_to_datablock(
...
-    let dialect = GenericDialect {};
-    let sql = std::str::from_utf8(buf).unwrap();
-    let mut tokenizer = Tokenizer::new(&dialect, sql);
-    let (tokens, position_map) = tokenizer.tokenize()?;
-    let mut parser = Parser::new(tokens, position_map, &dialect);
-    parser.parse_values()
+fn parse_exprs(buf: &[u8], typ: SessionType) -> std::result::Result<Vec<Vec<Expr>>, ParserError> {
+    match typ {
+        SessionType::MySQL => {
+            let dialect = MySqlDialect {};
```
Comment (b41sh) [inline query/src/sql/statements/value_source.rs:158]: Ditto

File: tests/suites/0_stateless/03_dml/03_0018_insert_into_variant.sql [hunk 6]
```diff
@@ -37,7 +37,7 @@ select * from t3;
 select arr[0] from t3;
 select arr[5] from t3;
 select arr[3][0] from t3;
-select arr[4]["k"] from t3;
```
Comment (b41sh) [inline tests/suites/0_stateless/03_dml/03_0018_insert_into_variant.sql:40]: Do double-quoted strings cause errors?

File: query/src/sql/sql_parser.rs (hunk 4 above)
Comment (TCeason) [reply query/src/sql/sql_parser.rs:84]: Sessiontype has different tpye .
I can not set a val with diff type

File: query/src/sql/sql_parser.rs (hunk 3 above)
Comment (TCeason) [reply query/src/sql/sql_parser.rs:80]: If use ClickHouse Client connect Databend server or ClickHouse server SQL like 

select “number” will return col value

But use MySQL client it will return a string

Comment (TCeason) [reply query/src/sql/sql_parser.rs:80]: tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql

like this test

Comment (sundy-li) [reply query/src/sql/sql_parser.rs:80]: Double quota is not sql standard(not allowed by Snowflake, Pg, ClickHouse), it's just for MySQL...

So we need this special `SessionType `

**Review by sundy-li — APPROVED** [review]

File: query/src/sql/sql_parser.rs [hunk 7]
```diff
@@ -57,7 +59,7 @@ pub struct DfParser<'a> {
 impl<'a> DfParser<'a> {
     /// Parse the specified tokens
     pub fn new(sql: &'a str) -> Result<Self, ParserError> {
```
Comment (BohuTANG) [inline query/src/sql/sql_parser.rs:61]: This function is no used anymore? We can remove it.

**Comment by BohuTANG** [comment]
Tips:
When the PR review starts, we try to avoid using `force-pushed`, because it loses a lot of information and the review doesn't know what was changed on the last change.

**Review by BohuTANG — APPROVED** [review]
lgtm

File: tools/fuzz/fuzz_targets/fuzz_parse_sql.rs (hunk 1 above)
Comment (TCeason) [reply tools/fuzz/fuzz_targets/fuzz_parse_sql.rs:23]: Hi @PsiACE Are we using this for testing now? And how can I use it for databend query?

Comment (PsiACE) [reply tools/fuzz/fuzz_targets/fuzz_parse_sql.rs:23]: Fuzz type is not necessary, I think it makes more sense to use it for fuzz testing of existing session types. As for how to run the fuzz test, you can see https://github.com/datafuselabs/databend/blob/main/tools/fuzz/README.md

It is not integrated in CI for now, and I am not sure if there are plans to use it to improve our parser. We have introduced the fuzz test in #700. It has helped us in the past to make some small improvements to the parser or the upstream sqlparser.
