### PR TITLE
fix(query): fix binary default string

### LINKED ISSUE #14721: bug: create table binary type with default value panic
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.347-nightly

### What's Wrong?

```
panicked at src/query/sql/src/planner/expression_parser.rs:409:79:
removal index (is 0) should be < len (is 0)
   0: databend_common_tracing::panic_hook::log_panic
```

### How to Reproduce?

```sql
mysql> create table t1(a int, b binary NOT NULL DEFAULT 'abc');
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = unable to cast type `UInt32` to type `Binary`.

mysql> create table t1(a int, b binary NOT NULL DEFAULT '');
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 512 panicked.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

fix(query): fix binary default string

fixes #14721 

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16345)

### CODE REVIEW

**Review by b41sh — APPROVED** [review]

File: src/query/expression/src/utils/display.rs [hunk 1]
```diff
@@ -773,7 +773,22 @@ impl<Index: ColumnIndex> Expr<Index> {
...
+                        "'nan'::Float64".to_string()
+                    }
+                    Scalar::Number(NumberScalar::Float32(f)) if f.is_infinite() => {
+                        "'inf'::Float32".to_string()
+                    }
+                    Scalar::Number(NumberScalar::Float64(f)) if f.is_infinite() => {
+                        "'inf'::Float64".to_string()
+                    }
+                    other => other.as_ref().to_string(),
+                },
```
Comment (andylokandy) [inline src/query/expression/src/utils/display.rs:791]: Maybe move these logic to `impl Display for NumberScalar`?

File: src/query/expression/src/utils/display.rs [hunk 2]
```diff
@@ -773,7 +773,22 @@ impl<Index: ColumnIndex> Expr<Index> {
...
+                        "'nan'::Float32".to_string()
+                    }
+                    Scalar::Number(NumberScalar::Float64(f)) if f.is_nan() => {
+                        "'nan'::Float64".to_string()
+                    }
+                    Scalar::Number(NumberScalar::Float32(f)) if f.is_infinite() => {
+                        "'inf'::Float32".to_string()
+                    }
+                    Scalar::Number(NumberScalar::Float64(f)) if f.is_infinite() => {
+                        "'inf'::Float64".to_string()
```
Comment (andylokandy) [inline src/query/expression/src/utils/display.rs:788]: missing -inf

File: src/query/expression/src/utils/display.rs (hunk 1 above)
Comment (sundy-li) [reply src/query/expression/src/utils/display.rs:791]: this is SQL display for parser, we should not change the default output style of scalar.

**Review by andylokandy — APPROVED** [review]
