### PR TITLE
fix: only check aggregate functions when create aggregating index

### LINKED ISSUE #12564: Feature: support to_start_of_minute in aggregation index
**Summary**

> Currently create aggregating index just support these aggregate functions: sum, min, max, avg.
> I am not able to create the index due to this error
> My usecase is that I want to create this aggregates over dimensions and ? to_start_of_minute(event_time) aggregation
> My query
> CREATE SYNC AGGREGATING INDEX test_agg AS SELECT
>    id,
>    platform,
>    to_start_of_minute(event_time)) AS ts,
>    sum(1) AS count_value
> FROM events
> WHERE (ts > (now() - toIntervalMinute(15))) AND (event_name IN ('ABC', 'XYZ'))
> GROUP BY
>    id,
>    platform,
>    ts

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

* only check aggregate functions when creating aggregating index
* disallow non-deterministic funcs like `now()` in aggregating index.
* fix index read with both scalar and agg func, thx @RinChanNOWWW 

Closes #12564

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12565)

### CODE REVIEW

**Review by RinChanNOWWW — DISMISSED** [review]

**Comment by BohuTANG** [comment]
It would be better to add a logic test for it(If we had, this bug can not happens before).

**Review by sundy-li — APPROVED** [review]

**Comment by BohuTANG** [comment]
> > It would be better to add a logic test for it(If we had, this bug can not happen).↳
> 
> After adding more tests, more bugs were found :(

 🤔 
 
If the PR introduces a new feature, please ensure there is some SQL logic tests. 
Without it, I think the PR shouldn't be approved. 

Kindly cc: @sundy-li and @RinChanNOWWW

**Comment by ariesdevil** [comment]
> > > It would be better to add a logic test for it(If we had, this bug can not happen).↳
> > 
> > 
> > After adding more tests, more bugs were found :(↳
> 
> 🤔
> 
> If the PR introduces a new feature, please ensure there is some SQL logic tests. Without it, I think the PR shouldn't be approved.↳
> 
> Kindly cc: @sundy-li and @RinChanNOWWW

approve is fine, the original pr was already covered by adding test_fuzz, but when I added sqllogictests, I found more problems that I wanted to fix all in this pr.

**Comment by BohuTANG** [comment]
Ensure your SQL logic is validated using the same as the end user. While `test_fuzz` and `unit test` are not substitutes for this validation, consider using them if you're uncertain about your function's reliability.

File: src/query/sql/src/planner/binder/ddl/index.rs [hunk 1]
```diff
@@ -220,12 +226,18 @@ impl Binder {
         Ok(plan)
     }
 
-    fn check_index_support(query: &Query) -> Result<()> {
+    fn check_index_support(query: &Query, has_now_func: bool) -> Result<()> {
+        let now_func = "now";
```
Comment (RinChanNOWWW) [inline src/query/sql/src/planner/binder/ddl/index.rs:230]: Better way: get the function signature and check if `is_deterministic`. Because there are other functions are not deterministic such as `random`.

Comment (ariesdevil) [reply src/query/sql/src/planner/binder/ddl/index.rs:230]: Oh yep, I forgot to modify this, nice capture.

**Review by sundy-li — APPROVED** [review]

File: src/query/sql/src/planner/semantic/aggregating_index_visitor.rs [hunk 2]
```diff
@@ -137,3 +149,29 @@ impl VisitorMut for AggregatingIndexRewriter {
...
+        _lambda: &'ast Option<Lambda>,
+    ) {
+        if self.has_no_deterministic_func {
+            return;
+        }
+
+        self.has_no_deterministic_func = match BUILTIN_FUNCTIONS.get_property(&name.name) {
+            Some(property) => property.non_deterministic,
+            None => false,
+        };
```
Comment (RinChanNOWWW) [inline src/query/sql/src/planner/semantic/aggregating_index_visitor.rs:171]:
```suggestion
        self.has_no_deterministic_func = BUILTIN_FUNCTIONS.get_property(&name.name).map(|p| p.non_deterministic).unwrap_or(false);
```
