### PR TITLE
fix(executor): fix lost pipeline on finished callback

### LINKED ISSUE #15649: bug: lost query (abort) log when query is kill by http handler.
**Summary**

https://github.com/datafuselabs/databend/blob/main/tests/suites/1_stateful/09_http_handler/09_0005_kill.sh#L16

all seen cases are in cluster mode

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

fix(executor): fix lost pipeline on finished callback

- Fixes #15649 

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15693)

### CODE REVIEW

File: src/query/pipeline/core/src/finished_chain.rs [hunk 1]
```diff
@@ -0,0 +1,388 @@
...
+                    location,
+                    is_always: false,
+                    successfully: false,
+                    elapsed: instant.elapsed(),
+                });
+
+                info.res = Err(cause.clone());
+                Self::apply_always(info, states, always_callbacks);
+
+                return Err(cause);
```
Comment (youngsofun) [inline src/query/pipeline/core/src/finished_chain.rs:100]: logging the locations of callbacks that have not run may help debug too.
otherwise, some developers may be unaware of its existence, making it difficult to associate the program’s erroneous behavior with it.

File: src/query/pipeline/core/src/finished_chain.rs [hunk 2]
```diff
@@ -0,0 +1,388 @@
...
+                Ok(_) => ApplyState {
+                    location,
+                    is_always: true,
+                    successfully: true,
+                    elapsed: instant.elapsed(),
+                },
+                Err(_cause) => ApplyState {
+                    location,
+                    is_always: true,
+                    successfully: false,
```
Comment (youngsofun) [inline src/query/pipeline/core/src/finished_chain.rs:132]: maybe not useful for now, but the cause can be recorded?

Comment (zhang2014) [reply src/query/pipeline/core/src/finished_chain.rs:132]: The cause may have been recorded in the log.

File: src/query/pipeline/core/src/finished_chain.rs [hunk 3]
```diff
@@ -0,0 +1,388 @@
...
+    fn apply(self: Box<Self>, info: &ExecutionInfo) -> Result<()> {
+        match catch_unwind(move || self(info)) {
+            Ok(Ok(_)) => Ok(()),
+            Err(cause) => Err(cause),
+            Ok(Err(cause)) => Err(cause),
+        }
+    }
+}
+
+pub struct AlwaysCallback<T: Callback> {
```
Comment (youngsofun) [inline src/query/pipeline/core/src/finished_chain.rs:186]: except for  `always`, do we need to add a flag to distinguish whether a callback failure will cause the statement to fail? Or should we just explain the current behavior through comments?”

File: src/query/pipeline/core/src/finished_chain.rs [hunk 4]
```diff
@@ -0,0 +1,388 @@
...
+                true => "\u{2705}",
+                false => "\u{274C}",
+            };
+
+            let always_state = match apply_state.is_always {
+                true => "(always) ",
+                false => "",
+            };
+
+            writeln!(
```
Comment (youngsofun) [inline src/query/pipeline/core/src/finished_chain.rs:180]: just a suggestion, I prefer to require a name for each `callback`, just like the processors, make it more readable.

and then we can display it by adding  just one line when display a pipeline ?

File: src/query/pipeline/core/src/finished_chain.rs (hunk 3 above)
Comment (zhang2014) [reply src/query/pipeline/core/src/finished_chain.rs:207]: `always` is special, by default, callback failure should always cause the statement to fail.

File: src/query/pipeline/core/src/finished_chain.rs (hunk 4 above)
Comment (zhang2014) [reply src/query/pipeline/core/src/finished_chain.rs:180]: Great suggestion. but it is only recorded in the log. Is the caller location okay?

File: src/query/pipeline/core/src/finished_chain.rs (hunk 3 above)
Comment (youngsofun) [reply src/query/pipeline/core/src/finished_chain.rs:207]: so `always` include 3 meanings

1.  itself always gets run, not affected by others 
2. if it fail, not affect others
3. if it fail, not affect a result of the stament.

**Review by youngsofun — APPROVED** [review]

File: src/query/pipeline/core/src/finished_chain.rs (hunk 4 above)
Comment (youngsofun) [reply src/query/pipeline/core/src/finished_chain.rs:180]: may ok if there are no more than 3 or 4 callbacks.
some can be identified from the file path if the debugger has seen it before.
