### PR TITLE
fix: select distinct

### LINKED ISSUE #5018: bug: select distinct
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.27-nightly

### What's Wrong?

`select distinct a from table` returns wrong result that is actually of `select a from table`.

### How to Reproduce?

create a table and select distinct

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by doki23**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix bug of `select distinct`

## Changelog

- distinct plan parser

## Related Issues

Fixes #5018

### CODE REVIEW

**Comment by sundy-li** [comment]
Thanks for the contributions, it needs a stateless test.

File: query/src/sql/plan_parser.rs [hunk 1]
```diff
@@ -75,13 +76,31 @@ impl PlanParser {
 
     pub fn build_query_plan(data: &QueryAnalyzeState) -> Result<PlanNode> {
         let from = Self::build_from_plan(data)?;
+        tracing::debug!("Build from plan:\n{:?}", from);
```
Comment (xudong963) [inline query/src/sql/plan_parser.rs:79]: need delete

File: query/src/sql/statements/analyzer_statement.rs [hunk 2]
```diff
@@ -80,12 +84,13 @@ impl Default for QueryAnalyzeState {
         QueryAnalyzeState {
             filter: None,
             having: None,
-            order_by_expressions: vec![],
-            expressions: vec![],
-            projection_expressions: vec![],
+            before_group_by_expressions: vec![],
```
Comment (Xuanwo) [inline query/src/sql/statements/analyzer_statement.rs:87]: Seems we can use derive `Default` on QueryAnalyzeState instead.

File: query/src/sql/plan_parser.rs (hunk 1 above)
Comment (doki23) [reply query/src/sql/plan_parser.rs:79]: It may helpful to print subquery plan.

**Comment by doki23** [comment]
> Thanks for the contributions, it needs a stateless test.

added

File: tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql [hunk 3]
```diff
@@ -16,3 +16,5 @@ SELECT b.number FROM (SELECT * FROM numbers(3) AS b) AS a ORDER BY b.number; --
 SELECT number, 'number', "number" FROM numbers(3) AS a order by a.number;
 SELECT 'That\'s good.';
 SELECT *; -- {ErrorCode 1015}
+SELECT DISTINCT * FROM numbers(3);
+SELECT DISTINCT 1 FROM numbers(3);
```
Comment (sundy-li) [inline tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql:20]: Add:  select distinct (number %3)  c from numbers(1000) order by c;

File: tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql [hunk 4]
```diff
@@ -16,3 +16,6 @@ SELECT b.number FROM (SELECT * FROM numbers(3) AS b) AS a ORDER BY b.number; --
 SELECT number, 'number', "number" FROM numbers(3) AS a order by a.number;
 SELECT 'That\'s good.';
 SELECT *; -- {ErrorCode 1015}
+SELECT DISTINCT * FROM numbers(3);
```
Comment (sundy-li) [inline tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql:19]: need order clause to keep the result stable.

**Review by sundy-li — APPROVED** [review]

File: tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql [hunk 5]
```diff
@@ -16,3 +16,6 @@ SELECT b.number FROM (SELECT * FROM numbers(3) AS b) AS a ORDER BY b.number; --
 SELECT number, 'number', "number" FROM numbers(3) AS a order by a.number;
 SELECT 'That\'s good.';
 SELECT *; -- {ErrorCode 1015}
+SELECT DISTINCT * FROM numbers(3) order by number;
```
Comment (BohuTANG) [inline tests/suites/0_stateless/00_dummy/00_0000_dummy_select_1.sql:19]: It would be better move the test to `suites/0_stateless/03_dml` like a new name: `03_0021_select_distinct.sql`.
