### PR TITLE
fix(query): the issue of (lpad,rpad) function getting hang

### LINKED ISSUE #12706: bug: `lpad` and `rpad` function does not respond if the `pad` string is empty
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.99-nightly

### What's Wrong?

`lpad` and `rpad` function does not respond if the `pad` string is empty

### How to Reproduce?

```sql
mysql> select lpad('', 1000, '');

mysql> select rpad('', 1000, '');
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nange**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

1. fix the issue of (lpad,rpad) function getting hang if the pad string is empty

- Closes #12706

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12760)

### CODE REVIEW

File: src/query/functions/src/scalars/string.rs [hunk 1]
```diff
@@ -139,7 +139,9 @@ pub fn register(registry: &mut FunctionRegistry) {
             |s, pad_len, pad, output, _| {
                 let pad_len = pad_len as usize;
                 if pad_len <= s.len() {
-                    output.put_slice(&s[..pad_len])
+                    output.put_slice(&s[..pad_len]);
```
Comment (b41sh) [inline src/query/functions/src/scalars/string.rs:142]: If the `pad_len` is greater than the length of `s` and the `pad` is empty, we should return an error message because it is not possible to fill the string to the `pad_len` with an empty string.

Comment (nange) [reply src/query/functions/src/scalars/string.rs:142]: Logically speacking, you are right. It's ok for me. Currently, I have adopted the same behavior as Postgres. I'll fix it.

Comment (nange) [reply src/query/functions/src/scalars/string.rs:142]: @b41sh PTAL.

**Review by b41sh — APPROVED** [review]
LGTM
