### PR TITLE
fix(query): union type not match just need return err

### LINKED ISSUE #10838: bug: union type not match , connection closed
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```sql
mysql> select [1,2,3] union all select 2;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    14
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    15
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #10838

### CODE REVIEW

**Review by xudong963 — APPROVED** [review]

File: src/query/sql/src/planner/binder/select.rs [hunk 1]
```diff
@@ -352,13 +352,17 @@ impl Binder {
...
                         *right_col.data_type.clone(),
                         &BUILTIN_FUNCTIONS.default_cast_rules,
-                    )
-                    .expect("SetOperation's types cannot be matched");
-                    coercion_types.push(data_type);
+                    ) {
+                        coercion_types.push(data_type);
+                    } else {
+                        return Err(ErrorCode::SemanticError(
+                            "SetOperation's types cannot be matched",
```
Comment (BohuTANG) [inline src/query/sql/src/planner/binder/select.rs:363]: Can we add the mismatch types to the error message?
