### PR TITLE
fix: use context's runtime in clickhouse handler  while executing interpreter

### LINKED ISSUE #9558: Bug:  databend-query hangs when running sqllogic test parallelly
**Summary**

_on behalf of @sundy-li_ :

databend-query hangs when running sqllogic test parallelly : 

- startup databend-query
~~~
export META_EMBEDDED_DIR="./.databend/meta_embedded"
export STORAGE_TYPE="fs"
./target/debug/databend-query --internal-enable-sandbox-tenant
~~~

- run sql logic test

~~~
cargo run -p sqllogictests -- --handlers clickhouse --parallel 8 --no-fail-fast --run_file 09_0 --enable_sandbox —debug
~~~

then, `databend-query` process will highly likely hang.

- sql logic test case can not run to end
- mysql client can not connect to databend-query

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

use context's runtime in clickhouse handler while executing interpreter

Closes #9558

### CODE REVIEW

**Comment by zhang2014** [comment]
> @zhang2014 PTAL : by using `ctx.spawn` to execute the interrupter, query process no longer hang. but I am not sure if using ctx’s runtime here is correct.

Look good to me.

File: src/query/service/src/servers/http/clickhouse_handler.rs [hunk 1]
```diff
@@ -112,7 +112,14 @@ async fn execute(
...
 ) -> Result<WithContentType<Body>> {
     let format_typ = format.typ.clone();
-    let mut data_stream = interpreter.execute(ctx.clone()).await?;
+    let mut data_stream = ctx
+        .try_spawn({
+            let ctx = ctx.clone();
+            async move { interpreter.execute(ctx.clone()).await }
+        })?
+        .await
+        .map_err(ErrorCode::from_std_error)??;
```
Comment (Xuanwo) [inline src/query/service/src/servers/http/clickhouse_handler.rs:121]: `from_std_error` will lost error context, how about using `map_err(|err| anyhow!("clickhouse handler failed to join interpreter thread: {err:?}"))` for better error message?

File: src/query/service/src/servers/http/clickhouse_handler.rs [hunk 2]
```diff
@@ -112,7 +112,14 @@ async fn execute(
     handle: Option<JoinHandle<()>>,
 ) -> Result<WithContentType<Body>> {
     let format_typ = format.typ.clone();
-    let mut data_stream = interpreter.execute(ctx.clone()).await?;
+    let mut data_stream = ctx
```
Comment (BohuTANG) [inline src/query/service/src/servers/http/clickhouse_handler.rs:115]: It would be better to add some comments here to explain why we need run it in context runtime

File: src/query/service/src/servers/http/clickhouse_handler.rs (hunk 1 above)
Comment (dantengsky) [reply src/query/service/src/servers/http/clickhouse_handler.rs:121]: yeah, that will be better

File: src/query/service/src/servers/http/clickhouse_handler.rs (hunk 2 above)
Comment (dantengsky) [reply src/query/service/src/servers/http/clickhouse_handler.rs:115]: ok

File: src/query/service/src/servers/http/clickhouse_handler.rs (hunk 1 above)
Comment (dantengsky) [reply src/query/service/src/servers/http/clickhouse_handler.rs]: PTAL, the error message has been updated as you suggested

File: src/query/service/src/servers/http/clickhouse_handler.rs (hunk 2 above)
Comment (dantengsky) [reply src/query/service/src/servers/http/clickhouse_handler.rs:148]: PTAL, the reason for spawning is documented, but rather lengthy,  failed to put it in a  concise way :(

File: src/query/service/src/servers/http/clickhouse_handler.rs [hunk 3]
```diff
@@ -112,13 +112,50 @@ async fn execute(
     handle: Option<JoinHandle<()>>,
 ) -> Result<WithContentType<Body>> {
     let format_typ = format.typ.clone();
+
+    // the reason of spawning new task to execute the interpreter:
```
Comment (Xuanwo) [inline src/query/service/src/servers/http/clickhouse_handler.rs:116]: Nice!

**Review by Xuanwo — APPROVED** [review]
