### PR TITLE
fix: update panic when contain window func

### LINKED ISSUE #13241: bug:  when update set expr is window func or avg func, the err msg is confusing
**Summary**

```sql
CREATE TABLE `test` (
  `c13` DATE NULL
) ENGINE=FUSE ;

insert into test values('2022-02-02');
Query OK, 1 row affected (0.107 sec)

UPDATE test SET c13 = last(to_date(911310)) OVER (PARTITION BY 'PdGqi', 'GJJ8R' ORDER BY 'gG3dk', 'o0whu' ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 1007 panicked.

```

in log:

```
panicked at 'called `Result::unwrap()` on an `Err` value: BadArguments. Code: 1006, Text = Unable to get field named "last(to_date(911310)) OVER (PARTITION BY 'PdGqi', 'GJJ8R' ORDER BY 'gG3dk', 'o0whu' ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)". Valid fields: ["c13"].

   0: common_exception::exception_backtrace::capture
             at src/common/exception/src/exception_backtrace.rs:72:17
   1: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::BadArguments
             at src/common/exception/src/exception_code.rs:35:30
   2: common_expression::schema::TableSchema::index_of
             at src/query/expression/src/schema.rs:586:13
   3: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::try_add_update_source::{{closure}}::{{closure}}::{{closure}}
             at src/query/storages/fuse/src/operations/update.rs:201:44
   4: common_expression::expression::Expr<Index>::project_column_ref
             at src/query/expression/src/expression.rs:309:21
   5: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::try_add_update_source::{{closure}}::{{closure}}
             at src/query/storages/fuse/src/operations/update.rs:199:24
   6: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
   7: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  10: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  11: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  12: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  13: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::try_add_update_source::{{closure}}
             at src/query/storages/fuse/src/operations/update.rs:120:5
  14: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::do_update::{{closure}}::{{closure}}
             at src/query/storages/fuse/src/operations/update.rs:96:10
  15: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  16: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  19: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  20: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  21: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  22: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::do_update::{{closure}}
             at src/query/storages/fuse/src/operations/update.rs:49:5
  23: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::update::{{closure}}::{{closure}}
             at src/query/storages/fuse/src/fuse_table.rs:668:10
  24: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  25: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  26: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  27: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  28: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  29: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  30: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  31: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::update::{{closure}}
             at src/query/storages/fuse/src/fuse_table.rs:648:5
  32: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  33: <databend_query::interpreters::interpreter_update::UpdateInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at src/query/service/src/interpreters/interpreter_update.rs:186:10
  34: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  36: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at src/query/service/src/interpreters/interpreter.rs:55:51
  37: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  38: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  39: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  40: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  41: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  42: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  43: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  44: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at src/query/service/src/interpreters/interpreter.rs:45:5
  45: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  46: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase::exec_query::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/query/service/src/servers/mysql/mysql_interactive_worker.rs:395:76
  47: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  48: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  49: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  50: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  51: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  52: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  53: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  54: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  55: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  56: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  57: tokio::runtime::task::core::Core<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  58: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  59: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  60: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  61: __rust_try
  62: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  63: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  64: tokio::runtime::task::harness::poll_future
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  65: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  66: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  67: tokio::runtime::task::raw::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  68: tokio::runtime::task::raw::RawTask::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  69: tokio::runtime::task::LocalNotified<S>::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  70: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  71: tokio::runtime::coop::with_budget
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  72: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  73: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  74: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  75: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  76: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  77: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  78: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  79: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  80: tokio::runtime::task::core::Core<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  81: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  82: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  83: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  84: __rust_try
  85: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  86: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  87: tokio::runtime::task::harness::poll_future
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  88: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  89: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  90: tokio::runtime::task::raw::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  91: tokio::runtime::task::raw::RawTask::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  92: tokio::runtime::task::UnownedTask<S>::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  93: tokio::runtime::blocking::pool::Task::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  94: tokio::runtime::blocking::pool::Inner::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  95: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
  96: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  97: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  98: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  99: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
 100: __rust_try
 101: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
 102: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:528:30
 103: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
 104: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
      call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
      thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
 105: <unknown>
 106: <unknown>
', src/query/storages/fuse/src/operations/update.rs:201:72
   0: common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:597:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: unwrap_failed
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/result.rs:1651:5
   9: core::result::Result<T,E>::unwrap
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/result.rs:1076:23
  10: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::try_add_update_source::{{closure}}::{{closure}}::{{closure}}
             at ./src/query/storages/fuse/src/operations/update.rs:201:44
  11: common_expression::expression::Expr<Index>::project_column_ref
             at ./src/query/expression/src/expression.rs:309:21
  12: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::try_add_update_source::{{closure}}::{{closure}}
             at ./src/query/storages/fuse/src/operations/update.rs:199:24
  13: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  14: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  16: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  17: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  18: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  19: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  20: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::try_add_update_source::{{closure}}
             at ./src/query/storages/fuse/src/operations/update.rs:120:5
  21: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::do_update::{{closure}}::{{closure}}
             at ./src/query/storages/fuse/src/operations/update.rs:96:10
  22: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  23: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  24: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  25: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  26: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  27: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  28: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  29: common_storages_fuse::operations::update::<impl common_storages_fuse::fuse_table::FuseTable>::do_update::{{closure}}
             at ./src/query/storages/fuse/src/operations/update.rs:49:5
  30: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::update::{{closure}}::{{closure}}
             at ./src/query/storages/fuse/src/fuse_table.rs:668:10
  31: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  32: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  35: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  36: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  37: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  38: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::update::{{closure}}
             at ./src/query/storages/fuse/src/fuse_table.rs:648:5
  39: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  40: <databend_query::interpreters::interpreter_update::UpdateInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at ./src/query/service/src/interpreters/interpreter_update.rs:186:10
  41: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  42: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  43: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at ./src/query/service/src/interpreters/interpreter.rs:55:51
  44: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  45: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  46: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  47: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  48: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  49: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  50: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  51: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at ./src/query/service/src/interpreters/interpreter.rs:45:5
  52: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  53: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase::exec_query::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/query/service/src/servers/mysql/mysql_interactive_worker.rs:395:76
  54: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  55: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  56: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  58: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  59: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  60: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  61: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  62: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  63: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  64: tokio::runtime::task::core::Core<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  65: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  66: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  67: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  68: __rust_try
  69: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  70: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  71: tokio::runtime::task::harness::poll_future
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  72: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  73: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  74: tokio::runtime::task::raw::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  75: tokio::runtime::task::raw::RawTask::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  76: tokio::runtime::task::LocalNotified<S>::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  77: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  78: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  79: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  80: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  81: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  82: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  83: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  84: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  85: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  86: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  87: tokio::runtime::task::core::Core<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  88: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  89: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  90: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  91: __rust_try
  92: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  93: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  94: tokio::runtime::task::harness::poll_future
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  95: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  96: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  97: tokio::runtime::task::raw::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  98: tokio::runtime::task::raw::RawTask::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  99: tokio::runtime::task::UnownedTask<S>::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
 100: tokio::runtime::blocking::pool::Task::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
 101: tokio::runtime::blocking::pool::Inner::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
 102: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
 103: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
 104: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
 105: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
 106: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
 107: __rust_try
 108: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
 109: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
 110: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
 111: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
 112: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
 113: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
 114: <unknown>
 115: <unknown>




```

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

update_list in update statement can't contain subquery|window|aggregate functions

- Closes #13241

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13259)

### CODE REVIEW

File: src/query/sql/src/planner/binder/update.rs [hunk 1]
```diff
@@ -102,11 +103,23 @@ impl Binder {
...
+                    ScalarExpr::WindowFunction(_)
+                        | ScalarExpr::AggregateFunction(_)
+                        | ScalarExpr::SubqueryExpr(_)
+                )
+            };
+            let finder = Finder::new(&f);
+            let finder = scalar.accept(finder)?;
+            if !finder.scalars().is_empty() {
+                return Err(ErrorCode::SemanticError(
+                    "update_list in update statement can't contain subquery|window|aggregate functions".to_string(),
```
Comment (xudong963) [inline src/query/sql/src/planner/binder/update.rs:118]: Why can't update_list contain them, is it temporarily unsupported or semantically unsupportable?

Comment (zhyass) [reply src/query/sql/src/planner/binder/update.rs:118]: > temporarily unsupported

subquery is temporarily unsupported. Aggr and window is semantically unsupported

**Review by xudong963 — APPROVED** [review]
