### PR TITLE
order by sub stmt support db.table.col

### LINKED ISSUE #6192: Feature: Orderby support use `database_name`.`table_name`.`column_name`
**Summary**

There has a grammar

```
SELECT `default`.`t`.`id` AS `id`, count(distinct `default`.`t`.`id`) AS `count` FROM `default`.`t` WHERE `default`.`t`.`id` = ? GROUP BY `default`.`t`.`id` ORDER BY `default`.`t`.`id` ASC
```

And in ORDER BY | GROUP BY

the sql is `database_name`.`table_name`.`column_name`

Now the error info is :

```SQL
SELECT `t`.`id` AS `id`, count(distinct `t`.`id`) AS `count` FROM `default`.`t` WHERE `default`.`t`.`id` = 100 GROUP BY `default`.`t`.`id` ORDER BY `default`.`t`.`id` ASC;
ERROR 1105 (HY000): Code: 1065, displayText = error: 
  --> SQL:1:149
  |
1 | SELECT `t`.`id` AS `id`, count(distinct `t`.`id`) AS `count` FROM `default`.`t` WHERE `default`.`t`.`id` = 100 GROUP BY `default`.`t`.`id` ORDER BY `default`.`t`.`id` ASC
  |                                                                                                                                                     ^^^^^^^^^^^^^^^^^^ can only order by column


```

GROUP BY is ok.

```
'root'@mysqldb 11:00:00 [(none)]> SELECT `t`.`id` AS `id`, count(distinct `t`.`id`) AS `count` FROM `default`.`t` WHERE `default`.`t`.`id` = 1 GROUP BY `default`.`t`.`id` ;
+------+-------+
| id   | count |
+------+-------+
|    1 |     1 |
+------+-------+
1 row in set (0.11 sec)
Read 1 rows, 4.00 B in 0.031 sec., 31.76 rows/sec., 127.05 B/sec.

```

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

order by sub stmt support db.table.col.

In this pr just support db.table.col not do any judge for db_name and table_name.

because the struct `ColumnBinding` does not have database_name.

```rust
#[derive(Clone, PartialEq, Debug)]
pub struct ColumnBinding {
    /// Table name of this `ColumnBinding` in current context
    pub table_name: Option<String>,
    /// Column name of this `ColumnBinding` in current context
    pub column_name: String,
    /// Column index of ColumnBinding
    pub index: IndexType,

    pub data_type: DataTypeImpl,

    /// Consider the sql: `select * from t join t1 using(a)`.
    /// The result should only contain one `a` column.
    /// So we need make `t.a` or `t1.a` invisible in unqualified wildcard.
    pub visible_in_unqualified_wildcard: bool,
}
```

And actually I'm not sure this issue can be fixed as this pr.

In my mind it's better fixed with ISSUE https://github.com/datafuselabs/databend/issues/6080

## Changelog

- New Feature

## Related Issues

Fixes #6192

### CODE REVIEW

File: tests/suites/0_stateless/03_dml/03_0004_select_order_by_db_table_col_v2.sql [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+SELECT id FROM a.t ORDER BY a.t.id2 ASC;
+
+SELECT DISTINCT(id) FROM a.t ORDER BY a.t.id;
+SELECT DISTINCT(id) FROM a.t ORDER BY a.t.id2; -- {ErrorCode 1065}
+-- this will err but if has a alias will not err.
+-- SELECT SUM(id) FROM a.t ORDER BY a.t.id2;
+-- ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named ""id2"_1". Valid fields: ["\"SUM(id)\"_4"].
+SELECT SUM(id) as id2 FROM a.t ORDER BY a.t.id2;
+-- expect err
+SELECT DISTINCT(id) as id2 FROM a.t ORDER BY a.t.id2;
```
Comment (TCeason) [inline tests/suites/0_stateless/03_dml/03_0004_select_order_by_db_table_col_v2.sql:19]: Here, we need an error, but now it will succeed. I will create a new ISSUE.

```
'root'@mysqldb 17:57:14 [(none)]> SELECT DISTINCT(id) FROM a.t ORDER BY a.t.id2;
ERROR 1105 (HY000): Code: 1065, displayText = error: 
  --> SQL:1:39
  |
1 | SELECT DISTINCT(id) FROM a.t ORDER BY a.t.id2
  |                                       ^^^^^^^ for SELECT DISTINCT, ORDER BY expressions must appear in select list

```

File: query/src/sql/planner/binder/sort.rs [hunk 2]
```diff
@@ -57,23 +56,25 @@ impl<'a> Binder {
...
-                table: None,
+                table: ref table_name,
                 column: ref ident,
                 ..
             } = order.expr
             {
+                let mut table = None;
+                if let Some(table_name) = table_name {
+                    table = Some(table_name.name.clone());
+                }
```
Comment (leiysky) [inline query/src/sql/planner/binder/sort.rs:71]:
```suggestion
                let table = table_name.map(|v| v.name.clone());
```

Comment (TCeason) [reply query/src/sql/planner/binder/sort.rs]: Cooool

**Comment by BohuTANG** [comment]
#6219 merged

File: scripts/ci/ci-run-stateless-tests-cluster.sh [hunk 3]
```diff
@@ -9,4 +9,5 @@ SCRIPT_PATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
 cd "$SCRIPT_PATH/../../tests" || exit
 
 echo "Starting databend-test"
-./databend-test '^0[^4]_' --mode 'cluster' --run-dir 0_stateless --skip '02_0057_function_nullif' '02_0058_function_ifnull'
+# Now Planner v2 not support cluster execute. So skip some tests that need enable planner v2.
+./databend-test '^0[^4]_' --mode 'cluster' --run-dir 0_stateless --skip '02_0057_function_nullif' '02_0058_function_ifnull' '03_0004_select_order_by_db_table_col_v2'
```
Comment (TCeason) [inline scripts/ci/ci-run-stateless-tests-cluster.sh:13]: Note: the test in this pr need to enable planner v2 but now we do not support cluster execute, so skip it.

**Comment by TCeason** [comment]
```
09_0008_fuse_optimize_table:                                            [ FAIL ] - result differs with:
--- /workspace/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.result	2022-06-27 04:37:36.977439331 +0000
+++ /workspace/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.stdout	2022-06-27 04:41:30.575939379 +0000
@@ -23,9 +23,3 @@
 9
 10
 1
-5
-6
-7
-8
-9
-10
```

Maybe that's a flaky test?

**Review by leiysky — APPROVED** [review]
