### PR TITLE
fix(query): fix and filter panic

### LINKED ISSUE #12699: bug: filter `and expr` with int type and boolean type panic
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.99-nightly

### What's Wrong?

filter `and expr` with int type and boolean type panic

```
panicked at 'called `Result::unwrap()` on an `Err` value: SemanticError. Code: 1065, Text = no overload satisfies `and_filters(Int32, Boolean)`

has tried possible overloads:
  and_filters(Boolean NULL, Boolean NULL) :: Boolean  : unable to unify `Int32` with `Boolean`.

   0: common_exception::exception_backtrace::capture
             at src/common/exception/src/exception_backtrace.rs:72:17
   1: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::SemanticError
             at src/common/exception/src/exception_code.rs:35:30
   2: common_expression::type_check::check_function
             at src/query/expression/src/type_check.rs:334:9
   3: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::push_downs::{{closure}}::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:1904:29
   4: core::iter::traits::iterator::Iterator::fold
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:2481:21
   5: core::iter::traits::iterator::Iterator::reduce
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:2518:14
   6: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::push_downs::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:1901:32
   7: core::option::Option<T>::map
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/option.rs:1075:29
   8: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::push_downs
             at src/query/sql/src/executor/physical_plan_builder.rs:1887:32
   9: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build_scan::{{closure}}::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:1752:13
  10: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  11: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  12: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  13: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  14: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  15: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  16: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  17: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build_scan::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:1631:5
  18: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:149:83
  19: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  20: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  21: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  22: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  23: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  24: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  25: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  26: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:143:5
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  28: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:266:73
  29: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  30: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  31: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  32: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  33: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  34: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  35: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  36: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:143:5
  37: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  38: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:252:72
  39: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  40: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  41: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  42: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  43: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  44: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  45: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  46: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}
             at src/query/sql/src/executor/physical_plan_builder.rs:143:5
  47: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  48: databend_query::interpreters::interpreter_select::SelectInterpreter::build_physical_plan::{{closure}}::{{closure}}
             at src/query/service/src/interpreters/interpreter_select.rs:93:14
  49: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  50: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  51: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  52: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  53: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  54: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  55: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  56: databend_query::interpreters::interpreter_select::SelectInterpreter::build_physical_plan::{{closure}}
             at src/query/service/src/interpreters/interpreter_select.rs:87:5
  57: <databend_query::interpreters::interpreter_select::SelectInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at src/query/service/src/interpreters/interpreter_select.rs:233:56
  58: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  59: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  60: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at src/query/service/src/interpreters/interpreter.rs:55:51
  61: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  62: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  63: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  64: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  65: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  66: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  67: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  68: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at src/query/service/src/interpreters/interpreter.rs:45:5
  69: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  70: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase::exec_query::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at src/query/service/src/servers/mysql/mysql_interactive_worker.rs:399:76
  71: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  72: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  73: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  74: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  75: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  76: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  77: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  78: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  79: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  80: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  81: tokio::runtime::task::core::Core<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  82: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  83: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  84: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  85: __rust_try
  86: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  87: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  88: tokio::runtime::task::harness::poll_future
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  89: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  90: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  91: tokio::runtime::task::raw::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  92: tokio::runtime::task::raw::RawTask::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  93: tokio::runtime::task::LocalNotified<S>::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  94: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  95: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  96: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  97: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  98: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  99: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
 100: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
 101: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
 102: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
 103: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
 104: tokio::runtime::task::core::Core<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
 105: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
 106: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
 107: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
 108: __rust_try
 109: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
 110: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
 111: tokio::runtime::task::harness::poll_future
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
 112: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
 113: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
 114: tokio::runtime::task::raw::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
 115: tokio::runtime::task::raw::RawTask::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
 116: tokio::runtime::task::UnownedTask<S>::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
 117: tokio::runtime::blocking::pool::Task::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
 118: tokio::runtime::blocking::pool::Inner::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
 119: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
 120: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
 121: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
 122: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
 123: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
 124: __rust_try
 125: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
 126: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
 127: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
 128: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
      call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
      thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
 129: <unknown>
 130: <unknown>
', src/query/sql/src/executor/physical_plan_builder.rs:1911:30
   0: common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:597:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: unwrap_failed
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/result.rs:1651:5
   9: core::result::Result<T,E>::unwrap
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/result.rs:1076:23
  10: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::push_downs::{{closure}}::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:1904:29
  11: core::iter::traits::iterator::Iterator::fold
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:2481:21
  12: core::iter::traits::iterator::Iterator::reduce
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:2518:14
  13: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::push_downs::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:1901:32
  14: core::option::Option<T>::map
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/option.rs:1075:29
  15: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::push_downs
             at ./src/query/sql/src/executor/physical_plan_builder.rs:1887:32
  16: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build_scan::{{closure}}::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:1752:13
  17: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  18: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  20: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  21: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  22: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  23: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  24: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build_scan::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:1631:5
  25: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:149:83
  26: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  27: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  30: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  31: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  32: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  33: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:143:5
  34: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  35: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:266:73
  36: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  37: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  40: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  41: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  42: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  43: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:143:5
  44: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  45: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:252:72
  46: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  47: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  49: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  50: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  51: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  52: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  53: common_sql::executor::physical_plan_builder::PhysicalPlanBuilder::build::{{closure}}
             at ./src/query/sql/src/executor/physical_plan_builder.rs:143:5
  54: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  55: databend_query::interpreters::interpreter_select::SelectInterpreter::build_physical_plan::{{closure}}::{{closure}}
             at ./src/query/service/src/interpreters/interpreter_select.rs:93:14
  56: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  57: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  58: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  59: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  60: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  61: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  62: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  63: databend_query::interpreters::interpreter_select::SelectInterpreter::build_physical_plan::{{closure}}
             at ./src/query/service/src/interpreters/interpreter_select.rs:87:5
  64: <databend_query::interpreters::interpreter_select::SelectInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at ./src/query/service/src/interpreters/interpreter_select.rs:233:56
  65: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  66: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  67: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at ./src/query/service/src/interpreters/interpreter.rs:55:51
  68: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  69: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  70: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  71: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  72: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  73: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  74: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  75: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at ./src/query/service/src/interpreters/interpreter.rs:45:5
  76: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  77: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase::exec_query::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/query/service/src/servers/mysql/mysql_interactive_worker.rs:399:76
  78: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  79: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  80: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  81: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  82: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  83: async_backtrace::frame::active_frame::with
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  84: async_backtrace::frame::Frame::in_scope
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  85: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  86: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  87: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  88: tokio::runtime::task::core::Core<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  89: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  90: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  91: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  92: __rust_try
  93: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  94: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  95: tokio::runtime::task::harness::poll_future
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  96: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  97: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  98: tokio::runtime::task::raw::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  99: tokio::runtime::task::raw::RawTask::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
 100: tokio::runtime::task::LocalNotified<S>::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
 101: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
 102: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
 103: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
 104: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
 105: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
 106: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
 107: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
 108: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
 109: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
 110: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
 111: tokio::runtime::task::core::Core<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
 112: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
 113: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
 114: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
 115: __rust_try
 116: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
 117: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
 118: tokio::runtime::task::harness::poll_future
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
 119: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
 120: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
 121: tokio::runtime::task::raw::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
 122: tokio::runtime::task::raw::RawTask::poll
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
 123: tokio::runtime::task::UnownedTask<S>::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
 124: tokio::runtime::blocking::pool::Task::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
 125: tokio::runtime::blocking::pool::Inner::run
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
 126: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/b41sh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
 127: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
 128: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
 129: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
 130: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
 131: __rust_try
 132: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
 133: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
 134: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
 135: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
 136: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
 137: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
 138: <unknown>
 139: <unknown>
```

### How to Reproduce?

```
mysql> create table test(a int, b bool);
Query OK, 0 rows affected (0.10 sec)

mysql> select * from test where a and b;
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 4559 panicked.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Fix and filter panic
- `and_filters` function supports auto-cast rulers.
- `and_filters` function supports Boolean data type, avoiding unnecessary casts to Boolean Nullable

Closes #12699

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12770)

### CODE REVIEW

**Comment by sundy-li** [comment]
```
pub fn register(registry: &mut FunctionRegistry) {
    registry.register_default_cast_rules(GENERAL_CAST_RULES.iter().cloned());
    registry.register_default_cast_rules(CAST_FROM_STRING_RULES.iter().cloned());
    registry.register_default_cast_rules(CAST_FROM_VARIANT_RULES());
    registry.register_auto_try_cast_rules(CAST_FROM_VARIANT_RULES());

    for func_name in ["and", "or", "not", "xor"] {
        for data_type in ALL_INTEGER_TYPES {
```


here we need to add `and_filters`

**Review by sundy-li — APPROVED** [review]

File: src/query/functions/src/scalars/boolean.rs [hunk 1]
```diff
@@ -49,11 +49,16 @@ pub fn register(registry: &mut FunctionRegistry) {
         if args_type.len() < 2 {
             return None;
         }
+        for arg_type in args_type {
```
Comment (ariesdevil) [inline src/query/functions/src/scalars/boolean.rs:52]: More functional:
```rust
if args_type.iter().any(|arg_type| arg_type.remove_nullable() != DataType::Boolean) {
    return None;
}
```

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/actions/runs/6154484525/job/16700375350?pr=12770#step:4:312

```
-                   ├── push downs: [filters: [and_filters(and_filters(and_filters(and_filters(t_11831.time (#3) >= 1686672000000, t_11831.time (#3) <= 1686758399000), t1.uid (#0) = 11), t_11831.time (#3) >= 1686672000000), t_11831.time (#3) <= 1686758399000)], limit: NONE]       |
+                   ├── push downs: [filters: [and_filters(and_filters(and_filters(and_filters(t_11831.time (#3) >= 1686672000000, t_11831.time (#3) <= 1686758399000), t1.uid (#0) = 11), t_11831.time (#3) >= 1686672000000), t_11831.time (#3) <= 1686758399000)], limit: NONE]
```

**Review by ariesdevil — APPROVED** [review]
