### PR TITLE
ISSUE-4860: fix empty query

### LINKED ISSUE #4860: Empty query: /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
**Summary**

This is ok:
```
mysql> /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */ select 1;
+------+
| 1    |
+------+
|    1 |
+------+
1 row in set (0.06 sec)
Read 1 rows, 1 B in 0.007 sec., 140.82 rows/sec., 140.82 B/sec.
```

Error:
```
mysql> /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
ERROR 1105 (HY000): Code: 1005, displayText = Empty query.
```

Server error log:
```
2022-04-14T10:20:06.409763Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */
2022-04-14T10:20:06.414387Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1005, displayText = Empty query.

   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::SyntaxException
             at common/exception/src/exception_code.rs:36:66
   1: databend_query::sql::plan_parser::PlanParser::build_plan::{{closure}}
             at query/src/sql/plan_parser.rs:57:24
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   3: databend_query::sql::plan_parser::PlanParser::parse_with_hint::{{closure}}
             at query/src/sql/plan_parser.rs:48:80
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   5: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}::{{closure}}
             at query/src/servers/mysql/mysql_interactive_worker.rs:276:88
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   7: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}
             at query/src/servers/mysql/mysql_interactive_worker.rs:262:5
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   9: <databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorker<W> as opensrv_mysql::AsyncMysqlShim<W>>::on_query::{{closure}}
             at query/src/servers/mysql/mysql_interactive_worker.rs:177:47
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/future.rs:124:9
  12: opensrv_mysql::AsyncMysqlIntermediary<B,S>::run::{{closure}}
             at /home/bohu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:513:30
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  14: opensrv_mysql::AsyncMysqlIntermediary<B,S>::run_with_options::{{closure}}
             at /home/bohu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:250:17
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

```

### PR DESCRIPTION
**Pull request by cadl**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add interpreter_empty to fix the empty query. 

## Changelog

- Bug Fix

## Related Issues

Fixes #4860

### CODE REVIEW

File: query/tests/it/servers/http/clickhouse_handler.rs [hunk 1]
```diff
@@ -69,6 +63,12 @@ async fn test_select() -> PoemResult<()> {
         assert_error!(body, "sql parser error");
     }
 
+    {
+        let (status, body) = server.get("").await;
```
Comment (BohuTANG) [inline query/tests/it/servers/http/clickhouse_handler.rs:67]: 👍

**Review by BohuTANG — APPROVED** [review]
👍
