### PR TITLE
fix(cluster): remove invalid cluster node in current query

### LINKED ISSUE #6532: bug: cluster accesing the old instances from the previous deployment, and get `no route to host` error
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.120-nightly

### What's Wrong?

```
2022/07/07 11:21:41 webapi.doRequest POST url=https://test.datafusecloud.com/v1/query req={"sql":"SELECT count(*) FROM hits;"} resp={"id":"fbca99d5-ebd9-4273-b8d0-1d8f063d27c8","session_id":"7ad21381-117d-48c5-ad7d-963f91a447d6","schema":{"fields":[],"metadata":{}},"data":[],"state":"Running","error":null,"stats":{"scan_progress":{"rows":0,"bytes":0},"write_progress":{"rows":0,"bytes":0},"result_progress":{"rows":0,"bytes":0},"running_time_ms":1012.8526280000001},"stats_uri":"/v1/query/fbca99d5-ebd9-4273-b8d0-1d8f063d27c8","final_uri":"/v1/query/fbca99d5-ebd9-4273-b8d0-1d8f063d27c8/final","next_uri":"/v1/query/fbca99d5-ebd9-4273-b8d0-1d8f063d27c8/page/0","kill_uri":"/v1/query/fbca99d5-ebd9-4273-b8d0-1d8f063d27c8/kill"}
2022/07/07 11:21:50 the 0 time result has error query has error: &{Code:1038 Message:can not connect to http://10.1.81.119:9191/, error: tonic::transport::error::Error: transport error source: error trying to connect: tcp connect error: No route to host (os error 113) source: tcp connect error: No route to host (os error 113) source: No route to host (os error 113) Kind:}, stats: <nil>
```

https://github.com/datafuselabs/databend-perf/runs/7232265390?check_suite_focus=true

### How to Reproduce?

1. start a databend-query cluster deployment in k8s
2. rolling a new deployment for the same cluster id (k8s would start new pods, and remove old pods)
3. send queries to the new cluster, and will get this error

select * from system.clusters shows that on this error happens, cluster still have the old pod IP inside (in the normal case, it should contains 8 instances, but it contains 15 instances, with 7 old ip addresses from the earlier deployment):

Screen Shot 2022-07-07 at 7 26 43 PM

after a few seconds, `system.clusters` became 8:

Screen Shot 2022-07-07 at 7 30 46 PM

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(cluster): remove invalid cluster node in current query

Fixes #6532

### CODE REVIEW

**Review by flaneur2020 — APPROVED** [review]
appreciate quq

File: src/query/service/src/clusters/cluster.rs [hunk 1]
```diff
@@ -224,7 +227,18 @@ impl ClusterDiscovery {
...
+                                "Cannot connect node [{:?}], remove it in query. cause: {:?}",
+                                node.flight_address, cause
+                            );
+
+                            continue;
+                        }
+                    }
+
+                    res.push(Arc::new(node.clone()));
                 }
```
Comment (flaneur2020) [inline src/query/service/src/clusters/cluster.rs:242]: return an error if res.len() == 0 ?

**Review by BohuTANG — APPROVED** [review]

File: src/query/service/src/clusters/cluster.rs (hunk 1 above)
Comment (BohuTANG) [reply src/query/service/src/clusters/cluster.rs:242]: > return an error if res.len() == 0 ?

If `res.len()`, there is only one node is himself.
