### PR TITLE
bugfix(planner): Fix grouping check

### LINKED ISSUE #6209: select projection will destroy order by logical
Here, we need an error, but now it will succeed. I will create a new ISSUE.

```sql
-- SELECT DISTINCT(id) as id2 FROM a.t ORDER BY a.t.id2; --Succed.
'root'@mysqldb 17:57:14 [(none)]> SELECT DISTINCT(id) FROM a.t ORDER BY a.t.id2;
ERROR 1105 (HY000): Code: 1065, displayText = error: 
  --> SQL:1:39
  |
1 | SELECT DISTINCT(id) FROM a.t ORDER BY a.t.id2
  |                                       ^^^^^^^ for SELECT DISTINCT, ORDER BY expressions must appear in select list

```

_Originally posted by @TCeason in https://github.com/datafuselabs/databend/pull/6196#discussion_r905914520_

### PR DESCRIPTION
**Pull request by leiysky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Changelog

- Bug Fix

## Related Issues

Close #6209

### CODE REVIEW

**Review by andylokandy — APPROVED** [review]

File: query/src/sql/planner/binder/sort.rs [hunk 1]
```diff
@@ -148,14 +148,28 @@ impl<'a> Binder {
         let mut order_by_items = Vec::with_capacity(order_by.items.len());
         let mut scalars = vec![];
         for order in order_by.items {
+            if from_context.in_grouping {
```
Comment (TCeason) [inline query/src/sql/planner/binder/sort.rs:151]: Maybe we need do some modify to fix this case 

```sql
select distinct(id) as id1 from t order by id1;
```

Because the in_grouping default value if false , only when the sql has aggregate it will be set true.

**Comment by BohuTANG** [comment]
test_sqllogic_standalone_linux
```
2022-06-26T07:57:28.425577Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: select count(number) from numbers(10) group by number+1 having number = 1;
2022-06-26T07:57:28.431370Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1065, displayText = error: 
  --> SQL:1:71
  |
1 | select count(number) from numbers(10) group by number+1 having number = 1;
  |                                                                       ^ column "number" must appear in the GROUP BY clause or be used in an aggregate function

```

**Review by TCeason — APPROVED** [review]

File: query/src/sql/planner/binder/sort.rs (hunk 1 above)
Comment (TCeason) [reply query/src/sql/planner/binder/sort.rs:153]: I think this should create a new issue? what do you think about it?@[leiysky](https://github.com/leiysky)

Comment (leiysky) [reply query/src/sql/planner/binder/sort.rs:153]: @TCeason I think so. 

I have no idea about this case yet, since we haven't support `DISTINCT ON` yet, this query should be the same as `select distinct id as id1 from t order by id1`.

Comment (TCeason) [reply query/src/sql/planner/binder/sort.rs:153]: Np  :) I think that’s not a regular usage. We just need record it now.
