### PR TITLE
fix: fix update using using constant in predicate from subquery panic

### LINKED ISSUE #14283: bug: after update data, select panic
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.2.279

### What's Wrong?

after update data, select panic

### How to Reproduce?

```SQL
mysql> create table t(a int);
Query OK, 0 rows affected (3.45 sec)

mysql> insert into t values(1),(2);
Query OK, 2 rows affected (2.58 sec)

mysql> select * from t;
+------+
| a    |
+------+
|    1 |
|    2 |
+------+
2 rows in set (3.25 sec)
Read 2 rows, 9.00 B in 0.794 sec., 2.52 rows/sec., 11.33 B/sec.
mysql> update t set a = 100 where 3 > any(select a from t);
Query OK, 2 rows affected (10.52 sec)

mysql> select * from t;
ERROR 1105 (HY000): PanicError. Code: 1104, Text = assertion `left == right` failed
  left: 1
 right: 0.
```

stack:
```
panicked at src/common/arrow/src/arrow/io/parquet/read/deserialize/primitive/basic.rs:71:9:
assertion `left == right` failed
  left: 1
 right: 0
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/backtrace.rs:331:13
   3: databend_common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   4: databend_common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/boxed.rs:2021:9
   6: std::panicking::rust_panic_with_hook
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:735:13
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:609:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys_common/backtrace.rs:170:18
   9: rust_begin_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:597:5
  10: core::panicking::panic_fmt
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panicking.rs:72:14
  11: core::panicking::assert_failed_inner
  12: core::panicking::assert_failed
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panicking.rs:279:5
  13: databend_common_arrow::arrow::io::parquet::read::deserialize::primitive::basic::Values::try_new
             at ./src/common/arrow/src/arrow/io/parquet/read/deserialize/primitive/basic.rs:71:9
  14: <databend_common_arrow::arrow::io::parquet::read::deserialize::primitive::basic::PrimitiveDecoder<T,P,F> as databend_common_arrow::arrow::io::parquet::read::deserialize::utils::Decoder>::build_state
             at ./src/common/arrow/src/arrow/io/parquet/read/deserialize/primitive/basic.rs:195:30
  15: <databend_common_arrow::arrow::io::parquet::read::deserialize::primitive::integer::IntDecoder<T,P,F> as databend_common_arrow::arrow::io::parquet::read::deserialize::utils::Decoder>::build_state
             at ./src/common/arrow/src/arrow/io/parquet/read/deserialize/primitive/integer.rs:139:18
  16: databend_common_arrow::arrow::io::parquet::read::deserialize::utils::next
             at ./src/common/arrow/src/arrow/io/parquet/read/deserialize/utils.rs:503:30
  17: <databend_common_arrow::arrow::io::parquet::read::deserialize::primitive::integer::IntegerIter<T,I,P,F> as core::iter::traits::iterator::Iterator>::next
             at ./src/common/arrow/src/arrow/io/parquet/read/deserialize/primitive/integer.rs:264:27
  18: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/map.rs:103:9
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/map.rs:103:9
  20: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/boxed.rs:1941:9
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/map.rs:103:9
  22: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/boxed.rs:1941:9
  23: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/map.rs:103:9
  24: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/boxed.rs:1941:9
  25: databend_common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl databend_common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_field
             at ./src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs:313:25
  26: databend_common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl databend_common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_parquet_chunks_with_buffer
             at ./src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs:114:39
  27: <databend_common_storages_fuse::operations::read::parquet_data_source_deserializer::DeserializeDataTransform as databend_common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs:257:42
  28: <alloc::boxed::Box<T> as databend_common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/pipeline/core/src/processors/processor.rs:239:9
  29: databend_common_pipeline_core::processors::processor::ProcessorPtr::process
             at ./src/query/pipeline/core/src/processors/processor.rs:178:9
  30: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:98:17
  31: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:78:46
  32: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:415:21
  33: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:364:34
  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panic/unwind_safe.rs:271:9
  35: std::panicking::try::do_call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:504:40
  36: ___rust_try
  37: std::panicking::try
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:468:19
  38: std::panic::catch_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panic.rs:142:14
  39: databend_common_base::runtime::catch_unwind::catch_unwind
             at ./src/common/base/src/runtime/catch_unwind.rs:27:11
  40: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:361:34
  41: databend_common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at ./src/common/base/src/runtime/thread.rs:85:21
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys_common/backtrace.rs:154:18
  43: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/thread/mod.rs:529:17
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panic/unwind_safe.rs:271:9
  45: std::panicking::try::do_call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:504:40
  46: ___rust_try
  47: std::panicking::try
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panicking.rs:468:19
  48: std::panic::catch_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/panic.rs:142:14
  49: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/thread/mod.rs:528:30
  50: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/ops/function.rs:250:5
  51: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/boxed.rs:2007:9
  52: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/boxed.rs:2007:9
  53: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys/unix/thread.rs:108:17
  54: __pthread_deallocate
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by lichuang**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

fix: update table using constant in subquery predicate, query will panic.

Fixes #14283 

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14367)

### CODE REVIEW

File: src/query/storages/fuse/src/operations/update.rs [hunk 1]
```diff
@@ -93,15 +93,23 @@ impl FuseTable {
...
             all_column_indices.iter().for_each(|&index| {
                 offset_map.insert(index, pos);
                 pos += 1;
             });
 
-            (
-                Projection::Columns(all_column_indices),
-                Arc::new(schema.remove_virtual_computed_fields()),
-            )
+            // add `_predicate` column into input schema
```
Comment (zhyass) [inline src/query/storages/fuse/src/operations/update.rs:103]: if query_row_id_col {
                fields.push(TableField::new(
                PREDICATE_COLUMN_NAME,
                TableDataType::Boolean,
            ));
            pos += 1;
           ... ...
}

**Review by zhyass — APPROVED** [review]
