### PR TITLE
fix: compact limit get no affect rows

### LINKED ISSUE #13216: bug: compact get unlimited block size
```
mysql> create table t(a int) row_per_block=10;
Query OK, 0 rows affected (0.17 sec)

mysql> insert into t select number from numbers(7);
Query OK, 7 rows affected (0.14 sec)

mysql> insert into t select number from numbers(7);
Query OK, 7 rows affected (0.12 sec)

mysql> insert into t select number from numbers(7);
Query OK, 7 rows affected (0.14 sec)

mysql> optimize table t compact;
Query OK, 21 rows affected (0.14 sec)

mysql> insert into t select number from numbers(7);
Query OK, 7 rows affected (0.14 sec)

mysql> optimize table t compact;
Query OK, 28 rows affected (0.08 sec)

mysql> select block_count,row_count from fuse_segment('default','t');
+-------------+-----------+
| block_count | row_count |
+-------------+-----------+
|           1 |        28 |
+-------------+-----------+
1 row in set (0.07 sec)
Read 1 rows, 104.00 B in 0.046 sec., 21.83 rows/sec., 2.22 KiB/sec.
```

### LINKED ISSUE #13217: bug: compact limit cannot work
```
mysql> create table t13(a int) row_per_block=10 block_per_segment=2;
Query OK, 0 rows affected (0.12 sec)

mysql> insert into t13 select number from numbers(7);
Query OK, 7 rows affected (0.19 sec)

mysql> insert into t13 select number from numbers(7);
Query OK, 7 rows affected (0.09 sec)

mysql> insert into t13 select number from numbers(7);
Query OK, 7 rows affected (0.12 sec)

mysql> insert into t13 select number from numbers(7);
Query OK, 7 rows affected (0.13 sec)

mysql> optimize table t13 compact limit 2;
Query OK, 14 rows affected (0.16 sec)

mysql> select block_count,row_count from fuse_segment('default','t13');
+-------------+-----------+
| block_count | row_count |
+-------------+-----------+
|           1 |        14 |
|           1 |         7 |
|           1 |         7 |
+-------------+-----------+
3 rows in set (0.10 sec)
Read 3 rows, 302.00 B in 0.068 sec., 44.18 rows/sec., 4.34 KiB/sec.

mysql> insert into t13 select number from numbers(7);
Query OK, 7 rows affected (0.14 sec)

mysql> optimize table t13 compact limit 2;
Query OK, 0 rows affected (0.15 sec)

mysql> select block_count,row_count from fuse_segment('default','t13');
+-------------+-----------+
| block_count | row_count |
+-------------+-----------+
|           2 |        21 |
|           1 |         7 |
|           1 |         7 |
+-------------+-----------+
3 rows in set (0.10 sec)
Read 3 rows, 302.00 B in 0.068 sec., 44.18 rows/sec., 4.34 KiB/sec.

mysql> optimize table t13 compact limit 2 ;
Query OK, 0 rows affected (0.12 sec)

mysql> select block_count,row_count from fuse_segment('default','t13');
+-------------+-----------+
| block_count | row_count |
+-------------+-----------+
|           2 |        21 |
|           1 |         7 |
|           1 |         7 |
+-------------+-----------+
3 rows in set (0.09 sec)
Read 3 rows, 302.00 B in 0.070 sec., 42.96 rows/sec., 4.22 KiB/sec.
```

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Limit block size to no more than 2 * N.
Mark the blocks as perfect, if there are more than one blocks after compact.

- Closes #13216 
- Closes #13217

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13210)

### CODE REVIEW

File: src/query/storages/fuse/src/operations/common/processors/transform_mutation_aggregator.rs [hunk 1]
```diff
@@ -341,6 +343,9 @@ impl TableMutationAggregator {
                 } else {
                     // use by compact.
                     assert!(segment_mutation.deleted_blocks.is_empty());
+                    // There are more than 1 blocks, mains that the blocks can no longer be compacted.
```
Comment (SkyFan2002) [inline src/query/storages/fuse/src/operations/common/processors/transform_mutation_aggregator.rs:346]:
```suggestion
                    // There are more than 1 blocks, means that the blocks can no longer be compacted.
```

**Review by dantengsky — APPROVED** [review]

**Review by SkyFan2002 — APPROVED** [review]
