### PR TITLE
fix: fix disallow scalar function with window

### LINKED ISSUE #12914: Should scalar function parse window func's over can success?
**Summary**

Now:

```sql
select to_date('2022-02-02') over(order by (to_date('2017-12-04') - to_date('2017-02-02')));
+---------------------------------------------------------------------------------------+
| to_date('2022-02-02') over (order by (to_date('2017-12-04') - to_date('2017-02-02'))) |
+---------------------------------------------------------------------------------------+
| 2022-02-02                                                                            |
+---------------------------------------------------------------------------------------+
1 row in set (0.012 sec)
```

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

disallow scalar function with window

- Closes #12914

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12925)

### CODE REVIEW

File: src/query/sql/src/planner/semantic/type_check.rs [hunk 1]
```diff
@@ -650,7 +650,7 @@ impl<'a> TypeChecker<'a> {
                 params,
                 window,
                 lambda,
-            } => {
+            } if window.is_none() => {
```
Comment (b41sh) [inline src/query/sql/src/planner/semantic/type_check.rs:653]: It is better to determine the type of the function by its name, and then determine whether the `window` should be `None` or `Some`. Separately handle will result in the window function not being able to find similar function names if the function name is not correct. We have code logic for finding similar function names between lines 662 and 695.
https://github.com/datafuselabs/databend/pull/12925/files#diff-8e24042e5eec79cd29dda9776333d9ecad8cba883a80e4590c31f594ea745795R662-R695

**Review by RinChanNOWWW — APPROVED** [review]
