### PR TITLE
COMMON-3801: Refine the error code

### LINKED ISSUE #3801: Refine the Exception Code to category
## Summary

From the https://github.com/datafuselabs/databend/blob/main/common/exception/src/exception.rs

The ErrCode number range is no category, a bit mess for the user, need to improve.

Reference from MySQL:
https://dev.mysql.com/doc/mysql-errors/8.0/en/error-reference-introduction.html

1. Server Error Message, [1002, ... ]
2. Client Error Message , which range [2000, ...]
3. Global Error Message [1, 100]

### PR DESCRIPTION
**Pull request by BohuTANG**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Refine the error code:
1. Split exception.rs into exception_code.rs(only defined error code)/exception_into.rs(for error try from)
2. Re-range the error code
3. Fix udf&stage `IF NOT EXISTS` error check

## Changelog

- Improvement

## Related Issues

Fixes #3801

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

File: query/tests/it/interpreters/interpreter_stage_create.rs [hunk 1]
```diff
@@ -46,16 +45,17 @@ async fn test_create_stage_interpreter() -> Result<()> {
...
-    } else {
-        panic!()
+        assert_eq!(stage.comments, String::from("test"));
     }
 
-    if let PlanNode::CreateUserStage(plan) = PlanParser::parse(TEST_QUERY, ctx.clone()).await? {
-        let executor = CreatStageInterpreter::try_create(ctx.clone(), plan.clone())?;
+    // IF NOT EXISTS.
+    {
+        // TODO(bohu): this is a bug, IF NOT EXISTS should not return error.
```
Comment (BohuTANG) [inline query/tests/it/interpreters/interpreter_stage_create.rs:53]: I will delete this line in another PR, to reduce the CI re-run.

**Review by zhang2014 — APPROVED** [review]

**Review by PsiACE — APPROVED** [review]
