### PR TITLE
fix(query): fix hashset capacity overflow

### LINKED ISSUE #7483: bug:  Code: 1058, displayText = downcast column error
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.23-nightly-cbaedce-simd(rust-1.64.0-nightly-2022-09-02T16:39:41.032000394Z)

### What's Wrong?

 Code: 1058, displayText = downcast column error

### How to Reproduce?

```sql

DROP DATABASE IF EXISTS databend3;
CREATE DATABASE databend3;
USE databend3;
CREATE TABLE t0(c0BOOLEAN BOOLEAN NULL, c1FLOAT DOUBLE NULL);
CREATE TABLE t16(c0BOOLEAN BOOL NULL DEFAULT(true));
INSERT INTO t0(c1float, c0boolean) VALUES (0.27563244104385376, false), (0.7913353443145752, false);

MySQL [databend3]> select * from t16 right join t0 on false;
ERROR 1105 (HY000): Code: 1058, displayText = downcast column error, column type: "Const(Nullable(Boolean))", expected column: "common_datavalues::columns::nullable::NullableColumn" (while in processor thread 0).

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### LINKED ISSUE #7495: bug: Hash table capacity overflow
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.23-nightly-cbaedce-simd(rust-1.64.0-nightly-2022-09-02T16:39:41.032000394Z)

### What's Wrong?

Code: 1104, displayText = Hash table capacity overflow.

### How to Reproduce?

```sql
DROP DATABASE IF EXISTS databend14;
CREATE DATABASE databend14;
USE databend14;
CREATE TABLE t0(c0VARCHAR VARCHAR NULL, c1VARCHAR VARCHAR NULL DEFAULT(''));
CREATE TABLE t1(c0FLOAT DOUBLE NULL DEFAULT(0.35153302550315857));
INSERT INTO t0(c1varchar, c0varchar) VALUES ('', '7812'), ('4724475', '4');
INSERT INTO t1(c0float) VALUES (0.8140779137611389);
INSERT INTO t1(c0float) VALUES (0.4561707079410553), (0.4561707079410553), (0.7349682450294495);
INSERT INTO t0(c0varchar, c1varchar) VALUES ('', '3569'), ('21', '44965');
INSERT INTO t1(c0float) VALUES (0.45393189787864685);

MySQL [databend14]> select * from t0 inner join t1 ON (true IN ((('88')LIKE('87')), ('' BETWEEN '031' AND '0'), true, (NULL NOT IN (NULL, NULL, NULL)), ('098' BETWEEN '53' AND '941'))) where false;

ERROR 1105 (HY000): Code: 1104, displayText = Hash table capacity overflow.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #7483
Fixes #7495

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

File: src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs [hunk 1]
```diff
@@ -628,6 +629,11 @@ impl JoinHashTable {
     pub(crate) fn set_validity(column: &ColumnRef, validity: &Bitmap) -> Result<ColumnRef> {
         if column.is_null() {
             Ok(column.clone())
+        } else if column.is_const() {
+            let col: &ConstColumn = Series::check_get(column)?;
+            let validity = validity.clone();
+            let inner = Self::set_validity( col.inner(), &validity.slice(0, 1))?;
```
Comment (Xuanwo) [inline src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs:635]:
```suggestion
            let inner = Self::set_validity(col.inner(), &validity.slice(0, 1))?;
```

Seems we need a format.

**Review by PsiACE — APPROVED** [review]
