### PR TITLE
fix(query): fix linux_kernel_version detection

### LINKED ISSUE #8585: bug:  unexpected character '_' after pre-release identifier after using new hash table
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

da64ca3b7480dba5927ad8d5420ae89062f413a5

### What's Wrong?

```
1mcommon_tracing::panic_hook^[[0m^[[31m: ^[[31mpanicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character '_' after pre-release identifier")', /media/ssd1/fangxiaojing/databend/src/common/base/src/mem_allocator/mmap_allocator.rs:266:54, ^[[1;31mbacktrace^[[0m^[[31m: Backtrace [{ fn: "common_tracing::panic_hook::log_panic", file: "/media/ssd1/fangxiaojing/databend/src/common/tracing/src/panic_hook.rs", line: 33 }, 
{ fn: "std::panicking::rust_panic_with_hook", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs", line: 702 },
 { fn: "std::panicking::begin_panic_handler::{{closure}}", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs", line: 588 },
 { fn: "std::sys_common::backtrace::__rust_end_short_backtrace", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs", line: 138 }, 
{ fn: "rust_begin_unwind", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs", line: 584 }, 
{ fn: "core::panicking::panic_fmt", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panicking.rs", line: 142 }, 
{ fn: "core::result::unwrap_failed", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/result.rs", line: 1785 },
 { fn: "common_base::mem_allocator::mmap_allocator::linux::linux_kernel_version", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/result.rs" }, 
{ fn: "common_base::mem_allocator::mmap_allocator::linux::<impl common_base::mem_allocator::mmap_allocator::MmapAllocator<T>>::mmap_grow", file: "/media/ssd1/fangxiaojing/databend/src/common/base/src/mem_allocator/mmap_allocator.rs", line: 90 },
 { fn: "common_base::mem_allocator::mmap_allocator::linux::<impl core::alloc::Allocator for common_base::mem_allocator::mmap_allocator::MmapAllocator<T>>::grow_zeroed", file: "/media/ssd1/fangxiaojing/databend/src/common/base/src/mem_allocator/mmap_allocator.rs", line: 192 },
 { fn: "<common_hashtable::container::HeapContainer<T,A> as common_hashtable::container::Container>::grow_zeroed", file: "/media/ssd1/fangxiaojing/databend/src/common/hashtable/src/container.rs", line: 80 }, 
{ fn: "common_hashtable::table0::Table0<K,V,C,A>::grow", file: "/media/ssd1/fangxiaojing/databend/src/common/hashtable/src/table0.rs", line: 214 }, 
{ fn: "common_hashtable::unsized_hashtable::UnsizedHashtable<K,V,A>::insert_and_entry", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/processors/transforms/group_by/aggregator_state.rs", line: 365 }, { fn: "<databend_query::pipelines::processors::transforms::group_by::aggregator_state::SerializedKeysAggregatorState as databend_query::pipelines::processors::transforms::group_by::aggregator_state::AggregatorState<common_datablocks::kernels::data_block_group_by_hash::HashMethodSerializer>>::entity_by_key", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/processors/transforms/group_by/aggregator_state.rs", line: 365 }, { fn: "databend_query::pipelines::processors::transforms::aggregator::aggregator_final::FinalAggregator<_,Method>::lookup_state", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final.rs", line: 154 }, { fn: "<databend_query::pipelines::processors::transforms::aggregator::aggregator_final::FinalAggregator<_,Method> as databend_query::pipelines::processors::transforms::transform_aggregator::Aggregator>::consume", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/processors/transforms/aggregator/aggregator_final.rs", line: 154 }, { fn: "databend_query::pipelines::processors::transforms::transform_aggregator::ConsumeState<TAggregator>::consume", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/processors/transforms/transform_aggregator.rs", line: 393 }, { fn: "<databend_query::pipelines::processors::transforms::transform_aggregator::AggregatorTransform<TAggregator> as common_pipeline_core::processors::processor::Processor>::process", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/processors/transforms/transform_aggregator.rs", line: 310 }, { fn: "common_pipeline_core::processors::processor::ProcessorPtr::process", file: "/media/ssd1/fangxiaojing/databend/src/query/pipeline/core/src/processors/processor.rs", line: 109 }, { fn: "databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs", line: 82 }, { fn: "databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/executor/executor_worker_context.rs", line: 72 }, { fn: "databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/executor/pipeline_executor.rs", line: 295 }, { fn: "databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/executor/pipeline_executor.rs", line: 255 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs", line: 492 }, { fn: "std::panicking::try", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs", line: 456 }, { fn: "std::panic::catch_unwind", file: "/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs", line: 137 }, { fn: "common_base::base::catch_unwind::catch_unwind", file: "/media/ssd1/fangxiaojing/databend/src/common/base/src/base/catch_unwind.rs", line: 26 }, { fn: "databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}", file: "/media/ssd1/fangxiaojing/databend/src/query/service/src/pipelines/executor/pipeline_executor.rs", line: 254 },
```

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #8585

### CODE REVIEW

File: src/common/base/src/mem_allocator/mmap_allocator.rs [hunk 1]
```diff
@@ -258,15 +258,29 @@ pub mod linux {
             let mut uname = unsafe { std::mem::zeroed::<libc::utsname>() };
             assert_ne!(-1, unsafe { libc::uname(&mut uname) });
             let mut length = 0usize;
-            while length < uname.release.len() && uname.release[length] != 0 {
+
```
Comment (Xuanwo) [inline src/common/base/src/mem_allocator/mmap_allocator.rs:261]: How about using https://docs.rs/sys-info/latest/sys_info/fn.os_release.html and parse it by `semver`?

Comment (sundy-li) [reply src/common/base/src/mem_allocator/mmap_allocator.rs:261]: I noticed that, but I do not want to have extra crate deps because here we already have fallbacks.

**Review by BohuTANG — APPROVED** [review]
