### PR TITLE
[deps] replace mysql with mysql_async

### LINKED ISSUE #3584: error: 1 vulnerability found
**Summary**

https://github.com/datafuselabs/databend/runs/4601020951?check_suite_focus=true

cc @PsiACE

### PR DESCRIPTION
**Pull request by PsiACE**
I hereby agree to the terms of the CLA available at: https://databend.rs/policies/cla/

## Summary

- replace mysql with mysql_async

## Changelog

- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #3584

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

File: query/tests/it/servers/mysql.rs [hunk 1]
```diff
@@ -14,36 +14,33 @@
...
-    let mut connection = create_connection(runnable_server.port())?;
-    let received_data: Vec<String> = query(&mut connection, "SELECT database()")?;
-    assert_eq!(received_data, vec!["default"]);
-    query::<EmptyRow>(&mut connection, "USE system")?;
-    let received_data: Vec<String> = query(&mut connection, "SELECT database()")?;
-    assert_eq!(received_data, vec!["system"]);
+    let mut connection = create_connection(runnable_server.port()).await?;
+    let result = connection.query_iter("SELECT 1, 2, 3;").await;
+
+    assert!(result.is_ok());
```
Comment (PsiACE) [inline query/tests/it/servers/mysql.rs:43]: This is a temporary change.

I'm not familiar with the mysql_async result type conversion. However, it can be confirmed that the query gives the correct results.

Hope to get some help.
