### PR TITLE
fix(query): fix arrow_rs read variant type

### LINKED ISSUE #13759: Feat: uploading support parquet_rs
> unloading is using parquet2, parquet_rs reader does not recognize variant types in unloaded parquet. this is not expected since they are using the same mechanism. cc @b41sh

I'll follow up to fix this.

_Originally posted by @b41sh in https://github.com/datafuselabs/databend/issues/13754#issuecomment-1817546362_

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Fix `arrow_rs` read variant type, the schema in `RecordBatch` doesn't contain extended metadata, so we can't determine the type of `Variant` and `Bitmap`. Use an external schema instead to fix this bug.

- Closes #13759

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13774)

### CODE REVIEW

**Review by youngsofun — APPROVED** [review]

File: src/query/storages/parquet/src/parquet_rs/parquet_reader/utils.rs [hunk 1]
```diff
@@ -119,7 +121,7 @@ pub fn compute_output_field_paths(
     if !inner_projection {
         return Ok(None);
     }
-    let expected_schema = to_arrow_schema(expected_schema);
+    let expected_schema = DataSchema::from(expected_schema);
```
Comment (youngsofun) [inline src/query/storages/parquet/src/parquet_rs/parquet_reader/utils.rs:124]: @b41sh 
so we infact get the right schema here,  what this pr does is to pass it to needed place.
am I right?

**Review by sundy-li — APPROVED** [review]

File: src/query/storages/parquet/src/parquet_rs/parquet_reader/utils.rs (hunk 1 above)
Comment (b41sh) [reply src/query/storages/parquet/src/parquet_rs/parquet_reader/utils.rs:124]: yes, the schema in `RecordBatch` don't have extension type
