### PR TITLE
fix: improve parquet meta reading.

### LINKED ISSUE #12658: cannot correctly infer variant when use_parquet2=0
**Summary**

```
mysql> select /*+ SET_VAR(use_parquet2=0) */ * from infer_schema(location => '@data/variant.parquet');
+-------------+---------+----------+----------+
| column_name | type    | nullable | order_id |
+-------------+---------+----------+----------+
| a           | INT     |        0 |        0 |
| b           | VARCHAR |        0 |        1 |
+-------------+---------+----------+----------+
2 rows in set (2.88 sec)
Read 2 rows, 77.00 B in 2.187 sec., 0.91 rows/sec., 35.21 B/sec.

mysql> select /*+ SET_VAR(use_parquet2=1) */ * from infer_schema(location => '@data/variant.parquet');
+-------------+---------+----------+----------+
| column_name | type    | nullable | order_id |
+-------------+---------+----------+----------+
| a           | INT     |        0 |        0 |
| b           | VARIANT |        0 |        1 |
+-------------+---------+----------+----------+
2 rows in set (2.82 sec)
Read 2 rows, 77.00 B in 2.122 sec., 0.94 rows/sec., 36.28 B/sec.

```

### PR DESCRIPTION
**Pull request by RinChanNOWWW**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- Prefetch `DEFAULT_FOOTER_READ_SIZE` data to try to reduce IO when reading parquet file meta.
- Add extension type information to field metadata to support Databend custom type (Variant, Bitmap, ...).
- Change default settings to allow use parquet-rs by default.

Closes #12658

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/12756)

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

**Review by b41sh — APPROVED** [review]

File: src/query/settings/src/settings_default.rs [hunk 1]
```diff
@@ -357,7 +357,7 @@ impl DefaultSettings {
                     display_in_show_settings: true,
                 }),
                 ("use_parquet2", DefaultSettingValue {
-                    value: UserSettingValue::UInt64(1),
+                    value: UserSettingValue::UInt64(0),
```
Comment (BohuTANG) [inline src/query/settings/src/settings_default.rs:360]: Why we disable the `use_parquet2` by default here? @RinChanNOWWW

Comment (RinChanNOWWW) [reply src/query/settings/src/settings_default.rs:360]: When `parquet_rs` is finely tested, we will remove `parquet2`, so we use `parquet_rs` by default now.
