### PR TITLE
fix: do not reuse expr when function are if

### LINKED ISSUE #13269: bug: make sql divided by zero
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.156

### What's Wrong?

```
 select coalesce((case when a = 0 then NULL else 6/a end) ,0,1) aaa from ( select 0 a union all select 3 a ) test;
APIError: ResponseError with 1001: divided by zero while evaluating function `divide(6, 0)`
```

### How to Reproduce?

 select coalesce((case when a = 0 then NULL else 6/a end) ,0,1) aaa from ( select 0 a union all select 3 a ) test;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

`if` is not same as normal function, they eval with validity, we not reuse expr in these two special functions to avoid bug.

- Closes #13269

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13271)

### CODE REVIEW

File: src/query/sql/src/evaluator/cse.rs [hunk 1]
```diff
@@ -124,6 +124,8 @@ pub fn apply_cse(
 /// and stores the count in a HashMap.
 fn count_expressions(expr: &Expr, counter: &mut HashMap<Expr, usize>) {
     match expr {
+        Expr::FunctionCall { function, .. }
+            if function.signature.name == "if" || function.signature.name == "and_filters" => {}
```
Comment (sundy-li) [inline src/query/sql/src/evaluator/cse.rs:128]: `and_filters`  seems no need to add this.

**Review by sundy-li — APPROVED** [review]

**Review by Dousir9 — APPROVED** [review]
