### PR TITLE
bugfix: Global MetaGrpcClient cause dispatch drop error

### LINKED ISSUE #4347: bug: Global  MetaGrpcClient cause dispatch drop error
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

latest

### What's Wrong?

We have a global meta client inside the query process. It's not recommended to have global hyper client.

See more in: https://togithub.com/hyperium/hyper/issues/2112 and related issues about it.

CI ERROR:

```
2022-03-07T01:10:24.9195619Z [2m2022-03-07T01:10:24.919236Z[0m [31mERROR[0m [2mcommon_tracing::panic_hook[0m[2m:[0m panicked at 'dispatch dropped without returning error', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.17/src/client/conn.rs:1000:39 [3mbacktrace[0m[2m=[0m   0: common_tracing::panic_hook::set_panic_hook::{{closure}}
2022-03-07T01:10:24.9204657Z              at common/tracing/src/panic_hook.rs:25:25
2022-03-07T01:10:24.9205346Z    1: std::panicking::rust_panic_with_hook
2022-03-07T01:10:24.9205840Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:702:17
2022-03-07T01:10:24.9206324Z    2: std::panicking::begin_panic::{{closure}}
2022-03-07T01:10:24.9206788Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:617:9
2022-03-07T01:10:24.9207288Z    3: std::sys_common::backtrace::__rust_end_short_backtrace
2022-03-07T01:10:24.9207799Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:138:18
2022-03-07T01:10:24.9208878Z    4: std::panicking::begin_panic
2022-03-07T01:10:24.9209335Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:616:12
2022-03-07T01:10:24.9209808Z    5: <hyper::client::conn::ResponseFuture as core::future::future::Future>::poll::{{closure}}
2022-03-07T01:10:24.9210611Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.17/src/client/conn.rs:1000:39
2022-03-07T01:10:24.9211032Z       core::task::poll::Poll<T>::map
2022-03-07T01:10:24.9211418Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/task/poll.rs:52:43
2022-03-07T01:10:24.9211854Z       <hyper::client::conn::ResponseFuture as core::future::future::Future>::poll
2022-03-07T01:10:24.9212503Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.17/src/client/conn.rs:996:17
2022-03-07T01:10:24.9213022Z    6: <tonic::transport::service::reconnect::ResponseFuture<F> as core::future::future::Future>::poll
2022-03-07T01:10:24.9213740Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/transport/service/reconnect.rs:215:39
2022-03-07T01:10:24.9214417Z    7: <tower::util::either::Either<A,B> as core::future::future::Future>::poll
2022-03-07T01:10:24.9215040Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.11/src/util/either.rs:71:57
2022-03-07T01:10:24.9215501Z       <tower::util::either::Either<A,B> as core::future::future::Future>::poll
2022-03-07T01:10:24.9216116Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.11/src/util/either.rs:71:57
2022-03-07T01:10:24.9216627Z       <tonic::transport::service::grpc_timeout::ResponseFuture<F> as core::future::future::Future>::poll
2022-03-07T01:10:24.9217316Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/transport/service/grpc_timeout.rs:88:38
2022-03-07T01:10:24.9218531Z       <tonic::transport::service::add_origin::AddOrigin<T> as tower_service::Service<http::request::Request<ReqBody>>>::call::{{closure}}
2022-03-07T01:10:24.9219296Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/transport/service/add_origin.rs:56:34
2022-03-07T01:10:24.9220003Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9220496Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9220920Z    8: <core::pin::Pin<P> as core::future::future::Future>::poll
2022-03-07T01:10:24.9221341Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/future.rs:124:9
2022-03-07T01:10:24.9221776Z    9: <tower::util::either::Either<A,B> as core::future::future::Future>::poll
2022-03-07T01:10:24.9222188Z       <tower::buffer::future::ResponseFuture<F> as core::future::future::Future>::poll
2022-03-07T01:10:24.9222843Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.11/src/buffer/future.rs:75:59
2022-03-07T01:10:24.9223447Z       <tonic::transport::channel::ResponseFuture as core::future::future::Future>::poll
2022-03-07T01:10:24.9224124Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/transport/channel/mod.rs:200:40
2022-03-07T01:10:24.9224622Z   10: <tonic::service::interceptor::ResponseFuture<F> as core::future::future::Future>::poll
2022-03-07T01:10:24.9225295Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/service/interceptor.rs:223:41
2022-03-07T01:10:24.9225741Z       tonic::client::grpc::Grpc<T>::streaming::{{closure}}
2022-03-07T01:10:24.9226335Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/client/grpc.rs:285:27
2022-03-07T01:10:24.9226798Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9227246Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9227668Z       tonic::client::grpc::Grpc<T>::client_streaming::{{closure}}
2022-03-07T01:10:24.9228271Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/client/grpc.rs:180:49
2022-03-07T01:10:24.9228741Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9229184Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9229581Z       tonic::client::grpc::Grpc<T>::unary::{{closure}}
2022-03-07T01:10:24.9230167Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.6.2/src/client/grpc.rs:160:52
2022-03-07T01:10:24.9230632Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9231078Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9231564Z   11: common_meta_types::protobuf::meta_service_client::MetaServiceClient<T>::write_msg::{{closure}}
2022-03-07T01:10:24.9232252Z              at target/x86_64-unknown-linux-gnu/release/build/common-meta-types-648787052dfc24d9/out/meta.rs:285:66
2022-03-07T01:10:24.9232742Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9234857Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9235336Z   12: common_meta_grpc::grpc_client::MetaGrpcClient::do_write::{{closure}}::{{closure}}
2022-03-07T01:10:24.9235733Z              at common/meta/grpc/src/grpc_client.rs:206:43
2022-03-07T01:10:24.9236118Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9237286Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9237760Z   13: common_meta_grpc::grpc_client::MetaGrpcClient::do_write::{{closure}}
2022-03-07T01:10:24.9238151Z              at common/meta/grpc/src/grpc_client.rs:195:5
2022-03-07T01:10:24.9238937Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9239536Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9240440Z       common_meta_grpc::kv_api_impl::<impl common_meta_api::kv_api::KVApi for common_meta_grpc::grpc_client::MetaGrpcClient>::upsert_kv::{{closure}}
2022-03-07T01:10:24.9240915Z              at common/meta/grpc/src/kv_api_impl.rs:31:39
2022-03-07T01:10:24.9241293Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9242278Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9242690Z   14: <core::pin::Pin<P> as core::future::future::Future>::poll
2022-03-07T01:10:24.9243109Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/future.rs:124:9
2022-03-07T01:10:24.9243697Z       <common_management::user::user_mgr::UserMgr as common_management::user::user_api::UserApi>::add_user::{{closure}}
2022-03-07T01:10:24.9244141Z              at common/management/src/user/user_mgr.rs:104:28
2022-03-07T01:10:24.9244545Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9244986Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9245376Z   15: <core::pin::Pin<P> as core::future::future::Future>::poll
2022-03-07T01:10:24.9245787Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/future.rs:124:9
2022-03-07T01:10:24.9246291Z       databend_query::users::user_mgr::<impl databend_query::users::user_api::UserApiProvider>::add_user::{{closure}}
2022-03-07T01:10:24.9246707Z              at query/src/users/user_mgr.rs:97:23
2022-03-07T01:10:24.9247084Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9247527Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9248297Z       <databend_query::interpreters::interpreter_user_create::CreateUserInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}::{{closure}}
2022-03-07T01:10:24.9248869Z              at query/src/interpreters/interpreter_user_create.rs:63:46
2022-03-07T01:10:24.9249280Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9249721Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9250312Z   16: <databend_query::interpreters::interpreter_user_create::CreateUserInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}
2022-03-07T01:10:24.9250872Z              at query/src/interpreters/interpreter_user_create.rs:48:5
2022-03-07T01:10:24.9251279Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9251727Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9252138Z   17: <core::pin::Pin<P> as core::future::future::Future>::poll
2022-03-07T01:10:24.9252555Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/future.rs:124:9
2022-03-07T01:10:24.9253151Z       <databend_query::interpreters::interpreter_factory_interceptor::InterceptorInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute::{{closure}}
2022-03-07T01:10:24.9253735Z              at query/src/interpreters/interpreter_factory_interceptor.rs:61:61
2022-03-07T01:10:24.9254723Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9255171Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9255569Z   18: <core::pin::Pin<P> as core::future::future::Future>::poll
2022-03-07T01:10:24.9256083Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/future.rs:124:9
2022-03-07T01:10:24.9256619Z       databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::exec_query::{{closure}}::{{closure}}::{{closure}}
2022-03-07T01:10:24.9257114Z              at query/src/servers/mysql/mysql_interactive_worker.rs:321:56
2022-03-07T01:10:24.9257543Z       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9257977Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/future/mod.rs:91:19
2022-03-07T01:10:24.9258880Z   19: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
2022-03-07T01:10:24.9262391Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
2022-03-07T01:10:24.9263667Z       tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2022-03-07T01:10:24.9264454Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
2022-03-07T01:10:24.9265183Z       tokio::runtime::task::core::CoreStage<T>::poll
2022-03-07T01:10:24.9268223Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
2022-03-07T01:10:24.9268730Z       tokio::runtime::task::harness::poll_future::{{closure}}
2022-03-07T01:10:24.9270280Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
2022-03-07T01:10:24.9271247Z       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-03-07T01:10:24.9271733Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
2022-03-07T01:10:24.9272104Z       std::panicking::try::do_call
2022-03-07T01:10:24.9273125Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
2022-03-07T01:10:24.9273513Z       std::panicking::try
2022-03-07T01:10:24.9273883Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
2022-03-07T01:10:24.9274430Z   20: std::panic::catch_unwind
2022-03-07T01:10:24.9274786Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
2022-03-07T01:10:24.9275665Z       tokio::runtime::task::harness::poll_future
2022-03-07T01:10:24.9276439Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
2022-03-07T01:10:24.9277013Z   21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
2022-03-07T01:10:24.9279322Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
2022-03-07T01:10:24.9279806Z       tokio::runtime::task::harness::Harness<T,S>::poll
2022-03-07T01:10:24.9280421Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
2022-03-07T01:10:24.9280836Z   22: tokio::runtime::task::raw::RawTask::poll
2022-03-07T01:10:24.9281553Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
2022-03-07T01:10:24.9281985Z       tokio::runtime::task::LocalNotified<S>::run
2022-03-07T01:10:24.9283143Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
2022-03-07T01:10:24.9283602Z       tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
2022-03-07T01:10:24.9284265Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:425:13
2022-03-07T01:10:24.9285004Z       tokio::coop::with_budget::{{closure}}
2022-03-07T01:10:24.9285878Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
2022-03-07T01:10:24.9286305Z       std::thread::local::LocalKey<T>::try_with
2022-03-07T01:10:24.9286914Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/local.rs:413:16
2022-03-07T01:10:24.9287305Z       std::thread::local::LocalKey<T>::with
2022-03-07T01:10:24.9287678Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/local.rs:389:9
2022-03-07T01:10:24.9288447Z       tokio::coop::with_budget
2022-03-07T01:10:24.9289026Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
2022-03-07T01:10:24.9289404Z       tokio::coop::budget
2022-03-07T01:10:24.9290089Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
2022-03-07T01:10:24.9290514Z       tokio::runtime::thread_pool::worker::Context::run_task
2022-03-07T01:10:24.9291899Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
2022-03-07T01:10:24.9292366Z   23: tokio::runtime::thread_pool::worker::Context::run
2022-03-07T01:10:24.9293182Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:391:24
2022-03-07T01:10:24.9293648Z       tokio::runtime::thread_pool::worker::run::{{closure}}
2022-03-07T01:10:24.9294399Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
2022-03-07T01:10:24.9294849Z       tokio::macros::scoped_tls::ScopedKey<T>::set
2022-03-07T01:10:24.9296804Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
2022-03-07T01:10:24.9297272Z       tokio::runtime::thread_pool::worker::run
2022-03-07T01:10:24.9297938Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
2022-03-07T01:10:24.9298399Z   24: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
2022-03-07T01:10:24.9299049Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
2022-03-07T01:10:24.9299565Z       <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
2022-03-07T01:10:24.9300227Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
2022-03-07T01:10:24.9300684Z       tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
2022-03-07T01:10:24.9301289Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
2022-03-07T01:10:24.9301730Z       tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2022-03-07T01:10:24.9302337Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
2022-03-07T01:10:24.9302771Z       tokio::runtime::task::core::CoreStage<T>::poll
2022-03-07T01:10:24.9303353Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
2022-03-07T01:10:24.9304180Z       tokio::runtime::task::harness::poll_future::{{closure}}
2022-03-07T01:10:24.9304805Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
2022-03-07T01:10:24.9305316Z       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-03-07T01:10:24.9305782Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
2022-03-07T01:10:24.9306155Z       std::panicking::try::do_call
2022-03-07T01:10:24.9306528Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
2022-03-07T01:10:24.9306869Z       std::panicking::try
2022-03-07T01:10:24.9307230Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
2022-03-07T01:10:24.9307584Z       std::panic::catch_unwind
2022-03-07T01:10:24.9308086Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
2022-03-07T01:10:24.9308454Z       tokio::runtime::task::harness::poll_future
2022-03-07T01:10:24.9309072Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
2022-03-07T01:10:24.9309528Z       tokio::runtime::task::harness::Harness<T,S>::poll_inner
2022-03-07T01:10:24.9310147Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
2022-03-07T01:10:24.9310578Z       tokio::runtime::task::harness::Harness<T,S>::poll
2022-03-07T01:10:24.9311186Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
2022-03-07T01:10:24.9311681Z       tokio::runtime::task::raw::poll
2022-03-07T01:10:24.9312260Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
2022-03-07T01:10:24.9312665Z   25: tokio::runtime::task::raw::RawTask::poll
2022-03-07T01:10:24.9313246Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
2022-03-07T01:10:24.9313670Z       tokio::runtime::task::UnownedTask<S>::run
2022-03-07T01:10:24.9314233Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
2022-03-07T01:10:24.9314651Z       tokio::runtime::blocking::pool::Task::run
2022-03-07T01:10:24.9315242Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
2022-03-07T01:10:24.9315679Z       tokio::runtime::blocking::pool::Inner::run
2022-03-07T01:10:24.9316268Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
2022-03-07T01:10:24.9316746Z       tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
2022-03-07T01:10:24.9317380Z              at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
2022-03-07T01:10:24.9317827Z       std::sys_common::backtrace::__rust_begin_short_backtrace
2022-03-07T01:10:24.9318239Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:122:18
2022-03-07T01:10:24.9318676Z   26: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
2022-03-07T01:10:24.9319099Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:498:17
2022-03-07T01:10:24.9319560Z       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-03-07T01:10:24.9320020Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
2022-03-07T01:10:24.9320444Z       std::panicking::try::do_call
2022-03-07T01:10:24.9320817Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
2022-03-07T01:10:24.9321172Z       std::panicking::try
2022-03-07T01:10:24.9321520Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
2022-03-07T01:10:24.9321875Z       std::panic::catch_unwind
2022-03-07T01:10:24.9322229Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
2022-03-07T01:10:24.9322621Z       std::thread::Builder::spawn_unchecked_::{{closure}}
2022-03-07T01:10:24.9323007Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:497:30
2022-03-07T01:10:24.9324211Z       core::ops::function::FnOnce::call_once{{vtable.shim}}
2022-03-07T01:10:24.9324634Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/ops/function.rs:227:5
2022-03-07T01:10:24.9325044Z   27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-03-07T01:10:24.9325580Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
2022-03-07T01:10:24.9326006Z       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-03-07T01:10:24.9326422Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
2022-03-07T01:10:24.9326799Z       std::sys::unix::thread::Thread::new::thread_start
2022-03-07T01:10:24.9327199Z              at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys/unix/thread.rs:108:17
2022-03-07T01:10:24.9327534Z   28: start_thread
2022-03-07T01:10:24.9327761Z   29: clone
```

### What You Expected?

x

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ariesdevil**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Bugfix: Global MetaGrpcClient cause dispatch drop error.

- move `MetaGrpcClient` from `SessionManager` to `Session` to avoid cross-runtime client clone.

**NOTE**
The current implementation leaves two issues
1. the `Drop` trait that impl by SessionRef using `block_on` to call async fn.
2. As of current existing query processing logic of HTTP handler is different from others(MySQL, ClickHouse), so the SessionManager still has a Client that provides HTTP handler to use.

## Changelog

- Bug Fix

## Related Issues

Fixes #4347 

## Test Plan

Unit Tests

Stateless Tests

### CODE REVIEW

File: query/src/sessions/session.rs [hunk 1]
```diff
@@ -68,6 +79,9 @@ impl Session {
             session_mgr,
             ref_count,
             session_ctx,
+            user_manager,
```
Comment (sundy-li) [inline query/src/sessions/session.rs:82]: Is it possible to make it lazy initialize?

Since most queries may not need this...

Comment (ariesdevil) [reply query/src/sessions/session.rs:82]: It is already lazy initialization, [MetaGrpcClient::try_new](https://github.com/datafuselabs/databend/blob/51b0ba2667e84e911c6b6309803713de0a1cd0f1/common/meta/grpc/src/grpc_client.rs#L112) just create a connection pool and only make real client instance when do read/write actions.

File: query/src/sessions/session_mgr.rs [hunk 2]
```diff
@@ -187,7 +191,7 @@ impl SessionManager {
 
     #[allow(clippy::ptr_arg)]
     pub fn get_session_by_id(self: &Arc<Self>, id: &str) -> Option<SessionRef> {
-        let sessions = self.active_sessions.read();
+        let sessions = futures::executor::block_on(self.active_sessions.read());
```
Comment (BohuTANG) [inline query/src/sessions/session_mgr.rs:194]: I am worried about the `active_sessions` lock here, it's a async and we `block_on` it to sync here, it seems not a good way.

Comment (ariesdevil) [reply query/src/sessions/session_mgr.rs:194]: I initially wanted to unify into all to async approach, but when I want to make [processes_info](https://github.com/datafuselabs/databend/pull/4361/files#diff-05e190acf915432f50b78d25482d816df331623745159f6e235f255aa4c73516R247) to async, I found it will make a huge change to the codebase...
The [ProcessesTable](https://github.com/datafuselabs/databend/blob/51b0ba2667e84e911c6b6309803713de0a1cd0f1/query/src/storages/system/processes_table.rs#L45) implement the `SyncSystemTable`, and `SyncSystemTable` is a sync trait and implemented by many tables. So I choose the block_one way.

But for this `get_session_by_id`, change it to the async function is easy.

Comment (ariesdevil) [reply query/src/sessions/session_mgr.rs]: So let's first make CI pass, then I'll try to change all related block_on to async way.

Comment (BohuTANG) [reply query/src/sessions/session_mgr.rs]: We can make `ProcessesTable` to AsyncSystemTable using the new processor.
@zhang2014  maybe give some suggestions here

File: query/src/sessions/session.rs (hunk 1 above)
Comment (youngsofun) [reply query/src/sessions/session.rs:82]: e.g.  Is it possible to make  .try_get_kv_client() called lazy too?


```
    pub async fn create_global(conf: Config) -> Result<Arc<UserApiProvider>> {
        let client = MetaClientProvider::new(conf.meta.to_grpc_client_config())
            .try_get_kv_client()
            .await?;

        Ok(Arc::new(UserApiProvider { client }))
    }
```

i.e. make MetaGrpcClient created lazy?

Comment (ariesdevil) [reply query/src/sessions/session.rs:82]: In `try_get_kv_client`, it first checks if metaservice is local embedded, and if local, it will create a local meta store instead of grpc client. The creation of local meta store is async...

File: query/src/sessions/session_mgr.rs (hunk 2 above)
Comment (BohuTANG) [reply query/src/sessions/session_mgr.rs]: :cry:

**Comment by youngsofun** [comment]
GLOBAL_META_EMBEDDED not inited
 MetaEmbedded::new_temp() called mutli times. 

https://github.com/youngsofun/databend/commit/adebe240086b34999b97f41233484394566a95ef

**Comment by youngsofun** [comment]
@ariesdevil 

block_on inside async block may lead to dead lock, is this the case here？

https://github.com/seanmonstar/reqwest/issues/1215

**Comment by ariesdevil** [comment]
> 



> GLOBAL_META_EMBEDDED not inited MetaEmbedded::new_temp() called mutli times.
> 
> [youngsofun/databend@`zyj_dev` (commits)](https://github.com/youngsofun/databend/commits/zyj_dev)
> 
> test passed after it is inited

We can use this way fix for now.

**Comment by ariesdevil** [comment]
> try to run globalinit only once in tests？
> 
> including
> 
> 1.utils like once staic 1.check and call in sessionmgr builder for all tests 1.hack global init itself，afterall embed is mainly for test？

We should avoid using global init in unit tests, global init is just used when query node init and no meta node is configured in the config file. Let's find a way solve it.

File: query/src/sessions/session_mgr.rs [hunk 3]
```diff
@@ -201,7 +201,8 @@ impl SessionManager {
             &self.conf.query.cluster_id,
         );
 
-        self.active_sessions.write().remove(session_id);
+        let mut sessions = futures::executor::block_on(self.active_sessions.write());
```
Comment (BohuTANG) [inline query/src/sessions/session_mgr.rs:204]: await?

File: query/src/sessions/session_mgr.rs [hunk 4]
```diff
@@ -232,14 +233,15 @@ impl SessionManager {
...
+                .await
                 .values()
                 .for_each(Session::force_kill_session);
         }
     }
 
     pub fn processes_info(self: &Arc<Self>) -> Vec<ProcessInfo> {
-        self.active_sessions
-            .read()
+        let sessions = futures::executor::block_on(self.active_sessions.read());
```
Comment (BohuTANG) [inline query/src/sessions/session_mgr.rs:243]: Should avoid using `block_on`, if it possible let's make the function to `async`.

File: query/src/sessions/session_mgr.rs (hunk 2 above)
Comment (flaneur2020) [reply query/src/sessions/session_mgr.rs]: if the outter async runtime is tokio, `futures::executor::block_on` might causes stuck as https://github.com/tokio-rs/tokio/issues/2603 describes.

**Comment by youngsofun** [comment]
@ariesdevil 

> We should avoid using global init in unit tests,

got it.

so we need:

1. diff test case use diff MetaEmbedded.
2. multi session in a test case should use the same one.  todo.

**Comment by youngsofun** [comment]
@ariesdevil  wrt http handler， I prefer to retain global auth_mgr/user_mgr. when not related to diff runtimes, it is safe and efficient to have a global conn pool,   we can add some comment  avoid miss using  it. 



---
> multi session in a test case should use the same MetaEmbedded

I think of 2 ways

1. keep an the instance in session_manager, need refactor 
1. a global dict to hold MetaEmbedded instance (bad), assign a uniq id to some field of config when build session_manager, get_or_create(uniq id) instead of new_temp(),

File: query/src/sessions/session_mgr.rs (hunk 4 above)
Comment (ariesdevil) [reply query/src/sessions/session_mgr.rs:243]: https://github.com/datafuselabs/databend/pull/4361#discussion_r822347236

File: query/src/sessions/session_mgr.rs (hunk 3 above)
Comment (ariesdevil) [reply query/src/sessions/session_mgr.rs:204]: This function is eventually called by drop function that impl Drop trait, async drop still in rust roadmap...

File: query/src/sessions/session_mgr.rs (hunk 4 above)
Comment (ariesdevil) [reply query/src/sessions/session_mgr.rs]: Solved, thanks @zhang2014

File: query/src/sessions/session_mgr.rs (hunk 3 above)
Comment (drmingdrmer) [reply query/src/sessions/session_mgr.rs:204]: Can you make `active_sessions` an `std::sync::Mutex`?
Then the `await` can be get rid of.

But using a sync-mode mutex introduces some retry-loops when inserting items into it.
Because it can not be held across an `await`.

Comment (flaneur2020) [reply query/src/sessions/session_mgr.rs:204]: i guess std::sync::Mutex is ok in this case, but should be careful NOT to introduce any async/await point inside the mutex guard.

1. sync mutex lock
2. await yield out to another coroutine
3. another coroutine tries to acquire the lock

however, it's a good practise to not do any blocking operations inside a mutex guard

**Review by drmingdrmer — COMMENTED** [review]
It looks good to me.
But I'm not familiar with the underlying logic around `session`.
So let experts approve.

File: query/src/sessions/session_mgr.rs [hunk 5]
```diff
@@ -132,34 +124,46 @@ impl SessionManager {
...
+            &self.conf.query.cluster_id,
+        );
+        let mut sessions = self.active_sessions.write().await;
+        if sessions.len() < self.max_sessions {
+            sessions.insert(session.get_id(), session.clone());
 
-                sessions.insert(session.get_id(), session.clone());
-                Ok(SessionRef::create(session))
-            }
+            Ok(SessionRef::create(session))
```
Comment (drmingdrmer) [inline query/src/sessions/session_mgr.rs:153]: The metrics counter should be moved into the if-closure.

But I am not sure if `label_counter` contains any async calls in it.

**Review by zhang2014 — APPROVED** [review]
