### PR TITLE
fix: consume stream inside explicit txn

### LINKED ISSUE #15581: bug:  `select ... from stream with consume` not work as expected in non auto commit mode
**Summary**

`select ... from stream with consume` not work as expected in non auto commit mode

how to reproduce:

the following test case should return a non-empty result set at the end, but not.

~~~
create or replace database poc_databend;

use poc_databend;


create  or replace table t_1 (
  str varchar 
);


create or replace stream s_1 on table t_1 append_only = true;


insert into t_1 (str) values ('a'), ('b');


begin;

      select * from s_1 with consume;
      select 1/0;

commit;

select * from s_1; -- expects non-empty result set but NOT
~~~

### PR DESCRIPTION
**Pull request by dantengsky**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

- The consuming (`with consume`) of stream should respect the semantics of transactions: if  transaction is aborted, the stream should roll back to its original state.

- Only the usage of `WITH CONSUME` in queries is allowed. Statements like `INSERT INTO t SELECT * FROM s WITH CONSUME` will fail with errors.

- Fixes #15581

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15582)

### CODE REVIEW

File: src/query/service/src/interpreters/common/stream.rs [hunk 1]
```diff
@@ -129,7 +136,7 @@ pub async fn query_build_update_stream_req(
         new_table_meta.options = options;
         new_table_meta.updated_on = Utc::now();
 
-        update_table_metas.push(UpdateTableMetaReq {
+        update_table_meta_reqs.push(UpdateTableMetaReq {
```
Comment (SkyFan2002) [inline src/query/service/src/interpreters/common/stream.rs:139]: Sometimes we use `UpdateTableMetaReq` to update a stream, and other times we use `UpdateTableMetaReq.update_stream_meta`. But both `SchemaApi::update_table_meta()` and `update_table_meta()` handle `stream` and `table` with subtle differences. Although the current implementation is logically correct, we could consider refactoring in the future to express the requests for updating a stream and updating a table with a more clear structure, to avoid potential bugs.

Comment (dantengsky) [reply src/query/service/src/interpreters/common/stream.rs:139]: agree

File: tests/sqllogictests/suites/ee/06_ee_stream/06_0002_stream_txn_consume.test [hunk 2]
```diff
@@ -288,6 +288,119 @@ query I
...
+onlyif http
+query I
+select str from s_1 order by str;
+----
+a
+b
+
+onlyif http
+query I
+select str from s_1 with consume order by str;
```
Comment (SkyFan2002) [inline tests/sqllogictests/suites/ee/06_ee_stream/06_0002_stream_txn_consume.test:388]: It would be better to test if repeatable read of stream works with both dml and '`select.. with consume` in a single txn.

Comment (dantengsky) [reply tests/sqllogictests/suites/ee/06_ee_stream/06_0002_stream_txn_consume.test:388]: good idea, let me insert a dml here

File: src/query/sql/src/planner/binder/binder.rs [hunk 3]
```diff
@@ -663,6 +664,22 @@ impl<'a> Binder {
                 self.bind_set_priority(priority, object_id).await?
             },
         };
+
+        match plan.kind() {
+            QueryKind::Query { .. } | QueryKind::Explain { .. } => {}
+            _ => {
+                let meta_data_guard = self.metadata.read();
+                let tables = meta_data_guard.tables();
+                for t in tables {
```
Comment (BohuTANG) [inline src/query/sql/src/planner/binder/binder.rs:673]: If a database has many tables, this check may break performance?

Comment (BohuTANG) [reply src/query/sql/src/planner/binder/binder.rs:673]: This check is work?
https://github.com/datafuselabs/databend/blob/2bfe458d31feb6a067cefb3b090c02f260d0fbcb/src/query/sql/src/planner/binder/table.rs#L265-L269

Comment (dantengsky) [reply src/query/sql/src/planner/binder/binder.rs:673]: this only involves the tables that bounded in the statement, not all the tables of a database.

File: tests/sqllogictests/suites/ee/06_ee_stream/06_0002_stream_txn_consume.test (hunk 2 above)
Comment (dantengsky) [reply tests/sqllogictests/suites/ee/06_ee_stream/06_0002_stream_txn_consume.test]: test added, PTAL

**Review by SkyFan2002 — APPROVED** [review]
