### PR TITLE
fix(storage): recluster panic

### LINKED ISSUE #11723: bug: Recluster Table ERROR, Cannot join handle from context's runtime, cause: task XX panicked.
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.1.46-nightly-377d21f7f0675bb6b08a02d79df65aa3c9975a4c(rust-1.70.0-nightly-2023-05-24T16:07:06.096155586Z)

### What's Wrong?

when running sql below，a panic error was thrown
```sql
ALTER TABLE XX RECLUSTER FINAL;
ERROR 1105 (HY000): Code: 1068, Text = Cannot join handle from context's runtime, cause: task 21806 panicked.
```

**Table schema：**
CREATE TABLE `XX` (
 ....
) ENGINE=FUSE CLUSTER BY (to_date(TO_TIMESTAMP(created_at)), sid, deleted) 

### How to Reproduce?

above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Remove unwrap to avoid panic.
Fix possible dead cycles

Closes #11723

### CODE REVIEW

**Review by dantengsky — APPROVED** [review]

File: src/query/storages/fuse/src/operations/recluster.rs [hunk 1]
```diff
@@ -156,7 +158,7 @@ impl FuseTable {
         }
 
         // sort
-        let block_size = ctx.get_settings().get_max_block_size()? as usize;
+        let block_size = self.get_option(FUSE_OPT_KEY_ROW_PER_BLOCK, DEFAULT_BLOCK_MAX_ROWS);
```
Comment (dantengsky) [inline src/query/storages/fuse/src/operations/recluster.rs:161]: oh, maybe `settings.max_block_size` is better?

value of table options  FUSE_OPT_KEY_ROW_PER_BLOCK may be much larger than settings.max_block_size.

Comment (RinChanNOWWW) [reply src/query/storages/fuse/src/operations/recluster.rs:161]: I think `settings.max_block_size` is better. The block size threshold is used to split large block in Sort.

**Review by RinChanNOWWW — APPROVED** [review]

**Review by sundy-li — APPROVED** [review]

File: tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster [hunk 2]
```diff
@@ -8,41 +8,57 @@ statement ok
...
-select * from t09_0016 order by a
+select * from t1 order by a
 ----
 1 1
 2 2
 3 3
 4 4
 5 5
 
+# Fix dead cycles in PR #11762 (https://github.com/datafuselabs/databend/pull/11762).
```
Comment (BohuTANG) [inline tests/sqllogictests/suites/base/09_fuse_engine/09_0016_remote_alter_recluster:44]: 11762 is this pr, i guess it's another one.

File: src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs [hunk 3]
```diff
@@ -196,4 +196,14 @@ impl ReclusterMutator {
 
         Ok(false)
     }
+
+    // block1: [1, 2], block2: [2, 3]. The depth of point '2' is 1.
+    fn check_point(start: &[usize], end: &[usize]) -> bool {
```
Comment (JackTan25) [inline src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:201]: I‘m confused here, why this occasion's point depth is 1. Why it's special?? This will cause the panic??

File: src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs [hunk 4]
```diff
@@ -163,17 +171,9 @@ impl ReclusterMutator {
...
-                if overlap.len() == max_depth {
-                    overlap.iter().for_each(|&idx| {
-                        selected_idx.insert(idx);
-                    });
-                    find = true;
-                } else if find {
-                    break;
-                }
-            }
+            point_overlaps[max_points[0]].iter().for_each(|idx| {
```
Comment (JackTan25) [inline src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:174]: just gather the first one? so other blocks with the same max point depth should be thrown away??
