### PR TITLE
chore(query): add cluster_by info into show tables and fix some err

### LINKED ISSUE #13005: improve: `show tables` returns more stats
**Summary**

Now:
```
SHOW TABLES

┌──────────────────────────────────┐
│ Tables_in_tpch_sf100_native_zstd │
│              String              │
├──────────────────────────────────┤
│ customer                         │
│ lineitem                         │
│ lineitem_zstd                    │
│ nation                           │
│ orders                           │
│ part                             │
│ partsupp                         │
│ region                           │
│ supplier                         │
└──────────────────────────────────┘
```

This is not useful for users, they also want:
```
created_on| cluster_by | rows | bytes |  kind
```

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

As title

- Closes #13005 #12084

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13009)

### CODE REVIEW

File: src/query/sql/src/planner/binder/ddl/table.rs [hunk 1]
```diff
@@ -272,7 +273,7 @@ impl Binder {
         NULL AS Row_format, num_rows AS Rows, NULL AS Avg_row_length, data_size AS Data_length, \
         NULL AS Max_data_length, index_size AS Index_length, NULL AS Data_free, NULL AS Auto_increment, \
         created_on AS Create_time, NULL AS Update_time, NULL AS Check_time, NULL AS Collation, \
-        NULL AS Checksum, '' AS Comment"
+        NULL AS Checksum, '' AS Comment, cluster_by as Cluster_by"
```
Comment (BohuTANG) [inline src/query/sql/src/planner/binder/ddl/table.rs:276]: How we get the` cluser_by` value?

**Comment by TCeason** [comment]
1. Show full tables and show table status support display table cluster_by info

2. fix nested query system table with filter err result. Already add case into test.

**Comment by TCeason** [comment]
> 1. Show full tables and show table status support display table cluster_by info
> 
> 2. fix nested query system table with filter err result. Already add case into test.

cc @soyeric128 show tables and show table status add new field Cluster_by

**Review by BohuTANG — APPROVED** [review]
