### PR TITLE
fix(query): fix precision of timestamp's stats in parquet-rs

### LINKED ISSUE #13270: bug: filter result empty on external parquet file
With data from AWS billing report parquet files:

```python
from databend import SessionContext

ctx = SessionContext()
ctx.register_parquet("report", "./data/", "*.parquet")
ctx.sql("set use_parquet2=0;").collect()
ctx.sql("create table usage like report;").collect()
ctx.sql("insert into usage select * from report;").collect()
ctx.sql("select sum(line_item_unblended_cost) from report where line_item_usage_start_date between '2023-10-13 00:00:00' and '2023-10-14 00:00:00'").show()
ctx.sql("select sum(line_item_unblended_cost) from usage where line_item_usage_start_date between '2023-10-13 00:00:00' and '2023-10-14 00:00:00'").show()
```

The first result from `report` is null, while the latter one from `usage` is normal.

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

fix(query): fix precision of timestamp's stats in parquet-rs

- Closes #13270

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/13284)

### CODE REVIEW

**Review by everpcpc — APPROVED** [review]

File: tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.sh [hunk 1]
```diff
@@ -35,6 +35,16 @@ echo "drop stage if exists s3;" | $MYSQL_CLIENT_CONNECT
 echo "create stage s3 url = '${DATADIR}' FILE_FORMAT = (type = CSV);"  | $MYSQL_CLIENT_CONNECT
 echo "set use_parquet2 = ${USE_PARQUET2} ; select * from @s3 (FILE_FORMAT => 'PARQUET');" | $MYSQL_CLIENT_CONNECT
 
+
```
Comment (youngsofun) [inline tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_00_basic.sh:38]: for read only tests.
it would be easier to maintain if use sqllogic test.
under suit stage_parquet

File: src/query/storages/parquet/src/parquet_rs/statistics/column.rs [hunk 2]
```diff
@@ -79,7 +79,17 @@ pub fn convert_column_statistics(s: &Statistics, typ: &TableDataType) -> ColumnS
                     TableDataType::Number(NumberDataType::Int64) => {
                         (Scalar::from(max), Scalar::from(min))
                     }
-                    TableDataType::Timestamp => (Scalar::Timestamp(max), Scalar::Timestamp(min)),
+                    TableDataType::Timestamp => {
+                        let multi = match max.checked_ilog10().unwrap_or_default() + 1 {
```
Comment (youngsofun) [inline src/query/storages/parquet/src/parquet_rs/statistics/column.rs:83]: as a statistic of some data, max can be any value from 0? 
not always for `2023...`?

Comment (sundy-li) [reply src/query/storages/parquet/src/parquet_rs/statistics/column.rs:83]: > max can be any value start from 0

Yes,  if the number of digits is less or equal  than  10, we set the unit to be second.  This could enlarge the range if the real precision is `ms` or others. But it will still work correctly in range pruner.

> data not always 2023...

Yes, the  timestamp value is time seconds(mills, micro, nanos) from epoch.

**Review by youngsofun — APPROVED** [review]
