### PR TITLE
fix: try to fix cte with duplicate name

### LINKED ISSUE #9029: bug: duplicate CTE source
**Summary**

```

MySQL [(none)]> select A.*, B.* from  (WITH source AS (select 1 as e) SELECT * FROM source) A,   (WITH source AS (select 1 as e) SELECT * FROM source) B;
ERROR 1105 (HY000): Code: 1065, displayText = duplicate cte source.
```

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Closes #9029

### CODE REVIEW

File: src/query/sql/src/planner/semantic/name_resolution.rs [hunk 1]
```diff
@@ -56,7 +56,7 @@ pub fn normalize_identifier<'a>(
         ident.clone()
     } else {
         Identifier {
-            name: ident.name.to_lowercase(),
+            name: ident.name.clone(),
```
Comment (Xuanwo) [inline src/query/sql/src/planner/semantic/name_resolution.rs:59]: I'm afraid this issue is more deep than this.

```sql
CREATE VIEW view_1 AS WITH source as (SELECT 1) SELECT * from source;

SELECT * from view_1;

CREATE VIEW view_2 AS WITH source as (SELECT 1) SELECT * from source;

SELECT * from view_2;

select * from VIEW_1 join view_2;
```

Comment (xudong963) [reply src/query/sql/src/planner/semantic/name_resolution.rs:59]: Filed an issue: https://github.com/datafuselabs/databend/issues/9049

Better to fix them in different PRs.

**Comment by xudong963** [comment]
@mergify update

**Review by BohuTANG — APPROVED** [review]
