### PR TITLE
fix(function): map access support array and function

### LINKED ISSUE #5305: Bug: select ([1,2])[100]
**Summary**

The index is not used, always returns the array:
```
select ([1,2])[100];
+--------+
| [1, 2] |
+--------+
| [1, 2] |

```

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

map access support array and function
support empty array

## Changelog

- Improvement

## Related Issues

Fixes #5305

### CODE REVIEW

File: tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.sql [hunk 1]
```diff
@@ -26,6 +29,14 @@ select json_extract_path_text('{"customer":{"id":1, "name":"databend", "extras":
 select json_extract_path_text('{"customer":{"id":1, "name":"databend", "extras":["ext", "test"]}}', 'customer["extras"][2]');
 select json_extract_path_text('{"customer":{"id":1, "name":"databend", "extras":["ext", "test"]}}', ''); -- {ErrorCode 1005}
 
+select '==array get==';
+select [][0];
+select [0,1,2,3][0];
+select [[[1,2,3],[4,5,6]],[[7,8,9]]][0];
```
Comment (sundy-li) [inline tests/suites/0_stateless/02_function/02_0051_function_semi_structureds_get.sql:35]: Great！

**Review by sundy-li — APPROVED** [review]
