### PR TITLE
fix(privilege): add privileges on system.one to PUBLIC by default

### LINKED ISSUE #10036: Bug: Permission denied, user 'testgatrpzwjo-0-cl1'@'%' requires SELECT privilege on 'default'.'system'.'one'. on executing SELECT 1
**Summary**

maybe `SELECT 1` do not need checking privieleges?

### PR DESCRIPTION
**Pull request by flaneur2020**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

This PR adds a SELECT privilege on system.one to the PUBLIC role, so the normal users can execute `SELECT 1` without hitting permission denied error.

Closes #10036

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

File: src/query/users/src/role_mgr.rs [hunk 1]
```diff
@@ -78,17 +79,26 @@ impl UserApiProvider {
...
         );
-        self.add_role(tenant, role_info, true).await?;
-        let role_info = RoleInfo::new(BUILTIN_ROLE_PUBLIC);
-        self.add_role(tenant, role_info, true).await
+        self.add_role(tenant, account_admin, true).await?;
+
+        let mut public = RoleInfo::new(BUILTIN_ROLE_PUBLIC);
+        public.grants.grant_privileges(
+            &GrantObject::Table(
+                "default".to_string(),
```
Comment (BohuTANG) [inline src/query/users/src/role_mgr.rs:95]: We can define a system database list and each item has what's a role that can grant it, it easy to maintain.

Comment (flaneur2020) [reply src/query/users/src/role_mgr.rs:95]: currently we only have two roles builtin `account_admin` and `public`, these two roles are both special:

1. `account_admin` can access every tables
2. `public` is supposed to not able to access any system table at all.

We translate `SELECT 1` to query an internal table `system.one`, this makes us have to grant a privilege on `system.one` for every user. However the query `SELECT 1` do not really touches any tables in the query semantics. So I guess `system.one` can be viewed as a special corner case?
