### PR TITLE
fix(cluster): fix limit query hang in cluster mode

### LINKED ISSUE #9993: test: main branch test_stateful_cluster_linux timeout
**Summary**

Always timeout:
https://github.com/datafuselabs/databend/actions/runs/4152074381/jobs/7183247396#step:3:459

```
04_0000_mini_ontime:                                                    [ FAIL ] - Timeout!
04_0001_mini_hits:                                                      [ FAIL ] - Timeout!

... ...

Having 2 errors! 49 tests passed.                     0 tests skipped.
The failure tests:
    /home/runner/work/databend/databend/tests/suites/1_stateful/04_mini_dataset/04_0000_mini_ontime.sh
    /home/runner/work/databend/databend/tests/suites/1_stateful/04_mini_dataset/04_0001_mini_hits.sh
Error: Process completed with exit code 1.
Prepare all required actions
Getting action download info
Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
Run ./.github/actions/artifact_failure
Run tar --exclude='target' \
tar: .: file changed as we read it
```

### PR DESCRIPTION
**Pull request by zhang2014**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

fix(cluster): fix limit query hang in cluster mode

Closes #9993

### CODE REVIEW

**Review by BohuTANG — APPROVED** [review]

File: src/query/service/src/api/rpc/packets/packet_data.rs [hunk 1]
```diff
@@ -172,7 +183,8 @@ impl TryFrom<FlightData> for DataPacket {
                     progress: progress_info,
                 })
             }
-            0x05 => Ok(DataPacket::ClosingClient),
+            0x05 => Ok(DataPacket::ClosingOutput),
```
Comment (Xuanwo) [inline src/query/service/src/api/rpc/packets/packet_data.rs:186]: Do we need to add enum for them?

**Comment by BohuTANG** [comment]
stateless&stateful cluster test all timeout in the main branch:
https://github.com/datafuselabs/databend/actions/runs/4165952146/jobs/7210797677
https://github.com/datafuselabs/databend/actions/runs/4165952146/jobs/7210797015

File: src/query/service/src/api/rpc/packets/packet_data.rs (hunk 1 above)
Comment (zhang2014) [reply src/query/service/src/api/rpc/packets/packet_data.rs:186]: Enum nesting without any field may be meaningless.
