### PR TITLE
fix(query): tuple field name can not contain special char

### LINKED ISSUE #15125: bug: tuple field with special char will cause session panic
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main branch

### What's Wrong?

```sql
create table t(d tuple("A-a" int, b int));
```

```
panicked at src/query/ast/src/parser/parser.rs:67:13:
Failed to reparse SQL:
create table tc(d tuple("A-a" int, b int))
AST:
CreateTable(
    CreateTableStmt {
        create_option: Create,
        catalog: None,
        database: None,
        table: Identifier {
            span: Some(
                13..15,
            ),
            name: "tc",
            quote: None,
            is_hole: false,
        },
        source: Some(
            Columns(
                [
                    ColumnDefinition {
                        name: Identifier {
                            span: Some(
                                16..17,
                            ),
                            name: "d",
                            quote: None,
                            is_hole: false,
                        },
                        data_type: Tuple {
                            fields_name: Some(
                                [
                                    "A-a",
                                    "b",
                                ],
                            ),
                            fields_type: [
                                Int32,
                                Int32,
                            ],
                        },
                        expr: None,
                        comment: None,
                    },
                ],
            ),
        ),
        engine: None,
        uri_location: None,
        cluster_by: [],
        table_options: {},
        as_query: None,
        transient: false,
    },
)
SyntaxException. Code: 1005, Text = error: 
  --> SQL:1:27
  |
1 | CREATE TABLE tc (d TUPLE(A-a Int32, b Int32))
  | ------           - -----  ^ unexpected `-`, expecting `BOOLEAN`, `BOOL`, `UINT8`, `TINYINT`, `UINT16`, `SMALLINT`, `UINT32`, `INT`, `INTEGER`, `UINT64`, `UNSIGNED`, `BIGINT`, `INT8`, `INT16`, `INT32`, `INT64`, `SIGNED`, `FLOAT32`, `FLOAT`, `FLOAT64`, `DOUBLE`, `DECIMAL`, `ARRAY`, `MAP`, `BITMAP`, `TUPLE`, `DATE`, `DATETIME`, `TIMESTAMP`, `BINARY`, `VARBINARY`, `LONGBLOB`, `MEDIUMBLOB`, `TINYBLOB`, `BLOB`, `STRING`, `VARCHAR`, `CHAR`, `CHARACTER`, `TEXT`, `VARIANT`, `JSON`, `GEOMETRY`, or `NULLABLE`
  | |                | |       
  | |                | while parsing TUPLE(<name> <type>, ...)
  | |                | while parsing type name
  | |                while parsing `<column name> <type> [DEFAULT <expr>] [AS (<expr>) VIRTUAL] [AS (<expr>) STORED] [COMMENT '<comment>']`
  | while parsing `CREATE [OR REPLACE] TABLE [IF NOT EXISTS] [<database>.]<table> [<source>] [<table_options>]`

.
   0: databend_common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: databend_common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2030:9
   3: std::panicking::rust_panic_with_hook
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:785:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:659:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/sys_common/backtrace.rs:171:18
   6: rust_begin_unwind
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:647:5
   7: core::panicking::panic_fmt
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/panicking.rs:72:14
   8: databend_common_ast::parser::parser::parse_sql::{{closure}}
             at ./src/query/ast/src/parser/parser.rs:67:13
   9: core::result::Result<T,E>::unwrap_or_else
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/result.rs:1426:23
  10: databend_common_ast::parser::parser::parse_sql
             at ./src/query/ast/src/parser/parser.rs:65:9
  11: databend_common_sql::planner::planner::Planner::plan_sql::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/query/sql/src/planner/planner.rs:130:21
  12: databend_common_sql::planner::planner::Planner::plan_sql::{{closure}}::{{closure}}::{{closure}}
             at ./src/query/sql/src/planner/planner.rs:174:14
  13: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/framed.rs:49:27
  14: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:184:17
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:286:16
  16: std::thread::local::LocalKey<T>::with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:262:9
  17: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:81:9
  18: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:180:13
  19: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/framed.rs:49:9
  20: databend_common_sql::planner::planner::Planner::plan_sql::{{closure}}::{{closure}}
             at ./src/query/sql/src/planner/planner.rs:69:5
  21: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.6.4/src/future.rs:125:19
  22: databend_common_sql::planner::planner::Planner::plan_sql::{{closure}}
             at ./src/query/sql/src/planner/planner.rs:69:5
  23: databend_query::interpreters::interpreter::interpreter_plan_sql::{{closure}}
             at ./src/query/service/src/interpreters/interpreter.rs:228:40
  24: databend_query::servers::http::v1::query::execute_state::ExecuteState::try_start_query::{{closure}}::{{closure}}
             at ./src/query/service/src/servers/http/v1/query/execute_state.rs:307:14
  25: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/framed.rs:49:27
  26: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:184:17
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:286:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:262:9
  29: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:81:9
  30: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:180:13
  31: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/framed.rs:49:9
  32: databend_query::servers::http::v1::query::execute_state::ExecuteState::try_start_query::{{closure}}
             at ./src/query/service/src/servers/http/v1/query/execute_state.rs:293:5
  33: databend_query::servers::http::v1::query::http_query::HttpQuery::try_create::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/query/service/src/servers/http/v1/query/http_query.rs:481:18
  34: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.6.4/src/future.rs:125:19
  35: <databend_common_base::runtime::runtime_tracker::TrackingFuture<T> as core::future::future::Future>::poll
             at ./src/common/base/src/runtime/runtime_tracker.rs:140:9
  36: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/framed.rs:49:27
  37: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:184:17
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:286:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:262:9
  40: async_backtrace::frame::active_frame::with
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:81:9
  41: async_backtrace::frame::Frame::in_scope
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/frame.rs:180:13
  42: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /home/eason/.cargo/git/checkouts/async-backtrace-dc8b2c67d0719549/dea4553/backtrace/src/framed.rs:49:9
  43: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:328:17
  44: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/loom/std/unsafe_cell.rs:16:9
  45: tokio::runtime::task::core::Core<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:317:13
  46: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:485:19
  47: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/panic/unwind_safe.rs:272:9
  48: std::panicking::try::do_call
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:554:40
  49: __rust_try
  50: std::panicking::try
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:518:19
  51: std::panic::catch_unwind
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panic.rs:142:14
  52: tokio::runtime::task::harness::poll_future
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:473:18
  53: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:208:27
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:153:15
  55: tokio::runtime::task::raw::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:271:5
  56: tokio::runtime::task::raw::RawTask::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:201:18
  57: tokio::runtime::task::LocalNotified<S>::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/mod.rs:416:9
  58: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:576:13
  59: tokio::runtime::coop::with_budget
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  60: tokio::runtime::coop::budget
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  61: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  62: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  63: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  64: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/scoped.rs:40:9
  65: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context.rs:176:26
  66: std::thread::local::LocalKey<T>::try_with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:286:16
  67: std::thread::local::LocalKey<T>::with
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/local.rs:262:9
  68: tokio::runtime::context::set_scheduler
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context.rs:176:9
  69: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  70: tokio::runtime::context::runtime::enter_runtime
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65:16
  71: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  72: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  73: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/task.rs:42:21
  74: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:328:17
  75: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/loom/std/unsafe_cell.rs:16:9
  76: tokio::runtime::task::core::Core<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:317:13
  77: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:485:19
  78: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/panic/unwind_safe.rs:272:9
  79: std::panicking::try::do_call
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:554:40
  80: __rust_try
  81: std::panicking::try
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:518:19
  82: std::panic::catch_unwind
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panic.rs:142:14
  83: tokio::runtime::task::harness::poll_future
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:473:18
  84: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:208:27
  85: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:153:15
  86: tokio::runtime::task::raw::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:271:5
  87: tokio::runtime::task::raw::RawTask::poll
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:201:18
  88: tokio::runtime::task::UnownedTask<S>::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/mod.rs:453:9
  89: tokio::runtime::blocking::pool::Task::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:159:9
  90: tokio::runtime::blocking::pool::Inner::run
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:513:17
  91: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/eason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:471:13
  92: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/sys_common/backtrace.rs:155:18
  93: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/mod.rs:529:17
  94: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/panic/unwind_safe.rs:272:9
  95: std::panicking::try::do_call
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:554:40
  96: __rust_try
  97: std::panicking::try
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:518:19
  98: std::panic::catch_unwind
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panic.rs:142:14
  99: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/thread/mod.rs:528:30
 100: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/ops/function.rs:250:5
 101: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2016:9
 102: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2016:9
 103: std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/sys/pal/unix/thread.rs:108:17
 104: <unknown>
 105: <unknown>
```

### How to Reproduce?

```sql
create table t(d tuple("A-a" int, b int));
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

This bug maybe cause session panic:

```sql
create table t(d tuple("A-a" int, b int));
```

panicked at src/query/ast/src/parser/parser.rs:67:13:

```txt
SyntaxException. Code: 1005, Text = error: 
  --> SQL:1:27
  |
1 | CREATE TABLE tc (d TUPLE(A-a Int32, b Int32))
  | ------           - -----  ^ unexpected `-`, expecting `BOOLEAN`, `BOOL`, `UINT8`, `TINYINT`, `UINT16`, `SMALLINT`, `UINT32`, `INT`, `INTEGER`, `UINT64`, `UNSIGNED`, `BIGINT`, `INT8`, `INT16`, `INT32`, `INT64`, `SIGNED`, `FLOAT32`, `FLOAT`, `FLOAT64`, `DOUBLE`, `DECIMAL`, `ARRAY`, `MAP`, `BITMAP`, `TUPLE`, `DATE`, `DATETIME`, `TIMESTAMP`, `BINARY`, `VARBINARY`, `LONGBLOB`, `MEDIUMBLOB`, `TINYBLOB`, `BLOB`, `STRING`, `VARCHAR`, `CHAR`, `CHARACTER`, `TEXT`, `VARIANT`, `JSON`, `GEOMETRY`, or `NULLABLE`
  | |                | |       
  | |                | while parsing TUPLE(<name> <type>, ...)
  | |                | while parsing type name
  | |                while parsing `<column name> <type> [DEFAULT <expr>] [AS (<expr>) VIRTUAL] [AS (<expr>) STORED] [COMMENT '<comment>']`
  | while parsing `CREATE [OR REPLACE] TABLE [IF NOT EXISTS] [<database>.]<table> [<source>] [<table_options>]`

```

### Modify

Modify tuple type parser. 

Add a check, if tuple filed name contain char that is not alphanumeric characters, will directly return error.

- Fixes #15125 
- 
## Tests

- [x] Unit Test

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by sundy-li — APPROVED** [review]

File: src/query/ast/src/parser/expr.rs [hunk 1]
```diff
@@ -1611,15 +1611,23 @@ pub fn type_name(i: Input) -> IResult<TypeName> {
...
         |(_, _, fields, _)| {
-            let (fields_name, fields_type) =
+            let (fields_name, fields_type): (Vec<String>, Vec<TypeName>) =
                 fields.into_iter().map(|(name, ty)| (name.name, ty)).unzip();
-            TypeName::Tuple {
+            if fields_name
+                .iter()
+                .any(|field_name| !field_name.chars().all(|c| c.is_ascii_alphanumeric()))
+            {
+                return Err(nom::Err::Error(ErrorKind::Other(
```
Comment (andylokandy) [inline src/query/ast/src/parser/expr.rs:1623]: Consider using failure:
```suggestion
                return Err(nom::Err::Failure(ErrorKind::Other(
```
