### PR TITLE
fix: `select *` shouldn't return results

### LINKED ISSUE #4728: Bug: `select *` should not return results
### What's Wrong?

`select *` returns results 
```
mysql> select *;
+-------+
| dummy |
+-------+
|     1 |
+-------+
1 row in set (0.03 sec)
```

### What You Expected?

`select *` reports error;
```
postgres=# select *;
2022-04-07 07:56:53.698 CST [17886] ERROR:  SELECT * with no tables specified is not valid at character 8
2022-04-07 07:56:53.698 CST [17886] STATEMENT:  select *;
ERROR:  SELECT * with no tables specified is not valid
LINE 1: select *;
```

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

- fix `select *`
- fix nightly clippy

## Changelog

- Bug Fix

## Related Issues

Fixes #4728

### CODE REVIEW

File: query/tests/it/sql/plan_parser.rs [hunk 1]
```diff
@@ -266,6 +266,12 @@ async fn test_plan_parser() -> Result<()> {
             sql: "DROP ROLE role1",
             expect: "Drop role role1 if_exists:false",
             error: "",
+        },
+        Test {
+            name: "select-without-table",
+            sql: "SELECT *",
+            expect: "",
+            error: "Code: 1015, displayText = SELECT * with no tables specified is not valid (while in analyze select projection)."
```
Comment (sundy-li) [inline query/tests/it/sql/plan_parser.rs:274]: How about adding a stateless test.  

select *;  -- {ErrorCode 1015}

Comment (xudong963) [reply query/tests/it/sql/plan_parser.rs:274]: done

Comment (sundy-li) [reply query/tests/it/sql/plan_parser.rs:274]: Just use:

```
select *; -- {ErrorCode 1015}
```

**Review by sundy-li — APPROVED** [review]
