### PR TITLE
fix(query):  account_admin should support grant ownership to new role after drop an created role

### LINKED ISSUE #14572: Feature: Account admin role need support grant ownership
**Summary**

Account admin role need support grant ownership

```sql
MySQL [(none)]> grant ownership on a.* to role role1;
Query OK, 0 rows affected (0.032 sec)

MySQL [(none)]> select * from system.databases;
+---------+--------------------+---------------------+-------+
| catalog | name               | database_id         | owner |
+---------+--------------------+---------------------+-------+
| default | system             | 4611686018427387905 | NULL  |
| default | information_schema | 4611686018427387906 | NULL  |
| default | a                  |                  12 | role1 |
| default | default            |                   1 | NULL  |
+---------+--------------------+---------------------+-------+
4 rows in set (0.021 sec)

MySQL [(none)]> drop role role1;
Query OK, 0 rows affected (0.024 sec)

MySQL [(none)]> grant ownership on a.* to role role2;
ERROR 1105 (HY000): IllegalGrant. Code: 1061, Text = Illegal GRANT/REVOKE command; only owner can grant ownership.
```

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

1. if has ownership but owner role not exists, the owner role will be set to account_admin

2. has_ownership should get ownership and role from meta

- Fixes #14572

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/14597)

### CODE REVIEW

**Comment by TCeason** [comment]
cc  @everpcpc  I already add label ci-benchmark-suites but not trigger the suite benchmark. Could you please help to this question?

File: src/query/service/src/interpreters/interpreter_privilege_grant.rs [hunk 1]
```diff
@@ -136,7 +137,14 @@ impl GrantPrivilegeInterpreter {
         // if the object's owner is None, it's considered as PUBLIC, everyone could access it
         let owner = user_mgr.get_ownership(tenant, owner_object).await?;
         if let Some(owner) = owner {
-            let can_grant_ownership = available_roles.iter().any(|r| r.name == owner.role);
+            // if object has ownership, but the owner role is not exists, set owner role to ACCOUNT_ADMIN,
+            // only account_admin can grant this object.
+            let role = if !user_mgr.exists_role(tenant, owner.role.clone()).await? {
+                BUILTIN_ROLE_ACCOUNT_ADMIN.to_string()
```
Comment (flaneur2020) [inline src/query/service/src/interpreters/interpreter_privilege_grant.rs:143]: how about moving the default `BUILTIN_ROLE_ACCOUNT_ADMIN` inside the `user_mgr.get_ownership` function in the L138?

the other places which calls `user_mgr.get_ownership` may also require this logic

Comment (flaneur2020) [reply src/query/service/src/interpreters/interpreter_privilege_grant.rs:143]: i'd prefer to keep the logic consistent across different places, the special case on logic is easier to be forgotten in the future, and might hide corner cases we did not recognize.

Comment (flaneur2020) [reply src/query/service/src/interpreters/interpreter_privilege_grant.rs:143]: it's nice to have this semantic described in a doc.

File: src/query/service/src/interpreters/interpreter_privilege_grant.rs [hunk 2]
```diff
@@ -136,7 +137,7 @@ impl GrantPrivilegeInterpreter {
         // if the object's owner is None, it's considered as PUBLIC, everyone could access it
         let owner = user_mgr.get_ownership(tenant, owner_object).await?;
         if let Some(owner) = owner {
-            let can_grant_ownership = available_roles.iter().any(|r| r.name == owner.role);
+            let can_grant_ownership = available_roles.iter().any(|r| r.name == role);
```
Comment (flaneur2020) [inline src/query/service/src/interpreters/interpreter_privilege_grant.rs:140]: typo? i guess the `role` variable is not defined in this function

File: src/query/service/src/sessions/session_privilege_mgr.rs [hunk 3]
```diff
@@ -267,14 +268,20 @@ impl SessionPrivilegeManager for SessionPrivilegeManagerImpl {
 
     #[async_backtrace::framed]
     async fn has_ownership(&self, object: &OwnershipObject) -> Result<bool> {
-        let role_mgr = RoleCacheManager::instance();
+        let user_mgr = UserApiProvider::instance();
         let tenant = self.session_ctx.get_current_tenant();
-
-        // if the object is not owned by any role, then considered as ACCOUNT_ADMIN, the normal users
-        // can not access it unless ACCOUNT_ADMIN grant relevant privileges to them.
```
Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:274]: the comment can be kept here?

Comment (TCeason) [reply src/query/service/src/sessions/session_privilege_mgr.rs:274]: This comment refactor in get ownership function.

File: src/query/service/src/sessions/session_privilege_mgr.rs [hunk 4]
```diff
@@ -267,14 +268,20 @@ impl SessionPrivilegeManager for SessionPrivilegeManagerImpl {
...
-        let owner_role_name = match role_mgr.find_object_owner(&tenant, object).await? {
-            Some(owner_role) => owner_role.name,
+        let owner_role_name = match user_mgr.get_ownership(&tenant, object).await? {
             None => BUILTIN_ROLE_ACCOUNT_ADMIN.to_string(),
+            Some(owner) => match user_mgr.get_role(&tenant, owner.role).await {
+                Ok(owner_role) => owner_role.name,
+                Err(e) => {
+                    if e.code() == ErrorCode::UNKNOWN_ROLE {
+                        BUILTIN_ROLE_ACCOUNT_ADMIN.to_string()
```
Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:279]: IMHO this unknown role fallback logic could be reduced as the logic has already been encapsulated in the `get_ownership` call, so just keep the match statement as before is ok? 

```
let owner_role_name = match role_mgr.find_object_owner(&tenant, object).await? {
            Some(owner_role) => owner_role.name,
            None => BUILTIN_ROLE_ACCOUNT_ADMIN.to_string(),
}
```

Comment (TCeason) [reply src/query/service/src/sessions/session_privilege_mgr.rs:279]: find_object_owner is use rolecache. So maybe we can replace it with get real meta ownership into.

Comment (TCeason) [reply src/query/service/src/sessions/session_privilege_mgr.rs]: find_object_owner is ok. Now load from cache do not have bug.

Comment (flaneur2020) [reply src/query/service/src/sessions/session_privilege_mgr.rs]: oh, sorry my comment made a typo in the function name:

IMO `role_mgr.get_ownership` is better, the cache do not offer many benefits here.

but as we have already encapsulated the logic about fallback to BUILTIN_ROLE_ACCOUNT_ADMIN, we can simplify the code as the following, do not need handle the UNKNOWN_ROLE error here again:

```
let owner_role_name = match role_mgr.get_ownership(&tenant, object).await? {
            Some(owner_role) => owner_role.name,
            None => BUILTIN_ROLE_ACCOUNT_ADMIN.to_string(),
}
```

File: src/query/service/src/sessions/session_privilege_mgr.rs [hunk 5]
```diff
@@ -267,14 +268,16 @@ impl SessionPrivilegeManager for SessionPrivilegeManagerImpl {
...
+        let user_mgr = UserApiProvider::instance();
         let tenant = self.session_ctx.get_current_tenant();
-
-        // if the object is not owned by any role, then considered as ACCOUNT_ADMIN, the normal users
-        // can not access it unless ACCOUNT_ADMIN grant relevant privileges to them.
-        let owner_role_name = match role_mgr.find_object_owner(&tenant, object).await? {
-            Some(owner_role) => owner_role.name,
+        let owner_role_name = match user_mgr.get_ownership(&tenant, object).await? {
             None => BUILTIN_ROLE_ACCOUNT_ADMIN.to_string(),
+            Some(owner) => match user_mgr.get_role(&tenant, owner.role).await {
```
Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:275]: this match statement could be shorten as `user_mgr.get_role(&tenant, owner.role).map(|r| r.name)?` ?

Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:275]: we can just return the owner.role here? as it's already the string we want

Comment (TCeason) [reply src/query/service/src/sessions/session_privilege_mgr.rs]: Ok. find_object_owner will return Result<Option<String>> now.

**Review by flaneur2020 — APPROVED** [review]
LGTM

**Review by flaneur2020 — APPROVED** [review]
