### PR TITLE
fix: right semi join returns wrong answer

### LINKED ISSUE #8075: Bug: right semi join reuturns wrong answer
**Summary**
```sql
mysql> create table t1(a int, b int);
Query OK, 0 rows affected (0.06 sec)

mysql> create table t2(a int, b int);
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t1 values(1, 2), (2, 3);
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t2 values(3, 4), (2, 3);
Query OK, 0 rows affected (0.04 sec)

mysql> select * from t2 right semi join t1 on t1.a >= t2.a;
Empty set (0.05 sec)
Read 4 rows, 24.00 B in 0.013 sec., 300.68 rows/sec., 1.76 KiB/sec.
```

Expected
```sql
mysql> select * from t1 left semi join t2 on t1.a >= t2.a;
+------+------+
| a    | b    |
+------+------+
|    2 |    3 |
+------+------+
1 row in set (0.05 sec)
Read 4 rows, 24.00 B in 0.014 sec., 291.33 rows/sec., 1.71 KiB/sec.
```

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #8075

### CODE REVIEW

**Comment by xudong963** [comment]
A flakey test  in test_stateful_cluster_linux
```
00_0000_copy_into_stage:                                                [ FAIL ] - result differs with:
--- /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0000_copy_into_stage.result	2022-10-09 13:42:23.114395017 +0000
+++ /runner/_work/databend/databend/tests/suites/1_stateful/00_copy/00_0000_copy_into_stage.stdout	2022-10-09 13:44:34.364826941 +0000
@@ -1,2 +1,2 @@
 2
-4
+3
```

File: src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs [hunk 1]
```diff
@@ -777,6 +777,9 @@ impl HashJoinState for JoinHashTable {
             let unmatched_build_block = self.row_space.gather(&unmatched_build_indexes)?;
             return Ok(vec![unmatched_build_block]);
         }
+        if blocks.is_empty() {
+            return Ok(blocks.to_vec());
```
Comment (youngsofun) [inline src/query/service/src/pipelines/processors/transforms/hash_join/join_hash_table.rs:781]:
```suggestion
            return Ok(vec![]);
```

**Review by youngsofun — APPROVED** [review]

**Review by leiysky — APPROVED** [review]
