### PR TITLE
fix(planner): Remove unnecessary required columns

### LINKED ISSUE #8442: Reuse required columns of subtree for `count(*)` aggregate

### PR DESCRIPTION
**Pull request by leiysky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Close #8442

### CODE REVIEW

**Review by xudong963 — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

File: src/query/sql/src/planner/optimizer/property/property.rs [hunk 1]
```diff
@@ -34,9 +34,15 @@ impl RequiredProperty {
 
 #[derive(Default, Clone, Debug)]
 pub struct RelationalProperty {
+    // Output columns of a relational expression
```
Comment (Xuanwo) [inline src/query/sql/src/planner/optimizer/property/property.rs:37]:
```suggestion
    /// Output columns of a relational expression
```

Comment (leiysky) [reply src/query/sql/src/planner/optimizer/property/property.rs]: Done.

**Review by sundy-li — APPROVED** [review]
