### PR TITLE
fix(query): create ownership obejct only check current_role privilege

### LINKED ISSUE #15742: bug: create <object> only need to check current role privilege
**Summary**

Whether set secondary role ALL or None, create <object> only need to check current role privilege

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

create ownership object only check current_role privilege

If do not have this limit, some unexpected problems may occur.

If a user does not bind a default role, the user can create an ownership object like db.

Then this user creates a database, it's will be owned role `public`. So all users can access this db. 

This may not be what users expect

Note:

If the user has the right privilege also can access the object.

- Fixes #15742

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15751)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
I'm not very familiar with these parts of the logic, so I won't be approving or rejecting this PR.

> Reviewed 1 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15751#-:-NzlFdeN4uKYUnYsjBi1:bnulje4)* status: 1 of 14 files reviewed, all discussions resolved (waiting on @andylokandy and @flaneur2020)

File: src/query/catalog/src/table_context.rs [hunk 1]
```diff
@@ -203,12 +203,13 @@ pub trait TableContext: Send + Sync {
     fn get_current_session_id(&self) -> String {
         unimplemented!()
     }
-    async fn get_all_effective_roles(&self) -> Result<Vec<RoleInfo>>;
+    async fn get_all_effective_roles(&self, create_object: bool) -> Result<Vec<RoleInfo>>;
```
Comment (flaneur2020) [inline src/query/catalog/src/table_context.rs:206]: maybe we do not need add extra parameter on this method? we can consider CREATE XXX is a special case, and only make special checks with current role inside these operations, and do not need others to care about this special case.

File: src/query/catalog/src/table_context.rs [hunk 2]
```diff
@@ -203,12 +203,13 @@ pub trait TableContext: Send + Sync {
...
 
     async fn validate_privilege(
         &self,
         object: &GrantObject,
         privilege: UserPrivilegeType,
+        create_object: bool,
```
Comment (flaneur2020) [inline src/query/catalog/src/table_context.rs:212]: is this parameter can be removed? can we directly use the `privilege` parameter to check it's a CREATE XXX operation or not?

Comment (TCeason) [reply src/query/catalog/src/table_context.rs:212]: Now create udf/stage/task need super privilege. So I think we can use parameter tmp. Until we support Create xxObject privilege then refactor this code.

File: src/query/service/src/sessions/session_privilege_mgr.rs [hunk 3]
```diff
@@ -264,15 +272,15 @@ impl<'a> SessionPrivilegeManager for SessionPrivilegeManagerImpl<'a> {
     }
 
     #[async_backtrace::framed]
-    async fn has_ownership(&self, object: &OwnershipObject) -> Result<bool> {
+    async fn has_ownership(&self, object: &OwnershipObject, create_object: bool) -> Result<bool> {
```
Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:275]: create_object -> current_role_only ?

`create_object` is bound to a concerete scenary, it might makes the semantic of this parameter decoupled from the special checks about `CREATE XXX`, but simply "only care the current role".

File: src/query/catalog/src/table_context.rs (hunk 2 above)
Comment (TCeason) [reply src/query/catalog/src/table_context.rs:212]: And this check, only need to check ownership object's created.

File: src/query/service/src/sessions/session_privilege_mgr.rs [hunk 4]
```diff
@@ -242,6 +249,7 @@ impl<'a> SessionPrivilegeManager for SessionPrivilegeManagerImpl<'a> {
         &self,
         object: &GrantObject,
         privilege: UserPrivilegeType,
+        create_object: bool,
```
Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:252]: can we derive `create_object` parameter by the `privilege` parameter ?

File: src/query/service/src/sessions/session_privilege_mgr.rs (hunk 3 above)
Comment (TCeason) [reply src/query/service/src/sessions/session_privilege_mgr.rs:275]: Yes . check_current_role_only is better.

File: src/query/service/src/sessions/session_privilege_mgr.rs (hunk 4 above)
Comment (TCeason) [reply src/query/service/src/sessions/session_privilege_mgr.rs:252]: Same like this:https://github.com/datafuselabs/databend/pull/15751/files#discussion_r1630942306

File: src/query/catalog/src/table_context.rs (hunk 2 above)
Comment (flaneur2020) [reply src/query/catalog/src/table_context.rs:212]: can also consider rename the `create_object` here as `check_current_role_only`, to describe what this function does instead of emphasis it's a special case.

File: src/query/catalog/src/table_context.rs (hunk 1 above)
Comment (flaneur2020) [reply src/query/catalog/src/table_context.rs:206]: we can consider move this logic out of `get_all_effective_roles`, and calls `get_current_role` on this special case.

File: src/query/service/src/sessions/session_privilege_mgr.rs [hunk 5]
```diff
@@ -183,7 +189,21 @@ impl<'a> SessionPrivilegeManager for SessionPrivilegeManagerImpl<'a> {
...
     #[async_backtrace::framed]
-    async fn get_all_effective_roles(&self) -> Result<Vec<RoleInfo>> {
+    async fn get_all_effective_roles(
+        &self,
+        check_current_role_only: bool,
+    ) -> Result<Vec<RoleInfo>> {
+        // the current role is always included in the effective roles.
+        self.ensure_current_role().await?;
+        // if ensure_current_role success, the current role can not be None.
+        let current_role = self.get_current_role().unwrap();
```
Comment (flaneur2020) [inline src/query/service/src/sessions/session_privilege_mgr.rs:199]: the old code can handle the default fallback logic without a hard `unwrap()`:

```
        let mut role_names = self
            .get_current_role()
            .map(|r| vec![r.name])
            .unwrap_or_default();
```

**Review by flaneur2020 — APPROVED** [review]
LGTM :rocket:

**Comment by TCeason** [comment]
Now I think it's time to merge this pr. cc @flaneur2020

**Comment by flaneur2020** [comment]
LGTM

**Comment by TCeason** [comment]
@BohuTANG Please merge this pr.

After this pr, create an object only check the current role. So if some user creates an object return error, he should run SQL `set role` to ensure the current role has created privilege or ownership.
