### PR TITLE
chore(planner): fix can_filter_null

### LINKED ISSUE #15256: bug: error using IFNULL or COALESCE in statement
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

https://github.com/datafuselabs/databend/releases/tag/v1.2.423-nightly

### What's Wrong?

Get error `no overload satisfies `assume_not_null(NULL)` when adding `IFNULL` or `COALESCE` into statement

See below SQL, if line 
`WHERE IFNULL(base.context, '') = ''`
reads
`WHERE base.context = ''`
Then the SQL works ok, but if COALESCE OR IFNULL used, it raises the exception

### How to Reproduce?

```sql
drop table if exists m1;
drop table if exists j1;
create table m1(id varchar, "context" varchar);
create table j1(id varchar);

WITH base
AS (
	SELECT id, context
	FROM m1
	)
	,src1
AS (
	SELECT base.id
	FROM base
	WHERE IFNULL(base.context, '') = ''
	)
	,join1
AS (
	SELECT id
	FROM j1
	)
SELECT src1.id
FROM src1
LEFT OUTER JOIN join1 ON true;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Dousir9**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

In `can_filter_null`, if the function is `assume_not_null` or `remove_nullable`, we cannot replace the column bindings with `Scalar::Null`.

- Fixes #15256 

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test  - _Explain why_

## Type of change

- [x] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/datafuselabs/databend/15298)

### CODE REVIEW

File: src/query/sql/src/planner/optimizer/rule/rewrite/push_down_filter_join/outer_join_to_inner_join.rs [hunk 1]
```diff
@@ -186,6 +186,13 @@ pub fn can_filter_null(
                     Ok(())
                 }
                 ScalarExpr::FunctionCall(func) => {
+                    // If the function is `assume_not_null`, we can not replace
+                    // the column bindings with `Scalar::Null`.
+                    if func.func_name == "assume_not_null" {
```
Comment (sundy-li) [inline src/query/sql/src/planner/optimizer/rule/rewrite/push_down_filter_join/outer_join_to_inner_join.rs:191]: there is alias `remove_nullable`

**Review by xudong963 — APPROVED** [review]
