### PR TITLE
fix(query): show db/tab/col should not display no privelige object

### LINKED ISSUE #12082: bug: show db/table/cols will display object that the user does not have privilege.
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

As titile

### How to Reproduce?

```sql
create user a identified by '123';
grant all on default.* to a;
```

use the user a connect to databend-query, and execute statement `show databases`, the result contains db: information_schema.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

show db/tab/col should not display no privelige object

- Closes #12082

### CODE REVIEW

File: src/query/sql/src/planner/binder/ddl/column.rs [hunk 1]
```diff
@@ -24,6 +30,9 @@ use crate::BindContext;
 use crate::Binder;
 use crate::SelectBuilder;
 
+pub const GLOBAL_PRIV: &str = "0x5f3759df";
```
Comment (BohuTANG) [inline src/query/sql/src/planner/binder/ddl/column.rs:33]: Please don't use constant value here, we should xor the permission as the final value.

**Comment by BohuTANG** [comment]
askbend:summary

**Comment by TCeason** [comment]
test on ci-cloud:

image

**Review by BohuTANG — APPROVED** [review]

**Review by zhyass — APPROVED** [review]
