### PR TITLE
fix: left join returns wrong answer

### LINKED ISSUE #7650: bug: left join returns wrong answer
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```sql
mysql> create table t2 (a INT, s STRING);
Query OK, 0 rows affected (0.05 sec)

mysql> create table t1 (a INT, s STRING);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 VALUES (1, 'a' ), (2, 'A'), (3, 'c'), (4, 'D');
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t2 values (1, 'A'), (2, 'B'), (3, 'C'), (4, 'E');
Query OK, 0 rows affected (0.04 sec)

mysql> select * from t1 left join t2 on t1.s = t2.s;
+------+------+------+------+
| a    | s    | a    | s    |
+------+------+------+------+
|    1 | a    | NULL | NULL |
|    2 | A    | NULL | NULL |
|    3 | c    | NULL | NULL |
|    4 | D    | NULL | NULL |
+------+------+------+------+
4 rows in set (0.05 sec)
Read 8 rows, 120.00 B in 0.013 sec., 606.22 rows/sec., 8.88 KiB/sec.

mysql>
```

### How to Reproduce?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by xudong963**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

Fixes #7650

### CODE REVIEW

File: src/query/service/src/sql/planner/binder/join.rs [hunk 1]
```diff
@@ -448,9 +448,11 @@ impl<'a> JoinConditionResolver<'a> {
         // Bump types of left conditions and right conditions
         let left_type = left.data_type();
         let right_type = right.data_type();
-        let least_super_type = compare_coercion(&left_type, &right_type)?;
-        left = wrap_cast_if_needed(left, &least_super_type);
-        right = wrap_cast_if_needed(right, &least_super_type);
+        if left_type.ne(&right_type) {
```
Comment (sundy-li) [inline src/query/service/src/sql/planner/binder/join.rs:451]: the `compare_coercion` already checked that `left_type` eq `right_type`.

I don't know the root reason why it works fine after your commit.

**Review by sundy-li — APPROVED** [review]

**Review by BohuTANG — APPROVED** [review]

**Comment by xudong963** [comment]
One test in cluster mode failed, but mergify merged the ticket. :/
