### PR TITLE
Fix Unable to get field name bug

### LINKED ISSUE #4012: Unable to get field named
bug1:
```
mysql> select 1 and number>1 from numbers(10);
ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named "(1 AND (number > 1))". Valid fields: ["number", "(number > 1)"].
```

bug2:
```
mysql> select number<3 or number>5 from numbers(10);
ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named "((number < 3) OR (number > 5))". Valid fields: ["number", "((number < 3) or (number > 5))"].
```

They're caused by constant folding optimization(constant condition remove). Bug2 is  caused by the case sensitivity of the operator https://github.com/datafuselabs/databend/blob/main/query/src/optimizers/optimizer_constant_folding.rs#L164.

### PR DESCRIPTION
**Pull request by zhyass**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

CC @Veeupup , it's another bug, I just move `constant_cond_remove` from `constant_folding` to `expression_transform`. The problem `null value will be optimized as false` described in the issue #4004  is still exists.
I think doing this in the filter maybe has no effect.

This is the same problem as issue #2165

## Changelog

- Bug Fix

## Related Issues

Fixes #4012 

## Test Plan

Unit Tests

### CODE REVIEW

File: query/tests/it/optimizers/optimizer_expression_transform.rs [hunk 1]
```diff
@@ -115,6 +115,70 @@ async fn test_expression_transform_optimizer() -> Result<()> {
                 \n    Filter: true\
                 \n      ReadDataSource: scan schema: [number:UInt64], statistics: [read_rows: 0, read_bytes: 0, partitions_scanned: 0, partitions_total: 0], push_downs: [projections: [0], filters: [true]]",
             },
+            Test {
```
Comment (Veeupup) [inline query/tests/it/optimizers/optimizer_expression_transform.rs:118]: maybe add a new test to check it?

File: query/src/optimizers/optimizer_expression_transform.rs [hunk 2]
```diff
@@ -201,7 +303,8 @@ impl PlanRewriter for ExprTransformImpl {
         }
 
         let new_input = self.rewrite_plan_node(plan.input.as_ref())?;
-        let new_predicate = Self::boolean_transformer(&plan.predicate)?;
+        let new_predicate = Self::constant_transformer(&plan.predicate)?;
```
Comment (Veeupup) [inline query/src/optimizers/optimizer_expression_transform.rs:306]: `having`?

Comment (zhyass) [reply query/src/optimizers/optimizer_expression_transform.rs:306]: > `constant_transformer` for `having`?

Thanks for reminding, added

**Comment by zhyass** [comment]
`explain` in `MySQL`, It seems that mysql is only optimized for filter/join/having.
```
mysql> explain select true and a>0 from t;
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------+
|  1 | SIMPLE      | t     | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    2 |   100.00 | NULL  |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------+
1 row in set, 1 warning (0.08 sec)

mysql> show warnings\G
*************************** 1. row ***************************
  Level: Note
   Code: 1003
Message: /* select#1 */ select (true and (`zzq`.`t`.`a` > 0)) AS `true and a>0` from `zzq`.`t`
1 row in set (0.04 sec)

mysql> explain select * from t where true and a>0;
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | t     | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    2 |    50.00 | Using where |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------------+
1 row in set, 1 warning (0.04 sec)

mysql> show warnings\G
*************************** 1. row ***************************
  Level: Note
   Code: 1003
Message: /* select#1 */ select `zzq`.`t`.`a` AS `a`,`zzq`.`t`.`b` AS `b`,`zzq`.`t`.`c` AS `c` from `zzq`.`t` where (`zzq`.`t`.`a` > 0)
1 row in set (0.04 sec)
```

I

**Review by Veeupup — APPROVED** [review]
LGTM
